### ISSUE TITLE
sync/atomic: atomics are not implemented

### ISSUE THREAD

**Issue by imle** [tinygo-org/tinygo#1031]
Working off the dev branch.

I'm sure that this isn't a great pattern for microcontrollers, but I want to use `io.Pipe()` and there seems to be some issue importing it as noted below.

```
tinygo:ld.lld: error: undefined symbol: sync/atomic.LoadPointer
```

When I checked the [lang-support](https://tinygo.org/lang-support/stdlib/) page, it shows that package is supported and I was curious if this is something that is currently expected or not.

Code to reproduce.

```golang
package main

import (
	"bytes"
	"fmt"
	"io"
)

func main() {
	r, w := io.Pipe()

	go func() {
		fmt.Fprint(w, "some text to be read\n")
		w.Close()
	}()

	buf := new(bytes.Buffer)
	buf.ReadFrom(r)
	fmt.Print(buf.String())
}
```

**Comment by imle** [comment]
Good to know, sorry for the misunderstanding. I may take a look at that PR if I can find some time. Do you happen to know if there was anything keeping it from functioning or was it just a time investment?

**Comment by aykevl** [comment]
I hit some issues with LLVM that made it hard to test, probably caused by the fact that some platforms lack support for atomics.

**Comment by imle** [comment]
Gotcha, is there a roadmap of some kind for that functionality? I'd love to try to help if I can.

**Comment by aykevl** [comment]
I have written a new PR that implements atomics: #1113.

**Comment by jfcg** [comment]
Hi is there a plan to add sync/atomic.AddUint32() ?
at least for platforms that support it. [sorty](https://github.com/jfcg/sorty) needs it :)

**Comment by niaow** [comment]
Atomics are implemented on all major TinyGo platforms in the dev branch. The next release (v0.14) which is coming up will include these changes.
