### ISSUE TITLE
transform (coroutines): undef task handle in call to closure

### ISSUE THREAD

**Issue by asdine** [tinygo-org/tinygo#1032]
```go
func foo() {
	ch := make(chan int)

	fn := func(nb int) {
		ch <- nb
	}

	go func() {
		fn(10)
	}()

	fmt.Println(<-ch)
}

func main() {
  foo()
}
```

This causes the following compilation error:

```
async function exp.foo$1 used as function pointer
```

The same happens when I replace the fn closure by a method.

I compiled to wasm using the `0.12.0` docker image with the following params:

```bash
docker run ... \
    tinygo/tinygo:0.12.0 tinygo build -o /dist/exp.wasm -target wasm --no-debug exp
```

**Comment by jaddr2line** [comment]
On the current development branch, that part seems to have been fixed an replaced by a different problem: it now segfaults.

**Comment by jaddr2line** [comment]
```
tail call void @"/tmp/indirectasync.go.foo$1"(i64 10, i8* nonnull %ch, i8* undef)
```

It appears that we are passing in an undefined task handle, which is causing a segfault when we attempt to update the state.

**Comment by jaddr2line** [comment]
v0.13 is getting close to release, so the fix is probably going to have to be pushed back into the next release window.

**Comment by jaddr2line** [comment]
Alright, I found the cause of the problem: https://github.com/tinygo-org/tinygo/blob/5308e8903e8c1a79151c8262fc2992eb405ce049/transform/func-lowering.go#L147

This causes the pass to leave behind an indirect function call, which causes the coroutine lowering pass to fail to detect the call. As a result, the call is not lowered, and the parent handle is not provided.
