### ISSUE TITLE
check what golang packages tinygo supports

### ISSUE THREAD

**Issue by ghost** [tinygo-org/tinygo#106]
https://github.com/trashhalo/tinygo-import-report

think this is very useful. Helped me alot.

It can export the report to markdown i think with a bit of work and so can be a nice thing for the project.

**Comment by deadprogram** [comment]
Agreed, this would be a great thing to have as part of the CI build. I'm sure a PR that added this would be gratefully accepted.

**Comment by deadprogram** [comment]
This is now part of the Tinygo site:
https://github.com/tinygo-org/tinygo-site/commit/74191c6f5d824de6f7d57879fbefab7fdface288

Closing.
