### ISSUE TITLE
compileopts: better error reporting of unsupported flags

### ISSUE THREAD

**Issue by aykevl** [tinygo-org/tinygo#1062]
There are a few flags that currently don't have proper error checking. The ones I found are `-gc`, `-scheduler` and `-size`. Using the wrong value will lead to no or unexpected errors.

I think the best way to handle it is to add a new method to `compileopts.Config` that checks whether there are any faulty flags, which is then called from the main function.

**Comment by trevor403** [comment]
I can take this issue. I'll post a PR tomorrow.

**Comment by cebernardi** [comment]
@trevor403 I just saw your comment here, I was "assigned" this issue on slack 19th of April..
I'm sorry we overlapped

**Comment by trevor403** [comment]
That is totally okay! :smile:

**Comment by niaow** [comment]
Has this issue been sufficiently resolved?

**Comment by aykevl** [comment]
Yes, it will be included in the next release (see the label).

**Comment by deadprogram** [comment]
This was released with v0.14.0 so now closing. Please reopen if needed. Thanks!
