### ISSUE TITLE
no up to date build for armhf

### ISSUE THREAD

**Issue by dominictarr** [tinygo-org/tinygo#1072]
I tried installing on pinepro, following instructions on website

https://tinygo.org/getting-started/linux/#ubuntu-debian

but 0.13.0 is not available for armhf. installing 12 instead.
excited to try tinygo->wasm, looks good!

**Comment by aykevl** [comment]
The latest 0.13.1 release does include ARM binaries (and includes some non-wasm bug fixes). See the release here: https://github.com/tinygo-org/tinygo/releases/tag/v0.13.1

Closing now. The documentation would still need to be updated, however.
