### ISSUE TITLE
Make a Telegram discussion group

### ISSUE THREAD

**Issue by glococo** [tinygo-org/tinygo#1117]
Hi, I was looking for chat about different things regarding TinyGo, and tried to join the slack gophers without success.
Also I sometimes feel submiting an issue is like making noise. 

I got used to work with many tools, but the best I work with is Telegram.
Would you like to start a Telegram Group ?

**Comment by niaow** [comment]
The gopher slack invite has been fixed (explanation of what happened: https://twitter.com/theckman/status/1262083431682281473)

**Comment by glococo** [comment]
Thanks, now it worked. I'm in.
