### ISSUE TITLE
Unused Variable 'AlignedSize' 

### ISSUE THREAD

**Issue by selahaddinh** [tinygo-org/tinygo#1135]
While compiling from the source code with commands:
export CC=clang
export CXX=clang++
make llvm-build

I encountered with the following Warning: 
.../tinygo/llvm-project/llvm/lib/DebugInfo/CodeView/TypeStreamMerger.cpp:392:12: warning: unused variable 'AlignedSize' [-Wunused-variable]
  unsigned AlignedSize = alignTo(OriginalType.RecordData.size(), 4);

Is it something to do with tinygo, or LLVM related problem?

**Comment by niaow** [comment]
That's LLVM's problem

**Comment by selahaddinh** [comment]
Thanks for the informing, then I am closing the issue.
