### ISSUE TITLE
cgo: Looks buggy when in used in a library

### ISSUE THREAD

**Issue by racerxdl** [tinygo-org/tinygo#1148]
I think I found a bug on cgo implementation.
I used the following snippet to test:

```go
import (
    _ "unsafe"
)
/*
void hue() {}
*/
import "C"
func init() {
    C.hue()
}
```

* If the code is in a tinygo source code (like runtime or something else) it works as expected.
* If the code is in the application I'm compilling it works as expected.
* If the code is in a library that my application uses it gives me the following error:

```
panic: cgo: failed to parse source with libclang

goroutine 1 [running]:
github.com/tinygo-org/tinygo/cgo.(*cgoPackage).parseFragment(0xc0000ec460, 0xc000127600, 0x221, 0xc0007a0e00, 0x11, 0x20, 0xc000200180, 0x33, 0x6)
	/media/ELTN/Works/tinygo/cgo/libclang.go:113 +0x7f0
github.com/tinygo-org/tinygo/cgo.Process(0xc0001f86c8, 0x1, 0x1, 0xc000032064, 0x57, 0xc00039c580, 0xc0000dc500, 0x11, 0x20, 0x0, ...)
	/media/ELTN/Works/tinygo/cgo/cgo.go:394 +0x1e33
github.com/tinygo-org/tinygo/loader.(*Package).parseFiles(0xc000237280, 0xc000a2d6e0, 0x3, 0x4, 0x0, 0x0)
	/media/ELTN/Works/tinygo/loader/loader.go:424 +0x3e2
github.com/tinygo-org/tinygo/loader.(*Package).Parse(0xc000237280, 0x0, 0x0)
	/media/ELTN/Works/tinygo/loader/loader.go:357 +0x8a
github.com/tinygo-org/tinygo/loader.(*Program).Parse(0xc0000f21c0, 0x8cd835, 0x1)
	/media/ELTN/Works/tinygo/loader/loader.go:226 +0x6b
github.com/tinygo-org/tinygo/compiler.Compile(0x8cd835, 0x1, 0x1e57be0, 0xc0002cf080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/media/ELTN/Works/tinygo/compiler/compiler.go:190 +0xab2
github.com/tinygo-org/tinygo/builder.Build(0x8cd835, 0x1, 0x7fff3d24765f, 0x6d, 0xc0002cf080, 0xc0001f3c90, 0x0, 0x0)
	/media/ELTN/Works/tinygo/builder/build.go:41 +0x9e
main.Build(0x8cd835, 0x1, 0x7fff3d24765f, 0x6d, 0xc0000f20e0, 0x0, 0x1d)
	/media/ELTN/Works/tinygo/main.go:97 +0xc5
main.main()
	/media/ELTN/Works/tinygo/main.go:864 +0x1b2b
```

Locally I'm using the nintendoswitch branch but that happens as well in the dev branch.

The code snippet where the error is has a comment saying the panic is probably a bug in the libclang usage:

```go
	if errCode != 0 {
		// This is probably a bug in the usage of libclang.
		panic("cgo: failed to parse source with libclang")
	}
```

If I just change the panic to a error message, the code compiles and everything works as expected.

**Comment by aykevl** [comment]
Probably not the issue, but I see that the `hue` function is a variadic function call (which is easy to miss in C). You might want to specify this instead:

    void hue(void) {}

Also, function definitions are currently not compiled in CGo headers.

**Comment by racerxdl** [comment]
To be honest, thats totally optional to simulate the issue. I just put that to use C, but this also gives the same error:

```go
import (
    _ "unsafe"
)
/*
#cgo LDFLAGS: -lnx
*/
import "C"
```

Just importing C is enough to cause the error. The code I provided was just to use something from Cgo.

**Comment by aykevl** [comment]
I can't reproduce this. Can you maybe make a small repository or gist with all the files necessary for this?

I made two files:

```go
// cgo-import-test/cgo.go
package importtest

import (
	_ "unsafe"
)

/*
#cgo LDFLAGS: -lnx
*/
import "C"

// testfile.go
package main

import _ "./cgo-import-test"

func main() {}
```

I get the following error:

```
$ tinygo run testfile.go
ld: error: unable to find library -lnx
collect2: error: ld returned 1 exit status
error: failed to link /tmp/tinygo421895540/main: exit status 1
```

This error is entirely expected.

Additionally, I'm sure CGo usually works when used in packages as I frequently use it for the github.com/tinygo-org/bluetooth package.

**Comment by racerxdl** [comment]
@aykevl well that does not happen doing import from different package of the same project. It needs to be a external library, and I noticed that it needs to use go-modules. For example:
https://github.com/racerxdl/gonx/blob/dev/base.go#L6-L7

Just trying to import that `gonx` breaks the compilation with the message I said.

**Comment by racerxdl** [comment]
Ok, I just found it was some cflags defined for the nintendo switch that was breaking the compilation. It's not related to tinygo!

Sorry for the mess :((

**Comment by aykevl** [comment]
Glad you found the issue! I was surprised, as I had been using CGo (with and without Go modules) for a while for BLE support.

**Comment by racerxdl** [comment]
Yeah, I was trying to narrow down the issues, then I found that if the target wasn't nintendoswitch it worked perfectly. Solved now :D
