### ISSUE TITLE
gen-device-svd: unexported clusters

### ISSUE THREAD

**Issue by yannishuber** [tinygo-org/tinygo#1163]
When generating the Go definition for the K210 chip the `gen-device-svd.go` script generates cluster with lowercase names and are therefore not exported.

The result of the generation for the PLIC type for example is the following:
```go
// Platform-Level Interrupt Controller
type PLIC_Type struct {
	PRIORITY       [1024]volatile.Register32
	PENDING        [32]volatile.Register32
	_              [3968]byte
	target_enables [4]struct {
		ENABLE [32]volatile.Register32
	}
	_       [2088448]byte
	targets [4]struct {
		THRESHOLD volatile.Register32
		CLAIM     volatile.Register32
		_         [4084]byte
		_RESERVED volatile.Register32
	}
}
```
`target_enables` and `target` should be uppercase.

**Comment by aykevl** [comment]
The PR has been merged, so closing.
