### ISSUE TITLE
d.WriteByte() undefined for Arduino Nano and Bluepill

### ISSUE THREAD

**Issue by alankrantas** [tinygo-org/tinygo#1228]
I'm testing NeoPixel (WS2812) modules on some boards, and for Arduino Nano and Bluepill (for now I build the code and upload it via STLink Utility) the pin's WriteByte() are not defined:

```
go\src\tinygo.org\x\drivers\ws2812\ws2812.go:23:5: d.WriteByte undefined (type Device has no field or method WriteByte)
go\src\tinygo.org\x\drivers\ws2812\ws2812.go:32:5: d.WriteByte undefined (type Device has no field or method WriteByte)
go\src\tinygo.org\x\drivers\ws2812\ws2812.go:33:5: d.WriteByte undefined (type Device has no field or method WriteByte)
go\src\tinygo.org\x\drivers\ws2812\ws2812.go:34:5: d.WriteByte undefined (type Device has no field or method WriteByte)
```

Arduino Uno does has WriteByte() though.

**Comment by deadprogram** [comment]
The assembly language required for this particular device is not available for every MCU. This is a somewhat unique characteristic of the WS2818 due to the highly precise timing it requires.

I do not think either the Arduino or STM32 are currently supported. We'd love to get a PR that adds it!

**Comment by alankrantas** [comment]
I think WS2818 runs pretty well on Uno, and Nano is essentially a smaller Uno with an older bootloader. In fact - just tested it - I can build a hex file targeted for Uno and then use AVR to upload it to Nano.

![ezgif-4-db324ce1df65](https://user-images.githubusercontent.com/44191076/87217831-47706580-c380-11ea-9845-7b80e31edfc8.gif)

Any tips for where should I look at? I haven't yet been able to figure it out.

**Comment by deadprogram** [comment]
See https://github.com/tinygo-org/drivers/tree/master/ws2812 for TinyGo driver for WS2812.

**Comment by aykevl** [comment]
In particular, look at https://github.com/tinygo-org/drivers/blob/master/ws2812/ws2812_avr_16m.go, where you can add the Nano to the list of build tags (now just `arduino`).

**Comment by alankrantas** [comment]
Thanks, I made a PR at the Tinygo driver repository. Close this for now.
