### ISSUE TITLE
time.Sleep with a negative argument hangs forever

### ISSUE THREAD

**Issue by rogpeppe** [tinygo-org/tinygo#1268]
commit: 50a677e9b791bbf34eaa9effca231a036a284ce8
platform: itsybitsy-m4

If the duration passed to `time.Sleep` is negative, it seems to hang up forever rather than returning immediately.
This means that an idiom like:

     time.Sleep(time.Until(deadline))

can deadlock if the deadline has passed.

**Comment by niaow** [comment]
I will take a look at this soon to confirm whether this is still a problem and address it.

**Comment by niaow** [comment]
I have confirmed that this issue is still maybe possible in some form, and made a fix: #2394
