### ISSUE TITLE
bluepill flashing not working

### ISSUE THREAD

**Issue by ski7777** [tinygo-org/tinygo#1270]
I'm very new to tinygo and I wanted try it on my bluepill board.
Sadly flashing does not work. I tested it using a cheap china ST-LINK v2 and the Nucleo ST-Link (broken apart from nucleo itself).
This is my Code:
```go
package main

import (
	"machine"
	"time"
)

func main() {
	led := machine.LED
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})
	for {
		led.Low()
		time.Sleep(time.Millisecond * 1000)

		led.High()
		time.Sleep(time.Millisecond * 1000)
	}
}
```

This is the shell output:
```
tinygo flash -target bluepill main.go
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Error: open failed
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 506
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

error: failed to flash /tmp/tinygo361065343/main.hex: exit status 1
```

Is there any magic I forgot? Help is really appreciated.

Thanks
Raphael

**Comment by aykevl** [comment]
It appears that the ST-Link v2 wasn't properly connected, otherwise you'd see a message like `Target voltage: 3.249768`. There might be a Linux permission problem so that OpenOCD cannot access the programmer, perhaps you could check dmesg?

**Comment by ski7777** [comment]
Do I need special udev configuration?

Ayke <notifications@github.com> schrieb am Di., 28. Juli 2020, 13:55:

**Comment by alankrantas** [comment]
Just tried it on my RPi 3 and found a solution. You'll need to grant permission for openOCD:

```
sudo nano /etc/udev/rules.d/98-stlink.rules
```

and add

```
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="374b", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="3748", MODE="666"
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="3744", MODE="666"
```

in the file.

**Comment by ski7777** [comment]
I applied this. Next error:
```
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v28 API v2 SWIM v7 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.244444
Warn : UNEXPECTED idcode: 0x2ba01477
Error: expected 1 of 1: 0x1ba01477
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 506
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

error: failed to flash /tmp/tinygo060123624/main.hex: exit status 1
```

How do I need to set the BOOT jumpers? Do I need to connect the RST line?

Thanks
Raphael

**Comment by alankrantas** [comment]
Maybe this would help?
https://community.platformio.org/t/cannot-upload-to-stm32-bluepill-board-over-stlink-v2/3492/13

No, I didn't connect RST and GND. Both jumpers stay at 0.

**Comment by ski7777** [comment]
This seems to go in the right direction but how can I do this in tinygo?

**Comment by alankrantas** [comment]
The STM32duino for Arduino IDE does have an option for flashing to fake STM32F103s. So I assume there's a way to tell the openOCD to use a different device ID. But modifying the openOCD config file on your own system is probably quicker. 

Edit: found this discussion https://github.com/tinygo-org/tinygo-site/pull/93

**Comment by ski7777** [comment]
But where can I find this file?

Alan Wang <notifications@github.com> schrieb am Mi., 29. Juli 2020, 02:18:

**Comment by alankrantas** [comment]
I installed openOCD in my working laptop's VM Ubuntu, and it's at **/usr/share/openocd/scripts/target/stm32f1x.cfg**.

It's the same on my Raspberry Pi.

**Comment by ski7777** [comment]
Now it works but I think that should not be the way to go. A global fix would be better :)

**Comment by kenbell** [comment]
This is fixed given there's a `bluepill-clone` target? (which worked well enough for me on a cloned bluepill)

I'll close in a few days unless someone thinks there's a reason to keep this open.

**Comment by kenbell** [comment]
Closing since there's the `bluepill-clone` target
