### ISSUE TITLE
Using Liquidcrystal I2C with arduino nano

### ISSUE THREAD

**Issue by wlwatkins** [tinygo-org/tinygo#1271]
Hi, tinygo looks great to dev. for arduino instead of C. But I cannot find tutorials or example that would help me control a liquide crystal display htrough I2C such as https://www.ebay.fr/itm/IIC-I2C-TWI-SP-I-Serial-Interface1602-16X2-Character-LCD-Module-Display-Blue-/310565065847

any clues ?

**Comment by alankrantas** [comment]
I added a driver for it (https://github.com/tinygo-org/drivers/pull/173) but it's still waiting for review. It works pretty well on Arduino Uno and Nano.

**Comment by wlwatkins** [comment]
Woaw !! this is great ! Will be testing it thoroughly. It worked like a charm with your example.
