### ISSUE TITLE
Error using goroutines: attempted to start a goroutine without a scheduler

### ISSUE THREAD

**Issue by wlwatkins** [tinygo-org/tinygo#1272]
Hi, 

when I want to do a simple goroutine, (looking for button press) I get this compilation error
```
main.go:596:2: attempted to start a goroutine without a scheduler
```

I see that goroutines are supported on arduino (in my case nano). What am I missing? what is a scheduler?

**Comment by alankrantas** [comment]
Scheduler is default off on 8-bit AVR boards I think. It's the Golang mechanism to run goroutines.

You have to enable it like this:

```
tinygo flash -scheduler coroutines -target xxx
```

**Comment by wlwatkins** [comment]
oh, simple enough. I did not see that in the documentation. 
(side question @alankrantas, i saw you talked about servo library, on another issue. Do you have info on that?)

**Comment by niaow** [comment]
AVR does not support coroutines. You need `-scheduler tasks`.

**Comment by alankrantas** [comment]
Interesting, because I can run the blinky2 example (which use goroutines) on my Uno with the -scheduler flag. I'll try the other one later.

Servo control involves PWM frequency setting and it turned out to be difficult to implement that function across different hardwares. So no luck for now.

**Comment by niaow** [comment]
Hmm. . . maybe LLVM fixed the bug, or maybe it is just somehow working anyway.

**Comment by alankrantas** [comment]
Yeah... just tried it with two LEDs on a Nano. Both ```-scheduler coroutines``` and ```-scheduler tasks``` compiles and runs. However the timing is terrible, very inaccurate. :p
