### ISSUE TITLE
add -short flag for tests

### ISSUE THREAD

**Issue by jfcg** [tinygo-org/tinygo#1283]
Hi,
In the Go toolchain, `-short` flag (to `go test`) is used to signal "summary testing" in a Go project. Some tests could be skipped, and some tests could omit some long running cases. It is a handy feature. It should be trivial to add it to TinyGo and it would be useful for projects that use TinyGo, I think.

Note:
- In `*_test.go` files, the flag can be queried as `testing.Short()`.
- It makes sense to add this flag with the relevant `Skip*()` [methods](https://golang.org/pkg/testing/).

**Comment by dgryski** [comment]
`testing.Short()` was added in https://github.com/tinygo-org/tinygo/pull/2144

**Comment by deadprogram** [comment]
Thanks for the reminder @dgryski now closing.
