### ISSUE TITLE
docker run causes this error: "error: cannot locate $GOROOT, please set it manually"

### ISSUE THREAD

**Issue by hajimehoshi** [tinygo-org/tinygo#1302]
Hi,

I'm trying tinygo with Docker, but I saw this error:

```
hajimehoshi@Hajimes-MacBook-Pro-2020 ~/test 
$ cat main.go 
package main
func main() {
}
hajimehoshi@Hajimes-MacBook-Pro-2020 ~/test 
$ docker run --rm -v $(pwd):/src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm main.go 
error: cannot locate $GOROOT, please set it manually
```

What and how can I specify GOROOT? I specified `-e GOROOT=/usr/local/go` but this failed due to its version.

```
$ docker run --rm -v $(pwd):/src -e "GOROOT=/usr/local/go" tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm main.go
error: requires go version 1.11 through 1.15, got go1.5
```

Thanks,

**Comment by sago35** [comment]
0.14.0 and 0.14.1 of the docker image seem to be broken.
We'll make a fix for this, so please wait a while.

**Comment by sago35** [comment]
Hi @hajimehoshi 

Thank you for reporting this.
The following Dockerfile will be used to work around until we've reviewed the fixes.

https://github.com/tinygo-org/docker/pull/10

**Comment by hajimehoshi** [comment]
Thanks. Apparently this was already merged. Would `docker pull` fix the issue?

**Comment by sago35** [comment]
The docker image has also been updated.
Please do a docker pull.

**Comment by hajimehoshi** [comment]
OK I'll try that later. Thank you very much!

**Comment by hajimehoshi** [comment]
```
$ docker run --rm -v $(pwd):/src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm ./main.go 
# _/main.go
cannot find package "." in:
        /main.go
```

Now I found another error.

EDIT:

```
docker run --rm -v $(pwd):/src tinygo/tinygo:latest tinygo build -o wasm.wasm -target=wasm /src/main.go
```

worked!

**Comment by sago35** [comment]
Add '-w /src' to docker run command. @hajimehoshi

**Comment by hajimehoshi** [comment]
Thanks!

I'll close this issue.
