### ISSUE TITLE
Point releases for arm

### ISSUE THREAD

**Issue by mcrosson** [tinygo-org/tinygo#1312]
I was just reviewing the releases page for the project and notice point releases don't include ```deb``` files for arm but the major releases do.

Would it be possible to include arm releases for point releases of the project?

**Comment by deadprogram** [comment]
Actually this was just overlooked. @aykevl can you build this?

**Comment by aykevl** [comment]
Yes, I'll do that now.

**Comment by aykevl** [comment]
Done.
