### ISSUE TITLE
docker: install LLVM version that allows for our Xtensa support for tinygo-dev

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#1337]
We will need to install a version of LLVM in order to build the tinygo-dev Docker container in a way that includes this support:
https://github.com/tinygo-org/tinygo/blob/dev/Dockerfile#L4-L7

**Comment by aykevl** [comment]
I do not think Espressif provides binaries yet, see https://github.com/espressif/llvm-project/issues/36 for example.
I'm not sure whether compiling it from source for Docker is feasible, to be honest.

**Comment by deadprogram** [comment]
Valid point. If the Espressif people setup a build server with binaries, that would be ideal.

If not, perhaps we should setup our own build server perhaps as a separate docker container/stage so build times could improve.

**Comment by deadprogram** [comment]
Closing since this is not really an issue so much with how we are doing it.
