### ISSUE TITLE
hifive1b: compiles and flashes, but does not run

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#1342]
Seems like there is some problem with the HiFive1B since at least v0.14.1

I can flash code onto the board, but after the board restarts, nothing happens.

This is the case with blinky1 compiled on my local machine (latest dev version), as well as using a HEX file downloaded from the TinyGo Playground.

**Comment by aykevl** [comment]
It does work for me.

```
tinygo flash -target=hifive1b examples/blinky2
```

This gets the red and green portions of the RGB LED to blink.

**Comment by deadprogram** [comment]
Interestingly I cannot reproduce it now myself. Hmmm.

**Comment by deadprogram** [comment]
Closing, will reopen if I get it to occur again.
