### ISSUE TITLE
nrf: I2C Tx() fails on NACK

### ISSUE THREAD

**Issue by dmlambea** [tinygo-org/tinygo#1343]
The i2c.readByte has no checks for error conditions. This makes the function to loop forever if receiving a NACK instead of an ACK.

**Comment by deadprogram** [comment]
Hello @dmlambea thanks for reporting this. Are you able to submit a PR with a fix for this?

**Comment by dmlambea** [comment]
Yes, @deadprogram. Hopefully, today.

**Comment by deadprogram** [comment]
This was released as part of v0.16.0 so now closing. Thank you @dmlambea
