### ISSUE TITLE
Arduino UNO need SPI support for testing driver Lora sx127x

### ISSUE THREAD

**Issue by yevsia** [tinygo-org/tinygo#1351]
There are 2 Arduino UNO boards with Lora SX1278 available, but there is no SPI support at the moment, implementation is necessary if possible, thanks.

**Comment by Nerzal** [comment]
I'd say this issue can now be closed, as SPI support is coming in the next release thanks to #1614

**Comment by deadprogram** [comment]
Tagged for next release, at which point it can be closed.

**Comment by deadprogram** [comment]
This has been released with v0.17.0 so now closing. Thanks!
