### ISSUE TITLE
compiler: Support Go 1.16 file embedding

### ISSUE THREAD

**Issue by bgould** [tinygo-org/tinygo#1352]
Assuming that https://github.com/golang/go/issues/41191 is adopted, presumably support will need to be added to the compiler in order to support this feature.  Among other things, it seems like this could be a reliable means of defining byte arrays stored in flash on microcontrollers (with the current mechanism, it can be unpredictable at times, and difficult to determine why some variables are determined to be constants and some are not).

This issue is just a placeholder/reminder to track the progress of the proposal; eventually once a beta implementation in Go 1.16 is available we can evaluate if any special work is necessary to support the new functionality.

**Comment by aykevl** [comment]
Yes, I really want this. However I'm waiting at least until the proposal is accepted before doing anything.

> eventually once a beta implementation in Go 1.16 is available we can evaluate if any special work is necessary to support the new functionality.

This will certainly require some custom work in TinyGo. Ideally it should work together with dead code elimination so that only files that are absolutely needed are included.

**Comment by ncw** [comment]
go1.16 is out now with fully baked [embed](https://golang.org/pkg/embed/) support.

Now that tinygo 0.17.0 is released with go1.16 support I just noticed that this doesn't work when trying to compile a wasm binary.

It would be a great feature :-)

**Comment by ii64** [comment]
Hi, is this resolved by https://github.com/tinygo-org/tinygo/pull/2873 ?

**Comment by ncw** [comment]
@ii64 yes it looks like that does resolve it :-)

It isn't released yet but assuming it makes it into the master branch it should be in 0.24.0 :crossed_fingers:

**Comment by aykevl** [comment]
Yes, unless there is a big showstopper (that I don't expect) this will definitely be part of the next release :)

> This will certainly require some custom work in TinyGo. Ideally it should work together with dead code elimination so that only files that are absolutely needed are included.

This works in #2873. The linker can even merge files that happen to have the same contents, and `//go:embed` for byte slices that don't have their contents modified. And `//go:embed` globals that aren't used won't be part of the resulting binary.

**Comment by ncw** [comment]
Excellent news - thank you all very much for your hard work :-)
