### ISSUE TITLE
WASM examples don't work anymore.

### ISSUE THREAD

**Issue by nchanged** [tinygo-org/tinygo#1367]
Hi, At first I thought that I am doing something wrong on my local setup, then I tried the official examples and the result is the same.

Basically setting anything but string or number results in `RuntimeError: unreachable`

```
result := make([]interface{}, 0)
	result = append(result, 1)
	js.Global().Set("output", js.ValueOf(result))
```

This works:

```
js.Global().Set("output", js.ValueOf(1))
```

Only the `main` example works in the repository (the one with just `println()`). Everything else fails

```
Google Chrome: Version 85.0.4183.83 (Official Build) (64-bit)
go version go1.13.8 darwin/amd64
tinygo version 0.14.1 darwin/amd64 (using go version go1.13.8 and LLVM version 10.0.1)
```

**Comment by nchanged** [comment]
Upgrading GO version helped, however, `make slices` seems to fail

```
wasm_exec.js:296 syscall/js.finalizeRef not implemented
```

**Comment by deadprogram** [comment]
Is this still an issue now with the latest dev version?

**Comment by deadprogram** [comment]
Closing due to age/inactivity. Please reopen if needed. Thanks!
