### ISSUE TITLE
Tinygo + gopls doesn't work.

### ISSUE THREAD

**Issue by adamijak** [tinygo-org/tinygo#1370]
```
package main
import "machine"
import "time"

func main() {
    led := machine.LED
    led.Configure(machine.PinConfig{Mode: machine.PinOutput})
    for {
        led.Low()
        time.Sleep(time.Millisecond * 300)
        led.High()
        time.Sleep(time.Millisecond * 1000)
    }
}
```
Setting ` GOPATH="/path/to/go:/usr/lib/tinygo/src"`  will allows me to include machine. 
But still I get error `Led not declared in package machine`. That's caused by first line of board_bluepill.go is set to `// +build bluepill`. Its not detected as "machine package".

Any syggestions how to fix this to get gopls working with tinygo.

**Comment by aykevl** [comment]
This is something we're working on, see: https://github.com/tinygo-org/tinygo-site/pull/112

**Comment by adamijak** [comment]
Maybe we have found solution on this thread. Check this out https://github.com/golang/go/issues/41290

**Comment by aykevl** [comment]
Yes, this is what https://github.com/tinygo-org/tinygo-site/pull/112 also does (and more).

Closing this now as the issue has been resolved.
