### ISSUE TITLE
The syscall/js.valueInstanceOf not implemented

### ISSUE THREAD

**Issue by elct9620** [tinygo-org/tinygo#1423]
Hi, all

I try to call the `value.InstanceOf(js.Global().Get("String"))` but it seems comment out in the `wasm_exec.js`, does any reason didn't implement it?

It seems can work correctly if I change the disabled code to below:

```js
// func valueInstanceOf(v ref, t ref) bool
"syscall/js.valueInstanceOf": (sp) => {
  return loadValue(sp) instanceof loadValue(sp + 8);
},
```

**Comment by deadprogram** [comment]
Hello @elct9620 that sounds like it would be a nice pull request, unless someone else knows why it was commented out?

**Comment by elct9620** [comment]
I think I can create a pull request first and wait for the comment if anyone knows about that.

**Comment by deadprogram** [comment]
That would be very appreciated, thanks!

**Comment by elct9620** [comment]
The pull request is here #1432, I will close this issue and let us move to PR to continue discuss.
