### ISSUE TITLE
Slack Invitation

### ISSUE THREAD

**Issue by ewwaller** [tinygo-org/tinygo#1433]
The link for a Slack invitation in the Readme is dead.   
I would like to obtain an invite -- this is a cool project.

**Comment by deadprogram** [comment]
The links I just tried worked. You do have to request an invitation however from https://invite.slack.golangbridge.org/ before you can access it.

**Comment by ewwaller** [comment]
That link leads to a page that says:

Slack
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by deadprogram** [comment]
There is a problem according to the Slack admins. More on this soon, hopefully.

**Comment by ewwaller** [comment]
This seems to have been resolved.

**Comment by deadprogram** [comment]
OK good. Now closing, thanks for updating us.
