### ISSUE TITLE
tinygo flash -scheduler coroutines -target arduino leads to an error

### ISSUE THREAD

**Issue by c7haki** [tinygo-org/tinygo#1436]
Hi,

I'm trying to use a goroutine on arduino uno.
The following command leads to an error:
**$ tinygo flash -scheduler coroutines -target arduino AirQIndicator/tinytest.go** 
tinygo: /home/circleci/project/llvm-project/llvm/lib/IR/Constants.cpp:1056: llvm::ConstantAggregate::ConstantAggregate(llvm::CompositeType *, llvm::Value::ValueTy, ArrayRef<llvm::Constant *>): Assertion `V[I]->getType() == T->getTypeAtIndex(I) && "Initializer for composite element doesn't match!"' failed.
SIGABRT: abort
PC=0x7fb6c35ab18b m=11 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fb6c35ab18b
stack: frame={sp:0x7fb6777fd690, fp:0x0} stack=[0x7fb676ffe248,0x7fb6777fde48)
00007fb6777fd590:  0000000000000420  00000000068e3d84 
00007fb6777fd5a0:  00000000068e4546  00007fb66870e0d8 
00007fb6777fd5b0:  00007fb66870d870  0000000004aab7fc 
00007fb6777fd5c0:  0000000008b69d60  0000000000000000 
00007fb6777fd5d0:  0000020000000000  0000ffff00001fa2 
00007fb6777fd5e0:  0000000000000000  00007fb68c004578 
00007fb6777fd5f0:  00007fb668007310  0000000000001000 
00007fb6777fd600:  0000000000000039  0000000000000001 
00007fb6777fd610:  00007fb6777fd630  00007fb6777fd630 
00007fb6777fd620:  00007fb66870e290  00007fb66870e2f4 
00007fb6777fd630:  0000000008b8c5d8  00007fb66870e2f4 
00007fb6777fd640:  36353031777fd6a0  b85f4f773328f400 
00007fb6777fd650:  00007fb66870e290  00007fb6777fd8f0 
00007fb6777fd660:  0000000000000133  0000000000000133 
00007fb6777fd670:  0000000000000134  00007fb66871b930 
00007fb6777fd680:  00007fb6777fd6a0  00007fb6c35f3de6 
00007fb6777fd690: <0000000000000000  00007fb6c3602850 
00007fb6777fd6a0:  0787d43cfbad8000  00007fb66871b930 
00007fb6777fd6b0:  00007fb66871ba5d  00007fb66871b930 
00007fb6777fd6c0:  00007fb66871b930  00007fb66871ba63 
00007fb6777fd6d0:  00007fb66871bbec  00007fb66871b930 
00007fb6777fd6e0:  00007fb66871bbec  0000000000000000 
00007fb6777fd6f0:  0000000000000000  0000000000000000 
00007fb6777fd700:  0000000000000000  0000000000000000 
00007fb6777fd710:  fffffffe7fffffff  ffffffffffffffff 
00007fb6777fd720:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd730:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd740:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd750:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd760:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd770:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd780:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fb6c35ab18b
stack: frame={sp:0x7fb6777fd690, fp:0x0} stack=[0x7fb676ffe248,0x7fb6777fde48)
00007fb6777fd590:  0000000000000420  00000000068e3d84 
00007fb6777fd5a0:  00000000068e4546  00007fb66870e0d8 
00007fb6777fd5b0:  00007fb66870d870  0000000004aab7fc 
00007fb6777fd5c0:  0000000008b69d60  0000000000000000 
00007fb6777fd5d0:  0000020000000000  0000ffff00001fa2 
00007fb6777fd5e0:  0000000000000000  00007fb68c004578 
00007fb6777fd5f0:  00007fb668007310  0000000000001000 
00007fb6777fd600:  0000000000000039  0000000000000001 
00007fb6777fd610:  00007fb6777fd630  00007fb6777fd630 
00007fb6777fd620:  00007fb66870e290  00007fb66870e2f4 
00007fb6777fd630:  0000000008b8c5d8  00007fb66870e2f4 
00007fb6777fd640:  36353031777fd6a0  b85f4f773328f400 
00007fb6777fd650:  00007fb66870e290  00007fb6777fd8f0 
00007fb6777fd660:  0000000000000133  0000000000000133 
00007fb6777fd670:  0000000000000134  00007fb66871b930 
00007fb6777fd680:  00007fb6777fd6a0  00007fb6c35f3de6 
00007fb6777fd690: <0000000000000000  00007fb6c3602850 
00007fb6777fd6a0:  0787d43cfbad8000  00007fb66871b930 
00007fb6777fd6b0:  00007fb66871ba5d  00007fb66871b930 
00007fb6777fd6c0:  00007fb66871b930  00007fb66871ba63 
00007fb6777fd6d0:  00007fb66871bbec  00007fb66871b930 
00007fb6777fd6e0:  00007fb66871bbec  0000000000000000 
00007fb6777fd6f0:  0000000000000000  0000000000000000 
00007fb6777fd700:  0000000000000000  0000000000000000 
00007fb6777fd710:  fffffffe7fffffff  ffffffffffffffff 
00007fb6777fd720:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd730:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd740:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd750:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd760:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd770:  ffffffffffffffff  ffffffffffffffff 
00007fb6777fd780:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0xd3b700, 0xc001ac90d0, 0xc001ac90d8)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc001ac90a0 sp=0xc001ac9068 pc=0x9812eb
tinygo.org/x/go-llvm._Cfunc_LLVMRunFunctionPassManager(0x7fb668286cc0, 0x7fb68c004768, 0x0)
	_cgo_gotypes.go:8820 +0x4d fp=0xc001ac90d0 sp=0xc001ac90a0 pc=0xc1b60d
tinygo.org/x/go-llvm.PassManager.RunFunc.func1(0x7fb668286cc0, 0x7fb68c004768, 0x7fb68c004768)
	/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20200503225853-345b2947b59d/ir.go:2004 +0x79 fp=0xc001ac9100 sp=0xc001ac90d0 pc=0xc44939
tinygo.org/x/go-llvm.PassManager.RunFunc(0x7fb668286cc0, 0x7fb68c004768, 0x0)
	/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20200503225853-345b2947b59d/ir.go:2004 +0x35 fp=0xc001ac9128 sp=0xc001ac9100 pc=0xc2b355
github.com/tinygo-org/tinygo/transform.Optimize(0x8b8c4c0, 0xc0002568d0, 0x2, 0x2, 0x5, 0x0, 0x0, 0x0)
	/home/circleci/project/transform/optimizer.go:59 +0x29d fp=0xc001ac9480 sp=0xc001ac9128 pc=0xcf476d
github.com/tinygo-org/tinygo/builder.Build(0x7ffd805ec076, 0x19, 0x53339a7, 0x4, 0xc0002568d0, 0xc001ac9b88, 0x0, 0x0)
	/home/circleci/project/builder/build.go:109 +0x337a fp=0xc001ac9b20 sp=0xc001ac9480 pc=0xd07aaa
main.Flash(0x7ffd805ec076, 0x19, 0x0, 0x0, 0xc00025c000, 0x0, 0x15)
	/home/circleci/project/main.go:188 +0x198 fp=0xc001ac9bd0 sp=0xc001ac9b20 pc=0xd17a18
main.main()
	/home/circleci/project/main.go:894 +0xf2f fp=0xc001ac9f88 sp=0xc001ac9bd0 pc=0xd1b0cf
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x1fa fp=0xc001ac9fe0 sp=0xc001ac9f88 pc=0x9b39aa
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc001ac9fe8 sp=0xc001ac9fe0 pc=0x9e09a1

rax    0x0
rbx    0x7fb6777fe700
rcx    0x7fb6c35ab18b
rdx    0x0
rdi    0x2
rsi    0x7fb6777fd690
rbp    0x7fb6c3720588
rsp    0x7fb6777fd690
r8     0x0
r9     0x7fb6777fd690
r10    0x8
r11    0x246
r12    0x68e3d84
r13    0x420
r14    0x68e4546
r15    0x7fb6687145f0
rip    0x7fb6c35ab18b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

**$ tinygo version**
tinygo version 0.15.0 linux/amd64 (using go version go1.15.2 and LLVM version 10.0.1)

**Comment by aykevl** [comment]
This is a bug in the AVR backend of LLVM, not in TinyGo. If you want to use a scheduler, please use `-scheduler=tasks` instead. However, note that it might not even work on an Arduino Uno as it has a very limited amount of RAM.

**Comment by c7haki** [comment]
got it, thanks for clarification
