### ISSUE TITLE
Error when building multiple files: undeclared name

### ISSUE THREAD

**Issue by ttttmr** [tinygo-org/tinygo#1450]
This is a simplified version of my code, there are two files

```go
//main.go
package main
...
func main() {
  somefunc()
}
```

```go
//utils.go
package main
...
func somefunc(){
  //do something
}
```

I use docker to compile

```
docker run --rm -v `pwd`:/src -e "GOPATH=/go" tinygo/tinygo:0.15.0 /bin/bash -c "cd /src && tinygo build -o main.wasm -target wasm main.go"
```

error:
```
# command-line-arguments
main.go:x:x: undeclared name: somefunc
```

main.go cannot find the function in utils.go

**Comment by jrauschenbusch** [comment]
@ttttmr How did you solved the issue? I'm facing the same one.

UPDATE: Ok, one just has to make all files available to the compiler.

`tinygo build -o main.wasm -target wasm ./ # use folder instead of single main.go `

**Comment by maddin200** [comment]
tinygo build ./ 

is definitely different from:

tinygo build ./utils.go ./main.go // not possible
 especially in comparison to the standard go compiler
go build ./utils.go ./main.go

**Comment by flyn-org** [comment]
Would it be possible to support multiple input files? It would be nice to be able to use tinygo as a drop-in replacement to Google's Go compiler in this regard.
