### ISSUE TITLE
Are there any alternatives to net/http for get requests?

### ISSUE THREAD

**Issue by Nv7-GitHub** [tinygo-org/tinygo#1509]
I need to be able to send get requests using tinygo. Currently, the `net/http` package is not supported. Are there any alternatives to this package to sending GET requests?

**Comment by aykevl** [comment]
None are supported right now but I have just come across this on Twitter that might be useful: https://twitter.com/pojntfx/status/1333563900575539200 (I did not check or test this).

**Comment by dosgo** [comment]
I also look for http clients from non-standard libraries. I haven't found it yet, but you can use net.Dial to connect to simulate http is to handle the http protocol yourself.

**Comment by sago35** [comment]
In baremetal, you can use tinygo.org/x/drivers/net.
An example is given below.

https://github.com/tinygo-org/drivers/tree/dev/wifinina   <--  update
https://github.com/tinygo-org/drivers/blob/3fe3fc64e4dedb899cd03542ef20d828a264045b/examples/wifinina/http-get/main.go#L77-L105

**Comment by dosgo** [comment]
@sago35 Thanks! tinygo.org/x/drivers/net/http: module tinygo.org/x/drivers@latest found (v0.17.1), but does not contain package tinygo.org/x/drivers/net/http  This is because v0.17.1 does not?

**Comment by sago35** [comment]
@dosgo 
Try the latest on the dev branch.

https://github.com/tinygo-org/drivers/tree/dev

**Comment by dosgo** [comment]
@sago35 Thank you very much! It is perfectly compatible with net/http, the size has dropped by 2M, and it also supports the official compiler.

**Comment by deadprogram** [comment]
Closing since question seems to have been answered. Thank you!
