### ISSUE TITLE
Compiled WebAssembly generating wrong function signature for imported functions.

### ISSUE THREAD

**Issue by adlrocha** [tinygo-org/tinygo#1513]
If I compile the following code snippet to Wasm using `tinygo`: ` tinygo build -o wasm.wasm -target wasm ./add/add.go`, the function signature generated for the imported function is wrong.
```go
package main

func main() {
}

// imported function
func multiply(x int32, y int32) int32

//export add
func add(x, y int32) int32 {
	a := multiply(x, y)
	return x + y + a
}
```
If you use a wasm2wat tool similar to [this one](https://webassembly.github.io/wabt/demo/wasm2wat/) you can see the instead of two `int32` the function signature expects four `int32`:
```
(type $t1 (func (param i32 i32 i32 i32) (result i32)))
(import "env" "command-line-arguments.multiply" (func $command-line-arguments.multiply (type $t1)))
```
So if you want to use this Wasm module from a WASI environment such as Wasmtime-go, you need to check the right signature for it to work:
```go
item := wasmtime.WrapFunc(store, func(x, y, z, k int32) int32 {
		return x * y
	})
instance, err := wasmtime.NewInstance(store, module, []*wasmtime.Extern{item.AsExtern()})
```
Any idea why this could be happening? It is a bug at compilation, or it may be some kind of optimization that we may be disregarding?
Thanks!

**Comment by aykevl** [comment]
You are using the TinyGo internal ABI. You should import functions like this:

```go
package main

func main() {
}

// imported function
//export multiply
func multiply(x int32, y int32) int32

//export add
func add(x, y int32) int32 {
	a := multiply(x, y)
	return x + y + a
}
```

(I know it says "export" but think of it as making the function name and signature available outside of Go).

Those two extra parameters are internal to TinyGo, one is for function closures and the other is for our way of lowering goroutines on WebAssembly. In other words, compiler implementation details. You can read more about the calling convention here: https://tinygo.org/compiler-internals/calling-convention/
