### ISSUE TITLE
STM32L432 Support

### ISSUE THREAD

**Issue by nick-phillips-dev** [tinygo-org/tinygo#1523]
Is it possible to program the STM32L432 MCU using tinygo?

**Comment by aykevl** [comment]
It looks like nobody has added support for it yet, but most likely support can be added for this chip. So not right now but maybe in the future.

**Comment by nick-phillips-dev** [comment]
That sounds good. Can anyone estimate the amount of work to add support?

**Comment by nick-phillips-dev** [comment]
We would like to sponsor this work if anyone is available. Is there anyway to do that?

**Comment by deadprogram** [comment]
@hyprnick please feel free to email or message me to see how we can help.

**Comment by deadprogram** [comment]
Hello @hyprnick the STM32L432 is just about to land in the TinyGo `dev` branch:

https://github.com/tinygo-org/tinygo/pull/1710

**Comment by nick-phillips-dev** [comment]
Thanks for the update @deadprogram ! That's great to hear. I will check it out.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
