### ISSUE TITLE
ADC: Accept configuration struct as argument to method Configure

### ISSUE THREAD

**Issue by ardnew** [tinygo-org/tinygo#1533]
I think it makes sense to change the API of `ADC.Configure` (for all chips) to the API you're using here. The reason is that an ADC actually has a number of important configurations for different tradeoffs:

 - Reference voltage (often VCC, but sometimes 1.1V or some other value).
 - Accuracy vs time. I know that the nrf chips have this tradeoff (where more accurate sampling takes a lot longer but is necessary if there is a big resistor on the input) and I would guess other ADCs have something similar.

Of course, it's not necessary to implement them all right away but with this I think it makes sense to add an `ADCConfig` to the peripheral.

_Originally posted by @aykevl in https://github.com/tinygo-org/tinygo/pull/1458#discussion_r522904082_

**Comment by deadprogram** [comment]
This has been released with v0.17.0 so now closing. Thanks!
