### ISSUE TITLE
wasm memory bug/question

### ISSUE THREAD

**Issue by yuval-k** [tinygo-org/tinygo#1535]
Hello everyone! 
Than you for making tinygo wasm compatible. I've been testing it out, trying to use with envoy proxy, and I have some questions I would love your help with. I tried answering these myself by looking at the code, but I want to make sure I'm not missing anything:

I noticed that using different arguments to `--heap-size` still produces the exact same binary, with initial wasm memory set to 3 wasm-pages (i.e.: `(memory $0 3)`) I do see this argument passed in the ld flags, so I suspect that this is a bug? 

IIUC the code correctly, the initial memory is all that is available - i.e. the `memory.grow` instruction is not used to grow memory dynamically. This means that all the memory usage expected should be included in the heap-size. is that accurate?

Thank you for your reply!

**Comment by asayah** [comment]
@deadprogram any update on this one?

**Comment by djannot** [comment]
+1

**Comment by aykevl** [comment]
Hi! Thank you for your interest in using WebAssembly. I have made a PR that implements automatically growing the heap when needed: #1567. This removes the `-heap-size` parameter entirely as it is not necessary anymore, which I believe is the proper fix (`-heap-size` was always just a workaround as the TinyGo heap previously was unable to grow in size).

**Comment by djannot** [comment]
@aykevl do you know when this fix will be released ?

**Comment by deadprogram** [comment]
This has been released with v0.17.0 so now closing. Thanks!
