### ISSUE TITLE
Blue Pill STM32F103C8 and ws2812

### ISSUE THREAD

**Issue by olablt** [tinygo-org/tinygo#1546]
Hello,

I am new to TinyGo.
I have Blue Pill board and have OLED screen and other scripts running: https://github.com/olablt/tiny32

Now I would like to drive the ws2812 LED strip.
How to change the ws2812 driver to support BluePill?

**Comment by deadprogram** [comment]
@olablt the ws2812 drivers should currently support the ARM cortex on that board. If not please open an issue in the https://github.com/tinygo-org/drivers repo. Thank you! Now closing.
