### ISSUE TITLE
K210 RISC-V Support？

### ISSUE THREAD

**Issue by KISSMonX** [tinygo-org/tinygo#1554]

**Comment by aykevl** [comment]
Can you elaborate a bit more?

We support the Kendryte K210 chip in the Sipeed MAix BiT, if that's what you mean: https://www.seeedstudio.com/Sipeed-MAix-BiT-for-RISC-V-AI-IoT-p-2872.html

**Comment by KISSMonX** [comment]
> Can you elaborate a bit more?
> 
> We support the Kendryte K210 chip in the Sipeed MAix BiT, if that's what you mean: https://www.seeedstudio.com/Sipeed-MAix-BiT-for-RISC-V-AI-IoT-p-2872.html

oh, yes, K210. Good!
