### ISSUE TITLE
Support for Microchip range of microcontrollers

### ISSUE THREAD

**Issue by deepakkamesh** [tinygo-org/tinygo#1601]
Would you consider adding support for microchip range of microcontrollers?

**Comment by aykevl** [comment]
Can you provide a bit more information? What chip do you mean, and how is it used? Microchip provides many different microcontroller families, two of which (AVR and SAM) already have some support in TinyGo.

**Comment by deepakkamesh** [comment]
Hi, I was thinking of something like pic18f4550. These are 8bit chips so I dont know if thats even possible.

**Comment by aykevl** [comment]
Unfortunately LLVM does not have a backend for the PIC18 family of microcontrollers. In general, 8 bit support on LLVM is somewhat weak, with AVR having the best support (and even AVR support is limited). So for now PIC18 support cannot practically be added to TinyGo.
