### ISSUE TITLE
Standalone C files don't get header search path from #cgo ?

### ISSUE THREAD

**Issue by oflebbe** [tinygo-org/tinygo#1624]
Hi,

thanks for hinting for using proper prototypes.

However, only slightly more involved commands still won't compile

See https://github.com/oflebbe/testesp32 

Maybe the CFLAGS flag isn't honored for stand-alone C files ?

**Comment by aykevl** [comment]
> Maybe the CFLAGS flag isn't honored for stand-alone C files ?

Yes, that's true. Fixing this shouldn't be too hard, but it conflicts with https://github.com/tinygo-org/tinygo/pull/1612 so I'd like to get that PR ready first. In the meantime, you could work around it like this:

```diff
--- a/demo.c
+++ b/demo.c
@@ -1,4 +1,4 @@
-#include <foo.h>
+#include "include/foo.h"
 
 int fortytwo()
 {
```

Basically, do an include relative to the current directory.

**Comment by aykevl** [comment]
Based on the repository name, you might be interested in this PR: https://github.com/tinygo-org/tinygo/pull/1626

**Comment by aykevl** [comment]
#1626 does not fix this issue, so I've removed the next-release label.

**Comment by oflebbe** [comment]
Indeed !  #1626 looks very interesting.
Wanted to poke into compiling and linking with ESP-IDF Headers and binaries .

**Comment by aykevl** [comment]
Here is a fix: https://github.com/tinygo-org/tinygo/pull/1708

**Comment by deadprogram** [comment]
Looks like this was addressed some time ago, so now closing. Please reopen if needed. Thank you!
