### ISSUE TITLE
TinyGO support Build hex bin run soc
, How to TinyGO support run  freertos?

### ISSUE THREAD

**Issue by wcpsoft** [tinygo-org/tinygo#1629]
I know TinyGO support Build hex bin run soc,but How to TinyGO support run freertos or other?

**Comment by aykevl** [comment]
TinyGo has its own scheduler. While it could in theory use FreeRTOS, that introduces a lot of complexity and makes building TinyGo programs a lot more difficult. Therefore, I do not see a reason for integration at the moment.

**Comment by wcpsoft** [comment]
Thank you,I know
