### ISSUE TITLE
samd : If you disconnect USBCDC after communication is established, it will cause an infinite loop.

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#1637]
I thought `usbLineInfo.lineState` would return to 0 after disconnecting communication, but it did not.
Even when it returns to 0, USBCDC.WriteByte() will go into an infinite loop depending on the timing of the disconnect.

* #1636
* #1481

We will discuss how to fix it.
A simple solution would be to stop sending if it takes more than Xmsec to send a single message.

**Comment by sago35** [comment]
If the connection is never established, or never disconnected, there is no problem.

**Comment by deadprogram** [comment]
This has been released with v0.17.0 so now closing. Thanks!
