### ISSUE TITLE
build: add darwin/arm64 binary build for release to CI

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#1638]
Once we have added Go 1.16 to the CircleCI build, we need to add build step(s) to produce a darwin/arm64 binary artifact for release distribution.

**Comment by aykevl** [comment]
Certainly. However, I think it is most practical to wait until CircleCI has added ARM64 executors, see: https://support.circleci.com/hc/en-us/articles/360047734172-Can-I-build-Apple-Silicon-Universal-apps-

Cross compiling large C++ projects is always a hassle. Cross compiling a compiler even more so. I could spend time to try to figure out how to cross compile TinyGo, but I think that time would be better spent on something else (especially as it is a temporary workaround until CircleCI adds Apple Silicon support).

**Comment by joeshaw** [comment]
CI is on GitHub Actions now, but still no `darwin/arm64` availability.  That's being tracked in https://github.com/github/roadmap/issues/528 but looks like it's not coming for a while.

**Comment by HacDan** [comment]
Looks like this shipped! [🚢](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/)

### Edit: 

_For a price_... Figures. My bad, thanks for clarifying that @deadprogram

**Comment by deadprogram** [comment]
Only for paying plans, not for free open source. :money_with_wings:

**Comment by deadprogram** [comment]
We have had this for a while now, so closing. :smile: 

Thanks everyone!
