### ISSUE TITLE
Support for wasi_snapshot_preview1

### ISSUE THREAD

**Issue by fgsch** [tinygo-org/tinygo#1647]
While it's possible to change the module via `go:wasm-module` and use `wasi_snapshot_preview1`, I've encountered an issue (I will open a separate ticket) that makes this not ideal for my use case.

I was wondering if TinyGo could switch WASI to use `wasi_snapshot_preview1`, the latest version, instead of `wasi_unstable` by default?

**Comment by aykevl** [comment]
Please take a look here: https://github.com/tinygo-org/tinygo/pull/1690

**Comment by fgsch** [comment]
Oh, I didn't see this and I worked on the change myself. Sorry!
There are a few more things my PR covers so I will open it and you can decide.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
