### ISSUE TITLE
Teensy 4.0 UART stopped functioning after interp package rewrite

### ISSUE THREAD

**Issue by ardnew** [tinygo-org/tinygo#1649]
Ran into the problem of no data coming out UART1 with the "serial" test program. I realize it is a little late now, seems like I did not test this before properly?

_Originally posted by @deadprogram in https://github.com/tinygo-org/tinygo/issues/1454#issuecomment-778838171_

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
