### ISSUE TITLE
Why this project stopped?

### ISSUE THREAD

**Issue by vidalouiswang** [tinygo-org/tinygo#1664]

**Comment by Nerzal** [comment]
Could you please elaborate what exactly you intend to ask?

**Comment by deadprogram** [comment]
@vidalouiswang perhaps you are looking for the active `dev` branch:

https://github.com/tinygo-org/tinygo/tree/dev

**Comment by vidalouiswang** [comment]
> Could you please elaborate what exactly you intend to ask?



> Could you please elaborate what exactly you intend to ask?

Hi,
I just noticed this project haven't any commit for long time, so want to know some information.

**Comment by vidalouiswang** [comment]
> @vidalouiswang perhaps you are looking for the active `dev` branch:
> 
> https://github.com/tinygo-org/tinygo/tree/dev

Thank you, I am a beginner.
