### ISSUE TITLE
nano33: program "deadlocks" when using Nina chip + another SPI device

### ISSUE THREAD

**Issue by Nerzal** [tinygo-org/tinygo#1665]
I'm using a st7735 in a project, that displays sensor data and additionally that program posts the sensor data to a mqtt broker. Atleast that was the plan. But it is not a big deal, i don't really need the display as i have a WASM app, that displays the data :) 

After connecting to the MQTT broker, the program halts, when trying to draw onto the st7735. 
Is this intended behavior, as it is not possible to maintain 2 different SPI connections, or did i find a bug in here?

tinygo version:
> tinygo version 0.17.0-dev linux/amd64 (using go version go1.16 and LLVM version 11.1.0)

Update: 
Nina SPI uses default Pins: 

SDO: 12
SDI: 13
SCK: 15

CS: 14
ACK: 28
GPI0: 27

ST7735 uses: 
SCK: 17
SDO: 16
SDI: 19
Reset: 4
DC: 5
CS: 6
Backlight: 42

BME280:
SDA: 40
SCL 41

So i don't have any overlapping pins in here

**Comment by deadprogram** [comment]
Is this still a problem with the latest TinyGo @Nerzal?

**Comment by Nerzal** [comment]
I can try (:

**Comment by deadprogram** [comment]
I have several scenarios where I do exactly this same setup without problems, so now closing. Please reopen if needed. Thanks!
