### ISSUE TITLE
Testing non-browser specific WASM / WASI changes

### ISSUE THREAD

**Issue by fgsch** [tinygo-org/tinygo#1675]
Related to https://github.com/tinygo-org/tinygo/pull/1661, and more in general, do you have any thoughts around testing without the browser? Is https://github.com/wasmerio/wasmer-go an option?  I'd be happy to take a look. Thanks!

**Comment by fgsch** [comment]
Another option I was not aware of, https://github.com/bytecodealliance/wasmtime-go.

**Comment by hunjixin** [comment]
can wasm work on non browser environment such as vm in blockchain? @fgsch

**Comment by aykevl** [comment]
Yes, we have WASI support.

**Comment by aykevl** [comment]
Actually we're now also testing WASI (using wasmtime) so this issue can be closed.
