### ISSUE TITLE
how to import global variable, not function.

### ISSUE THREAD

**Issue by shelmesky** [tinygo-org/tinygo#1702]
just like this:

```go
// import this from javascript or webassembly VM
var myvar int

// This function is exported to JavaScript, so can be called using
// exports.multiply() in JavaScript.
//export multiply
func multiply(x, y int) int {
	return x * y + myvar
}
```

**Comment by aykevl** [comment]
WebAssembly does not natively allow this so you can't do this unfortunately. I think it would be possible to build a JavaScript shim that supports this using something like wasm-bindgen but this has not yet been implemented for TinyGo.

Alternatively, you could add this:

```go
//export getMyvar
func getMyvar() int {
    return myvar
}
```
