### ISSUE TITLE
Add arm64 release for Linux/.deb

### ISSUE THREAD

**Issue by LaPingvino** [tinygo-org/tinygo#1703]
I use a Chromebook with Linux in its VM and it uses the ARM64 architecture. It would be very nice to be able to download a precompiled tinygo release for this.

**Comment by aykevl** [comment]
Yes, that would be great but unfortunately CircleCI (where TinyGo is tested and release builds are built) does not have the necessary support. For more information: https://ideas.circleci.com/images/p/support-for-arm-based-docker-images

Hopefully we can support this in the near future, for now it is unfortunately not easily possible.

**Comment by LaPingvino** [comment]
A recent update to that thread about 5 days ago suggests a usable preview should be available, and less than 24 hours ago seemingly that post has been further picked up.

**Comment by aykevl** [comment]
Yes, that's for a raw system (no containers). I would very much prefer working in a container as is common in CircleCI, hopefully such support gets added in the near future (within a few months). That would mean less work towards CI and more towards other interesting things :)

**Comment by LaPingvino** [comment]
Probably good then to keep this up as a tracking issue and to show the need.

**Comment by briancampo** [comment]
I am also very interested in this for the same reasons.  
Any updates or progress?

**Comment by loeffel-io** [comment]
Oh no, want to use tinygo on my arm so bad

**Comment by niaow** [comment]
Closing as arm64 packages are included in releases v0.24.0 and up.
