### ISSUE TITLE
Support for crypto/rsa library

### ISSUE THREAD

**Issue by HasmitaA** [tinygo-org/tinygo#1723]
Is there any alternative to crypto/rsa package for jwt verification functionalities

**Comment by codefromthecrypt** [comment]
while this issue was much later than yours, it has more details. Do you mind closing this out and subscribing to it @HasmitaA? https://github.com/tinygo-org/tinygo/issues/3131

**Comment by dgryski** [comment]
Dup of https://github.com/tinygo-org/tinygo/issues/3131
