### ISSUE TITLE
Arduino Mega 2560's SPI MISO/MOSI Flipped

### ISSUE THREAD

**Issue by soypat** [tinygo-org/tinygo#1737]
[The lines in question](https://github.com/tinygo-org/tinygo/blob/release/src/machine/machine_atmega2560.go#L136).
`sdi` and `sdo` seem to be flipped.

It would seem that the correct way of arranging `SPI0` according to [arduino's documentation](https://www.arduino.cc/en/reference/SPI) would be the following

```go
// SPI configuration
var SPI0 = SPI{
	spcr: avr.SPCR,
	spdr: avr.SPDR,
	spsr: avr.SPSR,
	sck:  PB1,
	sdi:  PB2,
	sdo:  PB3,
	cs:   PB0}
```

I've tested both ways, the second one seems to actually work.

**Comment by soypat** [comment]
If someone can get around to testing the Arduino Mega that'd be great. I couldn't get the SPI to work for the life of me.

**Comment by soypat** [comment]
I have gotten around to testing the Arduino Mega's SPI with the MCP3008 library. 

The following setup worked for me:
* Use TinyGo library without modification (works fine right now)
* Connecting Pin 51 to MCP3008 `Din` (MOSI)
* Connecting Pin 50 to MCP3008 `Dout` (MISO)
* Connecting Pin 53 to MCP3008 `CS` (Chip select)
* Connecting Pin 52 to MCP3008 `CLK` (Serial clock)
`machine.D51` is equal to `machine.PB2` (equal to `10`), which appears as `sdo` in `SPI0` configuration, which confused me (I thought SDO was Slave Device Output). I'd like to point out these names are easy to mistake, as manufacturers commonly use SDO/SDI for their pins.

**Comment by deadprogram** [comment]
We try to follow the guidelines of the Open Source Hardware Association regarding naming of pins in the SPI interface. 

Please see:
https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names/

Thank you!
