### ISSUE TITLE
Windows: tinygo test should show a useful error message

### ISSUE THREAD

**Issue by Nerzal** [tinygo-org/tinygo#1748]
When running tinygo test <packagename> on Windows without specifying a target, it will print a very long error telling the user, that lots of stuff could not be found. 

Instead, we can add a nice error message, that tells the user, that they can try to use targets like `--target=wasi` or `--target=wasm` etc.

I'll should be able to submit a PR with a first throw of that error message :)

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
