### ISSUE TITLE
Arduino Uno PWM frequency too high

### ISSUE THREAD

**Issue by soypat** [tinygo-org/tinygo#1760]
As of TinyGo 0.17, Arduino Uno's PWM on pin 10 runs at 3922 Hz.This makes it unsuitable to control actuators such as Servos which usually rely on a pulse width of around 3-0.5ms.

Arduino's official documentation puts PWM frequency at 490 Hz and 980Hz, depending on the pin used.

My measurements on an oscilloscope put frequencies at:

* D10: 3922Hz
* D6: 490Hz (should be 980 according to Arduino) (pins 5 and 6: 980 Hz)
* D5: 490Hz (should be 980)
* D3: 490Hz
* D9: 3922Hz
* D11: 490Hz

**Comment by aykevl** [comment]
This will be solved in the future with #1121, which will let you control PWM frequency.

There is not one frequency that's best in all cases, it depends on what you use the PWM for. Therefore, #1121 will make it possible to configure each PWM peripheral individually.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
