### ISSUE TITLE
Unable to use bufio.Scanner on linux/amd64 and darwin/amd64

### ISSUE THREAD

**Issue by veeableful** [tinygo-org/tinygo#1761]
Hi, I was not able to run a program that uses `bufio.Scanner` successfully. It returns the following errors:

linux/amd64
```
multiple Read calls return no data or error
```
darwin/amd64 (running on M1)
```
read /dev/stdin: errno 78
```

The code is the following:
```go
// foo.go
package main

import (
	"bufio"
	"fmt"
	"os"
)

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		scanner.Text()
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
```

Then I build and run the program with:
```bash
tinygo build -o foo foo.go
echo | ./foo
```

The TinyGo versions are:

linux/amd64
```
tinygo version 0.17.0 linux/amd64 (using go version go1.16.2 and LLVM version 11.0.0)
```

darwin/amd64
```
tinygo version 0.17.0 darwin/amd64 (using go version go1.16.2 and LLVM version 11.0.0)
```

Does anyone know why? I tried looking for similar issue but there doesn't seem to be an existing one so hopefully this is not a duplicate. Thanks in advance!

**Comment by deadprogram** [comment]
This has been possible for a while thanks to TinyGo bringing in libc when compiling for those targets.

Now closing.
