### ISSUE TITLE
nodemcu (Amica with ESP8266MOD) examples/blinky1 not working

### ISSUE THREAD

**Issue by soypat** [tinygo-org/tinygo#1762]
Tried following the instructions to flash blinky1 at [https://tinygo.org/microcontrollers/esp8266-nodemcu/](https://tinygo.org/microcontrollers/esp8266-nodemcu/). 

Light was initially blinking before flashing tinygo program (I believe they come with a factory loaded blinky). After flashing the light stayed off

## Output
```
$ tinygo flash -port=/dev/ttyUSB0 -target=nodemcu -size=short examples/blinky1
   code    data     bss |   flash     ram
   2863       0      64 |    2863      64
esptool.py v3.0
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 60:01:94:51:bb:5e
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 3072 bytes to 2426...
Wrote 3072 bytes (2426 compressed) at 0x00000000 in 0.2 seconds (effective 113.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

## Installation information
<details><summary>Go install</summary>

```go
$ go version
go version go1.16.2 linux/amd64
```
```go
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/pato/go/bin"
GOCACHE="/home/pato/.cache/go-build"
GOENV="/home/pato/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pato/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pato/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4271522988=/tmp/go-build -gno-record-gcc-switches"

```

</details>

<details><summary> TinyGo </summary>

```shell-script
$ tinygo version
tinygo version 0.17.0 linux/amd64 (using go version go1.16.2 and LLVM version 11.0.0)
```

</details>

**Comment by sago35** [comment]
If you have a schematic, please let me know the URL.

Is the result the same if I try using other pins?
You can set the other pins to output settings as follows


https://github.com/tinygo-org/tinygo/blob/release/src/examples/blinky1/blinky1.go#L11

```
	led := machine.D0
```

A list of pins can be found below
https://github.com/tinygo-org/tinygo/blob/release/src/machine/board_nodemcu.go#L9-L17

**Comment by soypat** [comment]
I'll check as soon as I get my hands back on a nodemcu. This is the board https://www.luisllamas.es/esp8266-nodemcu/

**Comment by wuhanstudio** [comment]
I have the same issue, but it has been fixed by changing:

https://github.com/tinygo-org/tinygo/blob/138befd8a25d2a5c65e2e740038a8c3a44e95222/targets/esp8266.json#L19

For windows:
 
```
"flash-command": "esptool --chip=esp8266 --port {port} write_flash 0x00000 {bin} -fm dio"
```

For Linux:

```
"flash-command": "esptool.py --chip=esp8266 --port {port} write_flash 0x00000 {bin} -fm dio"
```

Maybe it's better to add an argument for flashing mode.

**Comment by soypat** [comment]
@sago35 Apparently my board is not flashing correctly. Trying out other pins and measuring voltage it seems the blinky program does nothing, including for other pins.

I'd try out wuhanstudio's solution but I'm unsure how to go about doing that modification... do I have to compile from source after modifying?

**Comment by wuhanstudio** [comment]
> @sago35 Apparently my board is not flashing correctly. Trying out other pins and measuring voltage it seems the blinky program does nothing, including for other pins.
> 
> I'd try out wuhanstudio's solution but I'm unsure how to go about doing that modification... do I have to compile from source after modifying?

It's not required to compile from source.

In Windows, it works by changing **tinygo/targets/esp8266.json** in the installation directory of pre-compiled tinygo.

![image](https://user-images.githubusercontent.com/15157070/114431374-57d79a00-9bb7-11eb-8b4d-5f36ade351dc.png)

**Comment by soypat** [comment]
Yes! that worked, thanks wuhanstudio. I'm on linux so it was in my `/usr/local/lib/tinygo` directory. Changing this file solves the issue. However I seem to have found a new bug in the process. The following blinky program does not work:

```go
package main

import (
	"machine"
	"time"
)

var cfg = machine.PinConfig{Mode: machine.PinOutput}
// The problem seems to lie with using D0 and D4 together. not sure though
var x = [...]machine.Pin{machine.LED, machine.D0}

func main() {
	for i := range x {
		x[i].Configure(cfg)
	}

	for {
		for i := range x {
			x[i].Low()
		}
		time.Sleep(time.Millisecond * 1000)
		for i := range x {
			x[i].High()
		}
		time.Sleep(time.Millisecond * 1000)
	}
}
```

The result should be blinky on `machine.LED` and `machine.D0` but it seems to crash leaving the LED on indefinitely. If I change `machine.D0` to `machine.D1` the program works as expected.

**Update**: the problem seems to be `D0`. Replacing line 9 with
```go

var x = [...]machine.Pin{machine.D1, machine.D2, machine.D3, machine.D4, machine.D5, machine.D6, machine.D7, machine.D8}
```
runs just fine.

**Comment by wuhanstudio** [comment]
![image](https://user-images.githubusercontent.com/15157070/114444502-e3a4f280-9bc6-11eb-834a-7fcbf333c2de.png)

For esp8266, the GPIO0 can not be controlled because it defines the boot mode.

The ESP8266 will enter the serial bootloader when GPIO0 is held low on reset. Otherwise it will run the program in flash.

GPIO0 Input | Mode
-- | --
Low/GND | ROM serial bootloader for esptool.py
High/VCC | Normal execution mode

https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection

**Comment by soypat** [comment]
Alright, that solves my issue.thanks @wuhanstudio
