### ISSUE TITLE
Support for building binaries targeting Windows

### ISSUE THREAD

**Issue by mohamadpk** [tinygo-org/tinygo#1781]
a one question.can compile for x86 or x64 embedded machine? like may car ecu .  ;)

**Comment by aykevl** [comment]
TinyGo already supports Linux on x86 and amd64, simply set `GOARCH` when compiling on Linux like you would do with regular Go. For details, see: https://tinygo.org/linux/

What kind of system would you like to target? Is it a small embedded Linux system or something else?

**Comment by mohamadpk** [comment]
tnx for your feedback.it is exact Linux.you saved my ass . but why not support windows embedded?

**Comment by deadprogram** [comment]
We'd been happy to receive contributions to add support for building binaries targeting Windows.

**Comment by deadprogram** [comment]
Released with 0.21 so now closing. Thank you!
