### ISSUE TITLE
Support SPI on STM32 L4 series

### ISSUE THREAD

**Issue by kenbell** [tinygo-org/tinygo#1785]
Some SVD patches are needed to get the same symbolic constants available as other platforms.  Have raised https://github.com/stm32-rs/stm32-rs/pull/535

Once SVD patches are merged, I'll update the stm32-svd repo

**Comment by kenbell** [comment]
PR to merge to stm32-svd repo: https://github.com/tinygo-org/stm32-svd/pull/3

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
