### ISSUE TITLE
stm32f40x: Reading data over SPI unreliable

### ISSUE THREAD

**Issue by kenbell** [tinygo-org/tinygo#1794]
Reading data over SPI is unreliable due to an internal feedback delay from SPI CLK to SPI SDI.

STM32F40x and STM32F41x Errata sheet
> In receive transaction, in both I2S and SPI Master modes, the last bit of the transacted frame
> is not captured when the signal provided by internal feedback loop from the SCK pin
> exceeds a critical delay. The lastly transacted bit of the stored data then keeps the value
> from the pattern received previously. As a consequence, the last receive data bit may be
> wrong and/or the CRCERR flag can be unduly asserted in the SPI mode if any data under
> check sum and/or just the CRC pattern is wrongly captured.

Fixed by #1793

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
