### ISSUE TITLE
Cannot indicate which ST-LINK to use when multiple plugged in

### ISSUE THREAD

**Issue by kenbell** [tinygo-org/tinygo#1816]
Currently, if multiple ST-LINK are plugged in to development box, it's not possible to indicate which one to use for flashing a target.  This makes it cumbersome to develop for & test multiple targets.

It is possible to select the desired ST-LINK by using the `hla_serial` openocd command, eg:
```
hla_serial 066CFF485648756687031446
```

This can be specified in the target configuration today, but that binds the serial number of a ST-LINK programmer into the target, which is undesirable.

To avoid hardcoding a specific way to identify programming devices, propose to add a new tinygo command-line option `programmer-cmd` (there is an existing command-line option `programmer` which takes values like `openocd`).  This would work like this:
```shell
tinygo gdb -target stm32f4disco-1 -programmer-cmd "hla_serial 066CFF485648756687031446" ./examples/ina228
```

The new `programmer-cmd` parameter would take one (or more) commands to be executed by the programmer software (eg openocd).  Commands can be separated by commas.  There would be no particular restrictions on the commands that can be supplied.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
