### ISSUE TITLE
Segfault after sync.Once ?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#1826]
A project I'm running with tinygo seems to be triggering a crash on the two platforms I've tried (amd64, both linux and mac).

It seems to occur in both 0.17 (prebuilt or self-built) and dev (though I can't quite say for certain my tests are valid - I am not 100% sure I'm cleaning up properly between runs).

As I minimized the test case, the crash wiggled around between sigsegv, sigabort, and null pointer panics.

It appears to happen shortly after a call to sync.Once's Do method, and commenting that out (or using an init function instead) prevents the crash.  It may also require nested functions.

Oddly, in a quick check just now, replacing the testcase with main() also seemed to keep the crash from happening.

Running ```tinygo test``` isn't enough to see the crash; you have to do ```tinygo test -c``` and run the binary yourself.

Here's a test case.  It could probably be reduced further (not sure if goreduce is up to it, I haven't tried it on this hand-reduced file yet).
```
package bug

import (
	"sync"
	"testing"
)

type Foo struct { }
type FooGen func() Foo
type FooGenListHolder struct {
	FooGens     []FooGen
}
type FooGenListHolderMaker func() *FooGenListHolder

func UseFooGenListHolderMakers(fooGenListHolderMakers ...FooGenListHolderMaker) {
	for _, fooGenListHolderMaker := range fooGenListHolderMakers {
		fooGenListHolderMaker()
	}
}
func GenerateAndUseFooGenListHolderMakers() {
	myFooGen := func() (Foo) {
		return Foo{}
	}
	fooGenListHolderMaker := func() *FooGenListHolder {
		println("Commenting out badnessOnce.Do(initBadness) avoids crash")
		badnessOnce.Do(initBadness)

		var fooGens []FooGen
		fooGens = append(fooGens, myFooGen)

		fooGenListHolder := FooGenListHolder{}
		return &fooGenListHolder
	}
	UseFooGenListHolderMakers(fooGenListHolderMaker, fooGenListHolderMaker)
}
func TestBug(t *testing.T) {
	GenerateAndUseFooGenListHolderMakers()
}

var badnessOnce sync.Once

func initBadness() {
}
```

Here's an example stack dump:
```
=== RUN   TestBug

Program received signal SIGSEGV, Segmentation fault.
bug.GenerateAndUseFooGenListHolderMakers$2 () at /home/dank/bug/bug_test.go:29
29			fooGens = append(fooGens, myFooGen)
(gdb) #0  bug.GenerateAndUseFooGenListHolderMakers$2 () at /home/dank/bug/bug_test.go:29
#1  0x0000000000402dfc in (*internal/task.Task).Resume (t=<optimized out>)
    at /home/dank/src/tinygo/src/internal/task/task_coroutine.go:23
#2  0x0000000000404382 in runtime.scheduler () at /home/dank/src/tinygo/src/runtime/scheduler.go:165
``` 

Here's my test script on linux:
```
#!/bin/sh
rm -rf log *.test ~/.caache/tinygo
tinygo test -c -opt 1
gdb ./*.test < $HOME/bug/cmds > log
if grep -q 'SIGSEGV' log && grep -q '#0 .*GenerateAndUseFooGenListHolderMakers$2' log
then
	echo PRESENT
else
	echo ABSENT
fi
```

where ~/bug/cmds is just
```
run
bt
quit
```

**Comment by aykevl** [comment]
This sounds a lot like a memory corruption.

Can you try `-gc=conservative`? I've seen crashes before with the default (extalloc) GC and this might be another instance of it.

**Comment by dkegel-fastly** [comment]
Update:
- sometimes you have to run the binary a few times before you see the crash
- the crash does not happen with -scheduler=none
- the test does not compile with -scheduler=tasks
- the crash does not seem to happen with -gc=conservative

**Comment by aykevl** [comment]
Interesting! In that case, I suspect that `-gc=extalloc` (the default on Linux and MacOS) is to blame. Especially since I've had mysterious issues before that were solved by switching to the conservative GC.

@niaow can you maybe take a look?

**Comment by deadprogram** [comment]
Now that #1860 has been merged, can we close this issue?

**Comment by niaow** [comment]
Huh, this is a different bug than the one I found.

**Comment by niaow** [comment]
Interestingly, turning gcDebug on causes this to pass.

**Comment by niaow** [comment]
Ok so specifically: observing the allocated pointer inside of `runtime.alloc` appears to change the codegen in some meaningful way.

**Comment by niaow** [comment]
Or maybe it could just be placing the pointer on the stack I guess?

**Comment by niaow** [comment]
Ok so I have narrowed this down a bit: when using coroutines, something is not being tracked properly. This issue can actually be replicated with the conservative collector too by forcing a GC on every allocation and zeroing freed blocks. Similar to #1245 , the extalloc collector may be triggering it more often due to more GC cycles and memory actually being quickly overwritten after freeing.

**Comment by dkegel-fastly** [comment]
This is still happening...

**Comment by dkegel-fastly** [comment]
The reduced test case seems to be passing now with both tinygo 0.19 and tinygo dev, even with -gc=extalloc, on my mac; I haven't tried on linux yet.

(Unfortunately, my larger app still seems to crash on mac without -scheduler=none.  I guess I'll try generating a new minimal testcase.)

**Comment by fgsch** [comment]
This still crashes under wasi and tinygo 0.19.0.

**Comment by peterbourgon** [comment]
@niaow 

> Ok so I have narrowed this down a bit: when using coroutines, something is not being tracked properly

Just some additional signal on this — we've been experiencing memory corruption issues with scheduler=coroutines since TinyGo v0.18.0. They appear to be loosely correlated to the number of allocations, seem to happen more under gc=conservative than gc=leaking, and _really_ get triggered if allocate a map at any point. We've so far been unable to produce a reliable reproducer that can be shared here :(

**Comment by niaow** [comment]
So there are a few things:
1. There are some bugs when using stack slots GC where things are not tracked properly, and stack slots GC is mostly required when we can't scan the stack (aka wasm).
2. There are some bugs in extalloc which I started to fix but did not finish. We have switched over to conservative where possible. (this does not affect wasm)
3. The coroutines system is really really complicated. I started working on support for asyncify to hopefully eventually replace it.
4. I think there is another bug somewhere i havent tracked down?

**Comment by peterbourgon** [comment]
We would be happy to use something other than coroutines, but AFAIK it is the only concurrent scheduler that works in Wasm/Wasi-land.

**Comment by niaow** [comment]
Right now with the default `conservative` collector and `tasks`, this no longer seems to replicate. I think this may be effectively fixed?

**Comment by dkegel-fastly** [comment]
Running our large app with conservative now crashes differently.   It may be a different crash, will investigate.

**Comment by dkegel-fastly** [comment]
OK, current dev with targets/wasi.json's default-stack-size bumped to 10000, and the app compiled with -scheduler=asyncify -gc=conservative does not crash.  So our stack just got a little out of hand.

Closing.
