### ISSUE TITLE
crypto/sha256 doesn't work on amd64

### ISSUE THREAD

**Issue by arp242** [tinygo-org/tinygo#1832]
`crypto/sha256` is listed as [supported](https://tinygo.org/lang-support/stdlib/), but it doesn't seem to work on amd64:

```
$ go run main.go
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

$ tinygo build -o test -x main.go
cc -no-pie -Wl,--gc-sections -L /data/src/tinygo -o /tmp/tinygo581617139/main /tmp/tinygo581617139/main.o /home/martin/.cache/tinygo/obj-fbced8a9773f0290f6e687666bf97daa131e97a2ce93c45b4c5e1314.o
/usr/bin/x86_64-unknown-linux-gnu-ld: /tmp/tinygo581617139/main.o: in function `(*crypto/sha256.digest).Write':
/usr/lib/go/src/crypto/sha256/sha256.go:191: undefined reference to `crypto/sha256.block'
/usr/bin/x86_64-unknown-linux-gnu-ld: /usr/lib/go/src/crypto/sha256/sha256.go:198: undefined reference to `crypto/sha256.block'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
error: failed to link /tmp/tinygo581617139/main: exit status 1
```

The problem seems to be that crypto/sha256 contains optimized assembly versions for some platforms such as amd64 and arm64. `block()` is defined in `sha256block_amd64.s`:

    TEXT ·block(SB), 0, $536-32

Via `sha256block_decl`:

```
// +build 386 amd64 s390x ppc64le

package sha256

//go:noescape

func block(dig *digest, p []byte)
```

I'm not sure if using assembly is a supported feature? I don't see why TinyGo shouldn't be able to use the assembly versions, at least in principle(?)

**Comment by dgryski** [comment]
The example at https://pkg.go.dev/crypto/sha256#example-New builds and runs fine for me with the latest release (v0.21).  Please reopen if you're still having issues.  (The assembly versions are not supported because llvm doesn't support Go-flavoured assembly).
