### ISSUE TITLE
Improve Docker quickstart

### ISSUE THREAD

**Issue by gfeun** [tinygo-org/tinygo#1834]
Hello,

I am experimenting with tinygo on micro-controller (esp8266/32 and arduino mega2560) and I'm having a lot of fun !

I see several ways to improve user onboarding and documentation regarding Docker.
I'll be glad to contribute changes if you find anything i list here useful.

This issue can be decomposed into tinier issues according to what you agree on.

### Document docker run --dev=/dev/tty... 
Docker allows to mount a host device inside the container using the --dev parameter.

This makes it possible to flash µC from inside a container ! 
And its great, no need to install any dependencies on the host, not even the tinygo binary.

A tinygo quickstart could be one command:  `docker run --dev=/dev/ttyUSB0 tinygo/tinygo:0.17.0 tinygo flash --port /dev/ttyUSB0 --target arduino example/blink.go`

### Package flashing utilities inside docker image

To flash from inside the image will require flashing dependencies to be installed on the docker image (avrdude etc...)

### Provide per architecture docker images

The [Dockerfile](https://github.com/tinygo-org/tinygo/blob/release/Dockerfile) has several stages defined but there is only one tinygo docker image available.

This image does not include all dependencies for all architecture, for example with `--target=nodemcu` I got:

 `error: failed to link /tmp/tinygo741062572/main: exec: "xtensa-esp32-elf-ld": executable file not found in $PATH` 

It could be great to provide one big image including all dependencies and several targeted images for each architecture.
Tags could be used to differentiate architecture, for example `tinygo/tinygo:avr-0.17.0`, `tinygo/tinygo:xtensa-0.17.0`. `tinygo/tinygo:0.17.0` would be the big, all included image.

### Build the docker image(s) in the CI
It doesn't seem that the docker image is built from the CI (i may have overseen this).

If we choose to build several images, doing so in the CI would be easier to automate.
This image building operation could occur on a new tag.

Happy to discuss this changes and contribute PR :slightly_smiling_face:

**Comment by deadprogram** [comment]
Closing due to age. Thank you!
