### ISSUE TITLE
"unable to locate a serial port" error because of missing "/dev/ttyACM0", even when I don't use it

### ISSUE THREAD

**Issue by jypelle** [tinygo-org/tinygo#1839]
With tinygo 0.17.0 on ubuntu 20.04, If I want to flash my arduino-nano, I should execute as a workaround:

```
cd /dev
sudo ln -s ttyUSB0 ttyACM0
```

Before flashing with

```
tinygo flash -target=arduino-nano ./cmd/myawesomeproject --port=/dev/ttyUSB0
```

Without the workaround, I got a "unable to locate a serial port" error message because tinygo always check the presence of at least one "/dev/ttyACM*" even if it doesn't use it.

**Comment by gfeun** [comment]
Hey @jypelle,

Try passing your command parameters before you input and use only one dash.

Like so: `tinygo flash -target=arduino-nano -port=/dev/ttyUSB0 ./cmd/myawesomeproject`

**Comment by jypelle** [comment]
Indeed, I should have reread myself, It works as expected
