### ISSUE TITLE
"make llvm-build" fails if invoked from within another makefile?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#1857]
"make llvm-build" is failing for me with 
```
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Success
+ /Library/Developer/CommandLineTools/usr/bin/ld -v
+ head -1
CMake Error at /Users/dkegel/tinygo.tmp/tinygo/llvm-project/clang/CMakeLists.txt:434 (message):
  /Library/Developer/CommandLineTools/usr/bin/ld failed with status 141
```

However, I think this only happens if I invoke it from within another Makefile.

I tried clearing the obvious environment variables set by the outer Make, but that didn't help.

Probably user error, recording it here in case someone else runs into it.

**Comment by aykevl** [comment]
Maybe the current working directory needs to be changed? Just a guess.

**Comment by dankegel** [comment]
That's not it, I think. 

This is not really a tinygo bug, may as well close or ignore until someone figures out what's going on.

**Comment by deadprogram** [comment]
In that case I will close. Please reopen if needed. Thanks!
