### ISSUE TITLE
regression: tinygo apps crash in one wasi runtime if argc == 0?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#1862]
Since https://github.com/tinygo-org/tinygo/commit/7b761fac7805083dd0263ed376b10e106726ef8f,
tinygo apps crash on one wasm runtime.  It seems the runtime used by my employer does not provide argv[0].
I could not reproduce the problem with wasmtime or wasmer, but the problem is quite reproducible in our environment.

I also tested on mac and linux, using execve to run a tinygo app without argv[0], but that worked without a crash;
linux actually does allow running with no argv[0], believe it or not, but that didn't cause a problem as it did with wasi.

The change to tinygo to avoid the crash in the wasi case is, well, tiny.  Pull request coming.

**Comment by deadprogram** [comment]
Since this issue was introduced in-between releases I am going to mark as closed. Thanks @dkegel-fastly for the report and the fix!
