### ISSUE TITLE
[DEV] Building wasm with none scheduler: default stack size for goroutines is not set

### ISSUE THREAD

**Issue by fgsch** [tinygo-org/tinygo#1875]
When building using the dev branch at `d7ec9ddcd23e7ba8bab2cb50780a6fda573ae8f3`, I'm now seeing:

`/usr/local/Cellar/go/1.16.3/libexec/src/time/sleep.go:180:2: default stack size for goroutines is not set`

Command line:

`tinygo build -target=wasi -scheduler=none -wasm-abi=generic -o main.wasm`

This works fine with 0.17.0 and I'd guess until `9f5066aa6f1d67f161bc0d7520dc2f1bfa1f2b0d`.
Using the `coroutines` scheduler also works. 

I wonder if the added check in `9f5066aa`:

```
if b.DefaultStackSize == 0 {
                        b.addError(pos, "default stack size for goroutines is not set")
}
```

should only apply to the "tasks" scheduler (which works).

**Comment by aykevl** [comment]
This should fix it: https://github.com/tinygo-org/tinygo/pull/1876

Before:

```
$ tinygo build -o test.wasm -scheduler=none ./testdata/env.go
/home/ayke/src/github.com/tinygo-org/tinygo/src/runtime/runtime_wasm_js.go:32:5: default stack size for goroutines is not set
```

After:

```
$ tinygo build -o test.wasm -scheduler=none ./testdata/env.go
/home/ayke/src/github.com/tinygo-org/tinygo/src/runtime/runtime_wasm_js.go:32:2: attempted to start a goroutine without a scheduler
```

I don't think `-scheduler=none` is currently supported in WebAssembly, but the PR linked above should improve the error message.

**Comment by fgsch** [comment]
Thank you. That's what I had in my tree.

FWIW, we've been using `-scheduler=none` with `-target=wasi` without issues. 

This can probably be closed now as it was an issue in the dev branch.

**Comment by deadprogram** [comment]
OK great. Now closing, thanks everyone!
