### ISSUE TITLE
tinygo work in Win10

### ISSUE THREAD

**Issue by wcpsoft** [tinygo-org/tinygo#1935]
I want to tinygo support build code in the win10.Do you need to use tinygo to compile code in docker container and then burn program in win10

**Comment by deadprogram** [comment]
You can run the TinyGo compiler on Windows 10. But you cannot yet build executable files targeting the Windows operating system. In other words, you can run TinyGo on Windows to build programs for microcontrollers and/or WebAssembly, but not build programs that can run on Windows itself.

Hope that helps!

**Comment by wcpsoft** [comment]
thanks,
