### ISSUE TITLE
CGo doesn't support functions defined in a CGo import block

### ISSUE THREAD

**Issue by rtttech** [tinygo-org/tinygo#1943]
I used cgo in my code as following, compile success but wasm load failed: "Failed to load Wasm module due to a missing import: env.my_time"

```go
/*
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

int64_t my_time() {
return time(NULL);
}
*/
import "C"
```
...

**Comment by fsyyft** [comment]
I also encountered the same problem, hope to get help!

**Comment by aykevl** [comment]
Yes, it's not currently supported to define functions in the header. What you can do instead is move the code (in this case the function `my_time`) into a separate C file and declare it above `import "C"` instead.

Removing the wasm label because it's not specific to WebAssembly.

**Comment by rtttech** [comment]
How to compile the .go file with the added c file?

**Comment by aykevl** [comment]
You can put them in the same package. The C file will be compiled together with the Go files in the package. Please see https://golang.org/doc/code for how code is normally organized in Go.

**Comment by rtttech** [comment]
Thanks!
