### ISSUE TITLE
Why does adding port operations improve performance?

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#1955]
In my efforts to improve the performance of ili9341, I found a strange behavior.

The following two branches have very different speeds.
The x02 branch is nearly 10 percent faster, despite having one more port operation.

```
tinygo flash --target feather-m4-can --size short --programmer cmsis-dap --scheduler tasks ./examples/ili9341/pyportal_boing/
```

* with `dbg5.Low()` : 96 fps
    * https://github.com/tinygo-org/drivers/tree/x02
    * https://github.com/tinygo-org/drivers/blob/x02/examples/ili9341/pyportal_boing/main.go#L170

![image](https://user-images.githubusercontent.com/9251039/122339831-7faef980-cf7c-11eb-96b0-67c69ac26fb0.png)

* without `dbg5.Low()` : 85 fps
    * https://github.com/tinygo-org/drivers/tree/x03
    * https://github.com/tinygo-org/drivers/blob/x03/examples/ili9341/pyportal_boing/main.go#L170

![image](https://user-images.githubusercontent.com/9251039/122339836-8178bd00-cf7c-11eb-8830-d2c80e65dcd1.png)

The only differences in the source code are the following

* https://github.com/tinygo-org/drivers/commit/4c59a3ff90b7290998881c3047be0fbd8924ed12#diff-8e902458c9da6983b9e1e8f334551b97ca7418023737a19b68cf179c224b4c3a

The diff of *.ll is as shown in the screenshot below.
I've compared them with the debug information removed.

```
tinygo build -o xxx.ll --target feather-m4-can --size short --scheduler tasks ./examples/ili9341/pyportal_boing/
```

![image](https://user-images.githubusercontent.com/9251039/122340121-d6b4ce80-cf7c-11eb-9a9a-99ffdcf28a77.png)

Is there any way to find out what is causing this?
Is it an alignment issue?
Or is there some other reason?

**Comment by sago35** [comment]
x02's log:
```
width, height == 240 320
128  fps
102  fps
96  fps
102  fps
98  fps
96  fps
94  fps
97  fps
96  fps
94  fps
93  fps
96  fps
```

x03's log:
```
width, height == 240 320
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
85  fps
```

**Comment by aykevl** [comment]
You could disassemble the binary. One IR instruction could lead to a big difference in the generated assembly.

Also, if you are optimizing for performance you should use `-opt=2` (which is like `-O2` in GCC), the default is to optimize for code size. It may make a difference.

**Comment by sago35** [comment]
When I measured again, I got the following results.
I used the latest version of tinygo compiler.


* x02 (with dbg5.Low())
    * w/o opt : 96 fps
    * opt=2 : 108 fps
* x03 (without dbg5.Low())
    * w/o opt : 104 fps
    * opt=2 : 103 fps

```
$ tinygo version
tinygo version 0.19.0-dev-0e267dd2 windows/amd64 (using go version go1.16 and LLVM version 11.0.0)
```

**Comment by deadprogram** [comment]
I think this was actually solved by https://github.com/tinygo-org/tinygo/pull/3492

Should we close it on next release?

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
