### ISSUE TITLE
Design for SPI using DMA with atsamd51

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#1973]
I am working on a design for SPI with DMA on atsamd51.

> I think we'll always want to use DMA. That is an easier to use API and likely faster overall.
> https://github.com/tinygo-org/tinygo/pull/1176#issuecomment-648437757

Tx() to always use dma if possible, but at least atsamd51 slows things down in some cases.
If the data is small or the communication speed is slow, using DMA will slow down spi.Tx().

To reduce the slowdown, I am considering implementing the following.
If anyone has any opinions, please let me know.

```go
// The following will be executed with blocking as before
// The internal implementation will be the same as before, without DMA.
spi.Tx(w, r)

// The following will be executed using DMA.
// It will always run asynchronously and can wait for completion by calling spi.
spi.TxDMA(w, r)
spi.Wait()

```

**Comment by sago35** [comment]
D6 (Channel 6) below is the processing time for spi.Tx() / spi.TxDMA().
When using DMA, about 2.5us of time is needed to prepare for the transfer.
However, after 2.5us has elapsed, the DMA will execute, allowing you to perform other operations.
I checked several lengths, and it seems that using DMA is not a problem when the length is 32 bytes or more.

freq : 24MHz

1byte + without DMA = 738ns
![image](https://user-images.githubusercontent.com/9251039/123581098-29f90d80-d816-11eb-9476-fed8acdc662b.png)

1byte + with DMA = 4446ns
![image](https://user-images.githubusercontent.com/9251039/123581102-2cf3fe00-d816-11eb-92d1-f01cc3800359.png)

32byte + without DMA = 13.494us
![image](https://user-images.githubusercontent.com/9251039/123581138-4006ce00-d816-11eb-8191-10968900b912.png)

32byte + with DMA = 14.798us
![image](https://user-images.githubusercontent.com/9251039/123581144-4432eb80-d816-11eb-8327-4750048e97bf.png)

64byte + without DMA = 26.638us
![image](https://user-images.githubusercontent.com/9251039/123581150-49903600-d816-11eb-8db1-79c16cc66fc3.png)

64byte + with DMA = 25.452us
![image](https://user-images.githubusercontent.com/9251039/123581162-4e54ea00-d816-11eb-8d27-c682f7de5108.png)

**Comment by soypat** [comment]
I'm linking a implementation of DMA on the RP2040 for your viewing pleasure. It is inspired by Rust's embassy implementation.

https://github.com/tinygo-org/pio/blob/main/rp2-pio/piolib/dma.go

**Comment by sago35** [comment]
I plan to switch to the method used in the following PR.

#3985
