### ISSUE TITLE
avr-gcc

### ISSUE THREAD

**Issue by fatih-dogmus** [tinygo-org/tinygo#1980]
When I type scoop install avr-gcc it gives this error:
The remote server returned an error: (403) Forbidden.
URL https://dl.bintray.com/lumito/public/projects/avr-gcc/10.2.0/avr-gcc-10.2.0-x64-windows.7z is not valid

What's the new link and how can i integrate?

**Comment by deadprogram** [comment]
Please see https://github.com/tinygo-org/tinygo/issues/1323

**Comment by aykevl** [comment]
This is not a duplicate. This is an issue upstream in Scoop, here: https://github.com/lukesampson/scoop/issues/4371 (pending PR: https://github.com/ScoopInstaller/Main/pull/2246).

I'm going to close this issue as it is not a TinyGo bug.

**Comment by thushan** [comment]
It was just merged in to fix this.
