### ISSUE TITLE
got LinkErrors when i run wasm on browsers

### ISSUE THREAD

**Issue by Taoja** [tinygo-org/tinygo#2012]
the error said:
`LinkError: WebAssembly.instantiate(): Import #5 module="env" function="math/big.shrVU" error: function import requires a callable`

golang version: 1.14.6
tinyGo version: 0.19.0
wasm_exec.js is come from tinyGoRoot/targets/
build shell command: 
`tinygo build -o pkg/lib.wasm -target wasm main.go`

**Comment by fgsch** [comment]
This should be fixed by #2002. 
In the meantime try building with `tinygo build -target wasm -tags math_big_pure_go -obj pkg/lib.wasm main.go`.

**Comment by Taoja** [comment]
> This should be fixed by #2002.
> In the meantime try building with `tinygo build -target wasm -tags math_big_pure_go -obj pkg/lib.wasm main.go`.

the -obj flag is error? 
`flag provided but not defined: -obj`

i try change the -obj to -o then it is worker.
but got a new error on runtime:
`
syscall/js.finalizeRef not implemented
syscall/js.finalizeRef @ lib.js:305
syscall/js.jsString @ lib.wasm:0xf24f
(syscall/js.Value).String.resume @ lib.wasm:0xeefc
runtime.scheduler @ lib.wasm:0xcfe5
resume @ lib.wasm:0xde10
_resume @ lib.js:490
(anonymous) @ lib.js:501
syscall/js.valueNew @ lib.js:380
(syscall/js.Value).New.resume @ lib.wasm:0x103f3
runtime.scheduler @ lib.wasm:0xcfe5
resume @ lib.wasm:0xde10
_resume @ lib.js:490
(anonymous) @ lib.js:501
(anonymous) @ VM626:1


lib.js:267 panic: runtime error: nil pointer dereference

VM626:2 RuntimeError: unreachable
    at runtime.runtimePanic (lib.wasm:0x957b)
    at runtime.nilPanic (lib.wasm:0x205e)
    at (io.Reader).Read (lib.wasm:0x62b7)
    at io.ReadAtLeast (lib.wasm:0x6265)
    at io.ReadFull (lib.wasm:0x6390)
    at github.com/tjfoc/gmsm/sm2.randFieldElement (lib.wasm:0x3bb46)
    at github.com/tjfoc/gmsm/sm2.Encrypt (lib.wasm:0x3a7bf)
    at main.encryptKey.resume (lib.wasm:0x4165c)
    at runtime.scheduler (lib.wasm:0xcfe5)
    at resume (lib.wasm:0xde10)
`

**Comment by deadprogram** [comment]
Closing since it appears to have been fixed. Please reopen if needed. Thank you!
