### ISSUE TITLE
[GameBoyAdvance] Tinygo build don't build a correct GBA ROM and execute .gba file with mgba fails: "The game crashed!"

### ISSUE THREAD

**Issue by scraly** [tinygo-org/tinygo#2025]
Hi,

I tested to run and build the gba-display example found in this repository.

Cool, the tinygo run command is orking:

```
$ tinygo run -target=gameboy-advance gba-display.go
tinygo:ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
```
<img width="398" alt="image" src="https://user-images.githubusercontent.com/2543381/128160278-960bc5a6-4fb4-4026-8341-6b7661c818d2.png">

But unfortunately I can't build successfully the gba binary and when I test it through mgba emulator, it fails! :( 

```
$ tinygo build -target=gameboy-advance -o bin/gba-display.gba gba-display.go 
tinygo:ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected

$ file bin/gba-display.gba
bin/gba-display.gba: data

$ mgba bin/gba-display.gba
The game crashed!
```

Same things when I launch mgba in the graphical way:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/2543381/128163216-eb9b7717-f3fe-41e0-ad50-39b9910860fd.png">

So, I can't build a working gba ROM file.

```
$ tinygo version
tinygo version 0.19.0 darwin/amd64 (using go version go1.16.5 and LLVM version 11.0.0)

$ mgba --version
mgba 0.9.2 (f6d5f51d231053cc8a1778b7a139096d2bcf7324)
```

Is it possible to know how to remove the warning message and to fix the bug?

Thanks

**Comment by deadprogram** [comment]
This is no longer a problem at least with the 0.28 release coming soon. Tagging to close this issue on next release. Thanks @scraly

**Comment by scraly** [comment]
Thanks @deadprogram 
I will test it soon! :)

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
