### ISSUE TITLE
[Suggestion] aarch64 deb

### ISSUE THREAD

**Issue by Nebdir** [tinygo-org/tinygo#2026]
it would be awesome if a build for aarch64 could be provided as the current release only ships armhf.

My usecase would be a easy installation in termux as i would love to run a few things from my phone while traveling by train.

my target would be the esp32/gba

about limitations i remember that i did a espressif install about a year ago and did a flash that acually worked. 
i appreciate any corrections if im wrong.

**Comment by LaPingvino** [comment]
Also useful for many ChromeOS systems, as they come with Debian aarch64 on ARM systems.

**Comment by cancecen** [comment]
Any plans of doing this? @deadprogram I noticed that this was marked as an enhancement, wondering if you have any plans for doing this soon.

**Comment by aykevl** [comment]
We have support for this in the dev branch, the next release will have an aarch64 binary: https://github.com/tinygo-org/tinygo/pull/2835

**Comment by cancecen** [comment]
@aykevl this is great thank you. Any rough idea on when next release would be?

**Comment by aykevl** [comment]
No plans currently, but maybe it would be a good idea in the not too distant future.

**Comment by deadprogram** [comment]
We will have a release soonish.
