### ISSUE TITLE
Question: use tinygo build error  

### ISSUE THREAD

**Issue by any-u** [tinygo-org/tinygo#2029]
## info
![image](https://user-images.githubusercontent.com/20504116/128470900-e3ab589b-e290-4f2c-9d68-8485742df65d.png)

## verison
![image](https://user-images.githubusercontent.com/20504116/128470966-aea06655-bd2c-47c6-a5e1-875e61147cb7.png)

I can use go-build to build, but if I use tinygo, an error will be reported

**Comment by peterbourgon** [comment]
TinyGo does not support Protocol Buffers.

**Comment by any-u** [comment]
thanks.
