### ISSUE TITLE
Update the getting-started install page

### ISSUE THREAD

**Issue by SoftTacos** [tinygo-org/tinygo#2042]
The installation instruction versions are behind the latest version on https://tinygo.org/getting-started/install/linux/
I tried to edit the page to change all of the 0.18 to 0.19, however the edit page button gives me a 404.

Thanks for all the work on this project, finally getting into microcontrollers and this has been a huge help!

**Comment by deadprogram** [comment]
This was updated on the site, so now closing. Thanks for reporting @SoftTacos
