### ISSUE TITLE
How to export memory or a global variable?

### ISSUE THREAD

**Issue by zu1k** [tinygo-org/tinygo#2045]
I want to expose a memory or variable, my wasm code is like that:

```
//export id
var id = "id_007"

//export const_str
const const_str = "const str"

//export sum
func sum(i,j int32) int32 { return i+j }
```

I can found the exported func `sum`, but I found that these variables or constants were not being exported, maybe, I can't found them.

How can I export a memory, a variable correctly? Thanks!

**Comment by vlkv** [comment]
I am also curious how to do that. Can somebody answer or throw an url to the docs?..

**Comment by radkomih** [comment]
Looks like exporting `globals, memory` is not currently supported?
I hope someone to confirm that.

**Comment by aykevl** [comment]
I do not believe WebAssembly supports these kind of globals. The globals it does support are limited to the standard WebAssembly types (`i32`, `i64`, etc) and don't include structs for example.

Memory should already be exported by default.

**Comment by radkomih** [comment]
Hmm, I've asked because I have `wasm` compiled with the `rust` toolchain and one compiled with `tinygo` and there are some differences. I am not sure how these `Globals` got exported?

Compiled with  rust toolchain
```js
Type: wasm
Imports:
  Functions:
    "env"."Another_provider_func": [I32, I64, I64] -> []
    ...
  Memories:
    "env"."memory": not shared (20 pages..)
  Tables:
  Globals:
Exports:
  Functions:
    "My_custom_func": [I32, I32] -> [I64]
  Memories:
  Tables:
    "__indirect_function_table": FuncRef (352..352)
  Globals:
    "__data_end": I32 (constant)
    "__heap_base": I32 (constant)
```

Compiled with tinygo
```js
Type: wasm
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "malloc": [I32] -> [I32]
    "free": [I32] -> []
    "calloc": [I32, I32] -> [I32]
    "realloc": [I32, I32] -> [I32]
    "_start": [] -> []
    "My_custom_func": [I32, I32] -> [I64]
  Memories:
    "memory": not shared (2 pages..)
  Tables:
  Globals:
```

**Comment by aykevl** [comment]
You mean `__data_end` and `__heap_base`? Those are defined by the linker, not by Rust. I'm not sure why they were exported.
