### ISSUE TITLE
Support zero runtime web assembly modules

### ISSUE THREAD

**Issue by richardanaya** [tinygo-org/tinygo#207]
I noticed when compiling a tinygo web assembly module:

* main gets re-exported as "cwa_main"
* functions without bodies get set as some import that is a concatination of their filename + name
* io_get_stdout and other functions are assumed to exist as imports

it would be nice to have a zero runtime compile option for web assembly that:
* exports main properly as "main"
* functions without bodies and without //go export: <name> don't show up in imports
* does not assume io_get_stdout and other functions

**Comment by abourget** [comment]
This would be useful to use tinygo in other environments where you don't control the VM, like in Blockchains (thinking of EOS here) for example.

**Comment by abourget** [comment]
Perhaps a flag that makes the compile use `1` by default for `stdout` ?  With `tiny build -panic trap`, we can remove `resource_write`, but didn't find any way to get rid of `io_get_stdout`.

**Comment by abourget** [comment]
I'd also like to be able to define how the import is declared within the imports section of the wasm. Right now I see:

```
  (import "env" "./wasmthing.go.add" (func $./wasmthing.go.add (type 2)))
```

when defining:

```golang
func add(x, y int) int
```

alone in `wasmthing.go`.  I'd like it to be `add` or something I define, perhaps with `//go:import add` ?

**Comment by deadprogram** [comment]
Hello all. I think this latter request has been addressed now via https://github.com/tinygo-org/tinygo/commit/55144ad6085c5c0c28d154589c8a7f2f1568364a

Not sure about the original items as requested.

**Comment by deadprogram** [comment]
Closing as I think the requested items now exist. Please reopen or open new issues as needed. Thank you.
