### ISSUE TITLE
Go 1.17 not yet supported

### ISSUE THREAD

**Issue by Ulset** [tinygo-org/tinygo#2080]
On running 
`tinygo flash -target arduino Arduino.go`

I get the following error message:
`error: could not read version from GOROOT (/opt/homebrew/Cellar/go/1.17/libexec): Invalid go version output:`

Im on Go version 1.17 and TinyGo version 0.19.0

**Comment by macedo** [comment]
same here

**Comment by dgryski** [comment]
This is https://github.com/tinygo-org/tinygo/pull/2048 that will be fixed in the next release.

**Comment by deadprogram** [comment]
TinyGo 0.19.0 does not support Go 1.17.  Please try the `dev` branch if you need that support right away, downgrade to Go 1.16.x or just wait for the upcoming next release.

**Comment by deadprogram** [comment]
Released with 0.20.0 so now closing. Thank you!

**Comment by dosgo** [comment]
0.20.0 No windows-amd64.zip package,does it support windows?

**Comment by sago35** [comment]
@dosgo 
The binary for windows has been completed and is attached.
https://github.com/tinygo-org/tinygo/releases/tag/v0.20.0
