### ISSUE TITLE
link errors on darwin when using -gc=leaking or -scheduler=coroutines

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2081]
The default configuration includes assembly files which have link errors (due to undefined references) if you build with `-gc=leaking` or `-scheduler=coroutines`.

If using `leaking`, the included `gc_amd64.S` file expects an implementation of `scanstack`, which is only provided for `conservative` and `extalloc`.

Similarly, the `task_stack_amd64.S` file expects an implementation of `_task_pause`, which is a compiler intrinsic for `-scheduler=coroutines`.

https://github.com/tinygo-org/tinygo/blob/release/compileopts/target.go#L262

**Comment by dgryski** [comment]
This bug should be tagged `next-release` ?

**Comment by deadprogram** [comment]
Indeed, thanks for the reminder @dgryski
