### ISSUE TITLE
Potential copy-paste error in machine_atsamd21

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2097]
The surrounding code strongly suggests the body of the `if` should be `calibTrim = 3` not `calibTransN = 3`.

```
        if calibTrim == 0x7 {
                calibTransN = 3
        }
        sam.USB_DEVICE.PADCAL.SetBits(calibTrim << sam.USB_DEVICE_PADCAL_TRIM_Pos)
```

https://github.com/tinygo-org/tinygo/blob/release/src/machine/machine_atsamd21.go#L1961

A similar issue is present at https://github.com/tinygo-org/tinygo/blob/release/src/machine/machine_atsamd51.go#L2170

**Comment by dgryski** [comment]
@deadprogram Should I make PR for this?  This bug was found by static analysis tooling but I wanted somebody else opinion before I submitted the obvious fix.

**Comment by deadprogram** [comment]
@dgryski yes please.

**Comment by dgryski** [comment]
https://github.com/tinygo-org/tinygo/pull/2105
