### ISSUE TITLE
How to set max memory in wasm?

### ISSUE THREAD

**Issue by zhenjunMa** [tinygo-org/tinygo#2108]
### 1. background

In my case, i want to limit the max memory that the `*.wasm` file can use, if it reached the limit, it can crash by OOM.

it's better for me to limit both stack and heap memory.

### 2. what i have tried

i write a `a.go`, the content as follows:

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("hello")
}
```
then, i build this file by the command `tinygo build -o a.wasm -target=wasi a.go`

at last, i run `a.wasm` as follows:
```
> wasmtime a.wasm
hello
```

now, i decompiled `a.wasm` to `wat file` by command `wasm2wat a.wasm -o a`.

i found the memory segment in the wat file as folows:
![image](https://user-images.githubusercontent.com/28104581/133037659-dfaeda33-2555-4cf2-83bc-014a2bdd722a.png)

`(memory (;0;) 2)` means the init memory is 2 pages, size is 65536 * 2 bytes, and no max memory limit, which means it can grow memory as needed.

i directly edit the wat file and modified the memory segment to `(memory (;0;) 1 1)`, which means the init memory is 1 page and the max is 2 page,

now i compiled the wat file to wasm file by the command `wat2wasm a -o a.wasm` and run it by `wasmtime`

i got the error as follows
```
Error: failed to run main module `a.wasm`
Caused by:
    0: failed to invoke command default
    1: wasm trap: out of bounds memory access
```
it indeed what i want to see.

### 3. my question

in my opinion, maybe there is a method to set max memory limit before i build it.

i tried some method on the internet as follows
```
tinygo build -o function1.wasm -target=wasi -ldflags="-z stack-size=2048 --max-memory=65536" a.go
```
but i got a error:
```
flag provided but not defined: -z
Usage of link:
  -X value
    	Set the value of the string variable to the given value.
```

when i remove the `-z` param like this:
```
tinygo build -o function1.wasm -target=wasi -ldflags="stack-size=2048 --max-memory=65536" a.go
```

it succeed, but the memory segment is also `(memory (;0;) 2)`, nothing happened.

any idea about this? looking forward for your reply.

### 4. tinyGo version

`> tinygo version`
`tinygo version 0.18.0 darwin/amd64 (using go version go1.16 and LLVM version 11.0.0)`

### 5. more info

In my case,  i also want to limit the max cpu cycle used by wasm file,  maybe this is more difficult than limit max memory, any idea about this?

**Comment by aduros** [comment]
I also had trouble using the `-ldflags` option. What seemed to work was compiling with `tinygo build ... -target ./target.json`, and putting something like this in target.json:

```json
{
    "inherits": [ "wasm" ],
    "ldflags": [
        "--initial-memory=65536",
        "--max-memory=65536",
        "-zstack-size=2048"
    ]
}
```

**Comment by zhenjunMa** [comment]
@aduros 

cool!  it really works!

![image](https://user-images.githubusercontent.com/28104581/133185641-50866914-0938-4f44-a80e-2e6ae48c51e7.png)

i found the memory segment is changed, now i just need to learn how to set cpu limit.

**Comment by aykevl** [comment]
Yeah, there are not many people who want to limit memory in this way so I'm not sure whether it's worth it to add a flag for this feature. The `ldflags` as indicated above seems like a good way to do this for now.

> In my case, i also want to limit the max cpu cycle used by wasm file, maybe this is more difficult than limit max memory, any idea about this?

What do you mean? There is no way to do this in WebAssembly directly. This is something the embedder will have to do by counting instructions for example.

**Comment by zhenjunMa** [comment]
> What do you mean? There is no way to do this in WebAssembly directly. This is something the embedder will have to do by counting instructions for example.

Right! i found some wasm runtime, e.g. wasmtime, provide API to limit the number of executable instructions in wasm.

**Comment by deadprogram** [comment]
Closing due to question appears to have been answered. Thank you everyone!
