### ISSUE TITLE
Slow interpreting complex init functions

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2124]
After applying #2001 to work around #1848, I appear to be running into something like #2090, but for trees.

Reproducer:
```
package main

import ac "github.com/cloudflare/ahocorasick"

var foo = ac.NewStringMatcher([]string{
        "axaxxxaxxaaa",
        "axaxxxaxxax",
        "xaxaxxxxaxxxx",
        "xaxaxxxxxxxaaqq",
        "xaxaxxxxxxxxxqq",
        "xaxxxxxxxaaqq",
        "xxaxaxaaax",
        "xxaxaxaaxaxa",
        "xxxaxaaaaaax",
        "xxxaxaaaaaaxqq",
        "xxxaxaaxqqqq",
        "xxxxaaaxaxa",
        "xxxxaaxxxx",
})

func main() {
	println("test")
}
```

```
$ time go build
real	0m0.215s
user	0m0.163s

$ time tinygo build -o foo.wasm -target wasm main.go
real	0m11.913s
user	0m32.456s
```

Adding more strings to the list causes compile time to increase rapidly.

**Comment by deadprogram** [comment]
How is this issue with the latest `dev` branch? Same problem still exist?

**Comment by dgryski** [comment]
Yes, interp still causes timeouts creating large data structures at build time.

**Comment by aykevl** [comment]
This does sound very much like a duplicate of #2090. Maybe the cause is different, but it certainly sounds like a duplicate.

**Comment by dkegel-fastly** [comment]
Yes.  Interesting it can be triggered with so few entries.

**Comment by dgryski** [comment]
There are so few entries in this case because `interp` is trying to run `ahocorasick.NewStringMatcher()` and that's taking the time.  Same reason global regexps timeout.

**Comment by dankegel** [comment]
Dup of 2090, whose title might want to change slightly.

**Comment by dkegel-fastly** [comment]
Closing as dup of #2090.
