### ISSUE TITLE
WriteString and WriteAt for *os.File are not implemented

### ISSUE THREAD

**Issue by Elara6331** [tinygo-org/tinygo#2157]
When trying to use [github.com/dlclark/regexp2](https://github.com/dlclark/regexp2), I encounter the following error:
```
os.Stdout.WriteString undefined (type *os.File has no field or method WriteString)
```
I looked at the stdlib of tinygo and noticed that `WriteString` and `WriteAt` are not implemented. `WriteString` seems like a pretty simple feature to implement, but I do not know enough about tinygo to be able to tell for sure.

**Comment by dgryski** [comment]
`WriteString` is easy enough to implement:

```
func (f *File) WriteString(s string) (n int, err error) {
       return f.Write([]byte(s))
}
```

although this can be improved to zero-copy by using `unsafe` to get the `[]byte` from `s` directly.

Given that `Seek` and `ReadAt` aren't implemented, I think it's totally fair to return an `ErrNotImplemented` from `WriteAt` as well (as long as you don't actually need that functionality).
