### ISSUE TITLE
[Question] Does TinyGo Intend on Supporting Generics?

### ISSUE THREAD

**Issue by danforbes** [tinygo-org/tinygo#2158]
[Generics are coming to Go](https://github.com/golang/go/issues/43651) 🚀 Does TinyGo plan on supporting this long-awaited feature?

**Comment by soypat** [comment]
From what I've heard on the #tinygo Slack channel from experienced TinyGo developers, generics are a welcome feature. I had heard @ardnew mention generics would make writing USB CDC drivers much easier, if I recall correctly.

**Comment by niaow** [comment]
TinyGo does (or at least intends to) support all core language features of Go. We will probably need to include this in the first TinyGo release to support Go 1.18 (assuming that generics remain on by default in 1.18).

**Comment by aykevl** [comment]
Yes, I very much intend to add support for generics. However, this is potentially a big change that needs a lot of work from TinyGo, so I can't promise that it will be supported right away with the first TinyGo release that supports Go 1.18.

**Comment by soypat** [comment]
Little PSA for all future generics users:
> [Russ Cox](https://groups.google.com/u/1/g/golang-dev/c/iuB22_G9Kbo) _"We expect that some package authors will be eager to adopt generics. If you are updating your package to use generics, please consider isolating the new generic API into its own file, build-tagged for Go 1.18 (//go:build go1.18), so that Go 1.17 users can keep building and using the non-generic parts."_

**Comment by ibudisteanu** [comment]
This would be great! For example, the package I am helping with already uses generics. Without support for generics would introduce a barrier to use TinyGo in order to reduce WASM bundles sizes. We will wait for Generics support in tinygo.

**Comment by deadprogram** [comment]
See https://github.com/tinygo-org/tinygo/pull/2903
