### ISSUE TITLE
go 1.12 - wasm

### ISSUE THREAD

**Issue by Zambiorix** [tinygo-org/tinygo#216]
I just updated to 1.12 and when compiling my project with tinygo, I get the following error:

```
/usr/local/go/src/internal/fmtsort/sort.go:58:19: invalid operation: mapValue (variable of type reflect.Value) has no field or method MapRange
```

It compiled just fine with 1.11.5 earlier

**Comment by aykevl** [comment]
Go 1.12 is not yet supported. I have an in-progress (unfinished) PR that will add support in #211. Some non-trivial changes are needed to add support.

**Comment by deadprogram** [comment]
This support has just landed in the `dev` branch, please give it a try @Zambiorix

**Comment by deadprogram** [comment]
Release v0.5.0 now supports this, so closing this issue. Thanks!
