### ISSUE TITLE
OOM crash when compiling sorty tests

### ISSUE THREAD

**Issue by jfcg** [tinygo-org/tinygo#2179]
Tinygo oom-crashes when compiling [sorty](https://github.com/jfcg/sorty) `v1.2.0` tests. I'm on Manjaro Linux with kernel `5.10.70` and i5-4210M CPU.
With Go 1.17
```
$ tinygo version
tinygo version 0.20.0 linux/amd64 (using go version go1.17.2 and LLVM version 11.0.0)
$ tinygo test -c -v
Killed
```
and with Go 1.16
```
$ tinygo version
tinygo version 0.20.0 linux/amd64 (using go version go1.16.9 and LLVM version 11.0.0)
$ tinygo test -c -v
Killed
```
The tests compile & run perfectly fine with both Go versions mentioned.

**Comment by dgryski** [comment]
This is solved by https://github.com/tinygo-org/tinygo/pull/2001

**Comment by deadprogram** [comment]
I think the request was fulfilled in the new release, so closing. Please reopen if needed. Thanks!
