### ISSUE TITLE
pin.Get in machine.PinOutput mode inconsistent between boards

### ISSUE THREAD

**Issue by floriaanpost** [tinygo-org/tinygo#2191]
I found an inconsistency between an Arduino Uno and the Adafruit Feather nRF52840. The blink function below shows alternately false and true on the Arduino Uno, and always shows false for the Adafruit Feather nRF52840 (and the LED does not blink)

```go
func blink(led machine.Pin, delay time.Duration) {
    for {
        led.Set(!led.Get())
        println(led.Get())
        time.Sleep(delay)
      }
}
```

Is this the expected behavior?

Maybe pin.Get should be something like below for the Adafruit Feather nRF52840?

```go
// Get returns the current value of a GPIO pin.
func (p Pin) Get() bool {
	port, pin := p.getPortPin()
        if (/* check if pin is an output*/) {
	    return (port.OUT.Get()>>pin)&1 != 0
        }
        return (port.IN.Get()>>pin)&1 != 0
}
```

**Comment by aykevl** [comment]
Actually this is a matter of missing documentation. The `Get` function is only valid when the pin is configured as an input. This is described in the [machine package documentation](https://tinygo.org/docs/reference/machine/#gpio):

> Get the input state of a pin. The returned value indicates whether the pin is low or high: true means high and false means low. Get may only be called when the pin has been configured as an input.

However, this is not always included in the documentation that's part of the source code. So the documentation should be improved here.
(Supporting this case is indeed possible as you describe, but that would also mean that every `Get` call becomes a bit slower which might not be a good idea).

I believe the fact that it works on AVR is just a coincidence.

**Comment by aykevl** [comment]
Actually, all chips I tested support reading the output back. In fact the nrf series chips are the only ones that needed a small change to support this behavior. PR here: https://github.com/tinygo-org/tinygo/pull/2192

**Comment by kenbell** [comment]
Fix was merged some time ago, so looks like this can be closed.
