### ISSUE TITLE
WASI gc=leaking is destroying preopened paths

### ISSUE THREAD

**Issue by fritzbauer** [tinygo-org/tinygo#2199]
I experience a Permission denied error when attempting to create a file using cgo and fopen(). When using WASI to access the filesystem, you need to specify preopens (wasmer-js) or --mapdir= (wasmer & wasmtime).

It seems that the preopens are processed and stored before initHeap() is called.
Since the -gc=leaking is resetting the heapptr when initHeap() is called, it appears that the preopen data is overwritten with the following allocations. 

**Idea to fix**
I do not know the reason why heapptr is set to heapStart again, therefore I shied back to create a PR. My initial idea would be to just align the heapptr, but do not set it back to heapStart.

**Technical details**
Here is the output of the failed run:
```
$ tinygo build -o tinyWrite2_dbg.wasm -opt=0 -target wasi -gc=leaking
$ wasmer --mapdir=/::. tinyWrite2_dbg.wasm 
#Alloc: <size> <address>
Alloc:  3 0x00011430
Alloc:  32 0x00011440
Alloc:  1 0x00011460
Alloc:  2 0x00011470
Alloc:  1 0x00011480
Init heap
Alloc:  4 0x00011430
Alloc:  4 0x00011440
Alloc:  4 0x00011450
Alloc:  20 0x00011460
Alloc:  8 0x00011480
Alloc:  8 0x00011490
Alloc:  10 0x000114a0
Could not create file.: Permission denied
```
The two allocations before initHeap() is called are the ones used to store the mapdir, which can be seen when using a longer value:
```
#Mapping a longer path will alloc 39 & 38 bytes instead of 2 & 1.
$ wasmer --mapdir=/my/longer/path/to/find/the/allocation::. tinyWrite2_dbg.wasm 
Alloc:  3 0x00011430
Alloc:  32 0x00011440
Alloc:  1 0x00011460
Alloc:  39 0x00011470
Alloc:  38 0x000114a0
Init heap
Alloc:  4 0x00011430
Alloc:  4 0x00011440
Alloc:  4 0x00011450
Alloc:  20 0x00011460
Alloc:  8 0x00011480
Alloc:  8 0x00011490
Alloc:  10 0x000114a0
Could not create file.: Permission denied

```
Only when leaving the heapptr untouched in initHead() the file can be created successfully:
```
# Do not modify heapptr in initHeap()
$ wasmer --mapdir=/::. tinyWrite2_dbg.wasm 
Alloc:  3 0x00011430
Alloc:  32 0x00011440
Alloc:  1 0x00011460
Alloc:  2 0x00011470
Alloc:  1 0x00011480
Init heap
Alloc:  4 0x00011490
Alloc:  4 0x000114a0
Alloc:  4 0x000114b0
Alloc:  20 0x000114c0
Alloc:  8 0x000114e0
Alloc:  8 0x000114f0
Alloc:  10 0x00011500
Alloc:  1144 0x00011510
File created and saved successfully.
```
**Avoid this trap when playing with preopens/mapdir's:**
The issue [Operations fail when the root (/) is mapped to a directory](https://github.com/wasmerio/wasmer/issues/2098) has been reported in the wasmer project. I experienced this problem when using the wasi-libc which is shipped with tinygo right now. 
When using the wasi-libc from wasi-sdk-12.0 this issue does not occur anymore.
You can also avoid this issue by mapping any other directory than root /.

**Comment by aykevl** [comment]
> It seems that the preopens are processed and stored before initHeap() is called.

This is the bug. The `alloc` function (and therefore `malloc`) may never be called before `initHeap` is called.
You could try to move the `__wasm_call_ctors` call into the `init` function, which is run after the initializers are run (and in fact, that seems like the more appropriate location to run C initializers).

**Comment by fritzbauer** [comment]
This works like a charm! Will submit a PR on monday.

**Comment by fritzbauer** [comment]
Fixed with PR above
