### ISSUE TITLE
uses -size parameter to build wasm error: bad magic number

### ISSUE THREAD

**Issue by ttttmr** [tinygo-org/tinygo#2211]
❯ tinygo version
tinygo version 0.20.0 darwin/amd64 (using go version go1.16.5 and LLVM version 11.0.0)
❯ tinygo build -o main.wasm -target wasm .
❯ tinygo build -o main.wasm -target wasm -size full .
error: bad magic number '[0 97 115 109]' in record at byte 0x0
❯ tinygo build -o main.wasm -target wasm -size short .
error: bad magic number '[0 97 115 109]' in record at byte 0x0

I got the same error with the docker version of 0.20.0

**Comment by aykevl** [comment]
This is not yet supported. I intend to add support in the future.

Meanwhile, I have worked on improving support for `-size=full`: https://github.com/tinygo-org/tinygo/pull/2212. After that PR is merged, I can look into adding support for the WebAssembly binary format.

**Comment by aykevl** [comment]
See: https://github.com/tinygo-org/tinygo/pull/2213

**Comment by aykevl** [comment]
This has been fixed in the latest release: 0.21.0.
