### ISSUE TITLE
tinygo error: Linking globals named 'malloc': symbol multiply defined!

### ISSUE THREAD

**Issue by TotTheMax** [tinygo-org/tinygo#2243]
tinygo build 

tinygo error: Linking globals named 'malloc': symbol multiply defined!

version:
╰─$ tinygo version                                                                                                                
tinygo version 0.20.0 darwin/amd64 (using go version go1.17 and LLVM version 11.0.0)
wasme --version
wasme version 0.0.32

**Comment by TotTheMax** [comment]
![image](https://user-images.githubusercontent.com/38995438/140854265-b9613edc-1f7b-4a2d-b2c5-e2265117198c.png)

**Comment by aykevl** [comment]
Can you provide a reproducer? I can't investigate this issue without looking at the source code.

**Comment by deadprogram** [comment]
Closing due to age and lack of info.
