### ISSUE TITLE
I2C eeprom

### ISSUE THREAD

**Issue by ghost** [tinygo-org/tinygo#2263]
Hi
Is it possible to use i2c with eeprom ?
I2c.Tx function specifies (deviceAddr, writeBuffer, readByffer)

While eeprom requires
(deviceAddr, eepromAddr, ........)

Or would i just include the eeprom Addr as part of the write buffer ?

Thanks

**Comment by deadprogram** [comment]
Perhaps you are looking for https://github.com/tinygo-org/drivers/tree/release/at24cx?

**Comment by ghost** [comment]
Thanks alot, that will more than suffice!
