### ISSUE TITLE
can i use nrf51822 DK?

### ISSUE THREAD

**Issue by bestony** [tinygo-org/tinygo#229]
I notice here a 'BBC Micro:bit' support.

The Micro:bit use `nrf51822`, So , it means i can use nrf51822?

**Comment by deadprogram** [comment]
Hello @bestony the processor support is in TinyGo already for that, but the board support like pin mappings would need to be added for the PCA10028, which I assume is the dev kit you want to use here.

Please take a look at https://github.com/tinygo-org/tinygo/wiki/Adding-a-new-board#adding-a-new-board for information about how to do this.

We would be very happy to receive a PR that added a new board definition for this hardware.

**Comment by deadprogram** [comment]
Closing due to age. Thanks to everyone!
