### ISSUE TITLE
nucleo-l432kc, nucleo-l031k6, nucleo-f722ze seemingly lack the ability to change I2C frequency

### ISSUE THREAD

**Issue by rayozzie** [tinygo-org/tinygo#2311]
For both of these boards there are consts for TWI_FREQ, however the I2CConfig type has no Frequency field and thus it is not apparent how to configure bus speed for I2C.

https://tinygo.org/docs/reference/microcontrollers/machine/nucleo-l432kc/
https://tinygo.org/docs/reference/microcontrollers/machine/nucleo-l031k6/
https://tinygo.org/docs/reference/microcontrollers/machine/nucleo-f722ze

Thank you for your consideration of this fix/enhancement.

**Comment by deadprogram** [comment]
@kenbell I was looking at this briefly, and saw that we are using some constant values based on clock speed generated by STM32CubeMX. We could keep doing this as an interim solution if we can also generate those 4 values for the typical standard and fast mode speeds for each of the boards this is currently being used for.

I was looking at STM32CubeMX but it was not immediately obvious how to regenerate those values. Could you show me how you did that and/or help out to generate values for the various `getFreqRange()` functions?

**Comment by kenbell** [comment]
@deadprogram you first have to set the peripheral clock to the correct MHz in the 'Clock Configuration' tab.  For L432, it's this (80MHz on PCLK1):
![image](https://github.com/tinygo-org/tinygo/assets/509378/8daa9f00-192e-4836-8837-fa65414b68e8)

Resolve the clock configuration.

Then enable I2C1 peripheral, you'll now see in gray the magic value in the 'timing' setting (0x10909CEC in this case for 100kHz standard mode):
![image](https://github.com/tinygo-org/tinygo/assets/509378/41a05e61-c5ae-4146-8650-043fa43b6779)

**Comment by deadprogram** [comment]
Thanks @kenbell that is exactly what I was looking for. PR coming later.

**Comment by deadprogram** [comment]
Merged into `dev`, tagged to close on next release. Thanks @rayozzie for report and to @kenbell for helping me out.

**Comment by deadprogram** [comment]
This was released with `v0.32.0` so now closing. Thank you everyone!
