### ISSUE TITLE
issue with maps indexed by float64? golang/geo/s2 TestCellFaces fails

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2339]
```
--- FAIL: TestCellFaces
    edge (0.000000000000000000000000, 0.000000000000000000000000, 0.000000000000000000000000) counts wrong, got 1, want 2
    edge (0.000000000000000000000000, 0.000000000000000000000000, 0.000000000000000000000000) counts wrong, got 1, want 2
    edge (0.000000000000000000000000, 0.000000000000000000000000, 0.000000000000000000000000) counts wrong, got 1, want 2
    edge (0.000000000000000000000000, 0.000000000000000000000000, 0.000000000000000000000000) counts wrong, got 1, want 2
```

These are entries from a map indexed by a struct.   Here is another program that demonstrates the map-of-structs problem, although I'm not 100% certain it's the same issue as the failing test.

```
package main

func main() {
        m := make(map[float64]int)
        m[0]++
        for k, v := range m {
                println(k, v)
        }
}
```

On tinygo, this shows that the map key does not have the expected value.
```
~/go/src/github.com/fastly/dgryski/wasmplay/cmd/structmap $ go run main.go
+0.000000e+000 1
~/go/src/github.com/fastly/dgryski/wasmplay/cmd/structmap $ ~/go/src/github.com/tinygo-org/tinygo/build/tinygo run main.go
+1.383384e-322 1
```

**Comment by dgryski** [comment]
Update: seems like the value that's coming out is the `interface{}` type code (`0x1c`).  The float64 `reflect.Kind` is 14.  Type codes for basic types are that type shifted over one bit, which for float64 makes it 28 == 0x1c.  Using https://evanw.github.io/float-toy/ (or `math.Frombits`) we can see that for a float64, the bit pattern `0x1c` is indeed `+1.383384e-322`.

**Comment by aykevl** [comment]
See https://github.com/tinygo-org/tinygo/pull/2353 which should fix this bug.
