### ISSUE TITLE
tinygo test -target wasi os fails with unknown import env::chmod

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2369]
With today's dev on mac:

```
$ tinygo test os
ok  	os	0.235s
$ tinygo test -target wasi os
Error: failed to run main module `/var/folders/v0/0k9hwftd29b18z9z7s2g2sfc0000gn/T/tinygo491621975/main`

Caused by:
    0: failed to instantiate "/var/folders/v0/0k9hwftd29b18z9z7s2g2sfc0000gn/T/tinygo491621975/main"
    1: unknown import: `env::chmod` has not been defined
FAIL	os	0.032s
```

**Comment by aykevl** [comment]
Apparently wasi-libc doesn't define `chmod`.

**Comment by dkegel-fastly** [comment]
I gather wasi-filesystem is the part of wasi that defines things like chmod, and hadn't gotten around to that function yet?

https://github.com/WebAssembly/WASI/blob/main/phases/ephemeral/docs.md mentioned but did not define a function path_permissions_set.

https://github.com/WebAssembly/wasi-filesystem/pull/36 appears to move a bunch of cheese, but interestingly defines a function change_file_permissions_at, so maybe they're getting around to it slowly.

**Comment by dkegel-fastly** [comment]
I think this can be closed.  tinygo test -target wasi os gets past this.
