### ISSUE TITLE
Unable to build Dockerfile attempting to use release v0.4.1

### ISSUE THREAD

**Issue by DazWilkin** [tinygo-org/tinygo#239]
I'd had problems installing LLVM correctly on a Linux workstation and so use the Docker image.

Would like to try this now v0.4.1 (#235) but there's no accompanying image.

Self-building the image appears to not work for me :-(

I'm unable to `go get -u github.com/tinygo-org/tinygo` because my local LLVM is not working.

I tried:
```
git clone git@github.com:tinygo-org/tinygo $GOPATH/src/github.com/tinygo-org/tinygo
cd $GOPATH/src/github.com/tinygo-org/tinygo
docker build --tag=tinygo --file=Dockerfile .
```
But this fails when I use this local image:
```
docker run \
--rm --interactive --tty \
--volume=${PWD}/src:/src --volume=${PWD}/bin:/bin \
tinygo tinygo build -o /bin/arduino.hex -target=arduino \
/src/github.com/DazWilkin/tinygo/arduino/main.go
../usr/local/go/src/syscall/js/func.go:74:3: todo: unknown expression: select blocking []
```
but succeeds with the existing deployed image:
```
docker run \
--rm --interactive --tty \
--volume=${PWD}/src:/src --volume=${PWD}/bin:/bin \
tinygo/tinygo tinygo build -o /bin/arduino.hex -target=arduino \
/src/github.com/DazWilkin/tinygo/arduino/main.go
```

Additionally:
- Please consider automating Docker image builds w/ releases

**Comment by deadprogram** [comment]
The latest docker image is from the 0.4.1 build.

**Comment by DazWilkin** [comment]
Will double-check but:

![image](https://user-images.githubusercontent.com/1022400/54452666-efd1d380-4712-11e9-8f11-8289e7b8e72e.png)

**Comment by DazWilkin** [comment]
Hmmm :-)

![image](https://user-images.githubusercontent.com/1022400/54452729-1263ec80-4713-11e9-96ab-19f9ddbf3ff7.png)

**Comment by deadprogram** [comment]
I agree that we need to get the auto-builds working correctly. They were doing do, but something changed when we switch over to the TinyGo github org, and they have been failing ever since.

I have been doing a manual build/push of Docker image for each release, until we get it working in a automated way.

**Comment by DazWilkin** [comment]
My apologies.

The microbit code *does* now compile.

Thank you!

**Comment by deadprogram** [comment]
OK, good. No apologies required, you were one of the first people to report, which made it a lot easier to track down. Thanks for helping.

**Comment by DazWilkin** [comment]
Thanks for building us such an interesting project!
