### ISSUE TITLE
minor: tag Docker images by release and|or commit

### ISSUE THREAD

**Issue by DazWilkin** [tinygo-org/tinygo#240]
It would be helpful to have a set of images for all major releases or commits.

`latest` (alone) is challenging and e.g. `tinygo:0.4.1` has a useful specificity

![image](https://user-images.githubusercontent.com/1022400/54453451-9074c300-4714-11e9-8629-536d1224573d.png)

**Comment by deadprogram** [comment]
Good point. Done.
