### ISSUE TITLE
wasmtest: TestChan failing randomly in CI

### ISSUE THREAD

**Issue by niaow** [tinygo-org/tinygo#2400]
It seems that TestChan is failing occasionally in CI under `assert-test-linux` due to a timeout.
This could just be a timeout (10 seconds does seem like it should be plenty though) or it could be a bug.

**Comment by niaow** [comment]
I am somewhat unsure of what is going on. No approach I try seems to be able to get this test (the section inside the timeout) to take over 250 ms locally (running it pinned to a single core to try to CPU-starve it, running it repeatedly, etc.).

**Comment by zdima** [comment]
I have PR #2431 (draft) that I believe will address this issue. 
Is there a way to trigger CI without making additional commits or better run “reduced” test on CI environment with “make wasmtest” only?

**Comment by deadprogram** [comment]
> Is there a way to trigger CI without making additional commits

I can help you with that. I will retrigger this right now as another test. Also please see my comments.

**Comment by dkegel-fastly** [comment]
This is happening a lot still.

**Comment by deadprogram** [comment]
I think this was addressed some time ago. Now closing, please reopen if needed. Thanks everyone!
