### ISSUE TITLE
testing flags (testVerbose/testShort/testRunRegex) should move to config.TestConfig

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2406]
I didn't see this struct was there when I added them.  The struct even has a TODO to add these flags there already.

**Comment by aykevl** [comment]
To be honest, I'd say that we don't need a separate struct for this. Just put everything directly in `compileopts.Config`. But that's just my personal opinion (I'm not going to bikeshed about this).

**Comment by galamdring** [comment]
Should this be closed with the related PR merged?

**Comment by dgryski** [comment]
The related PR is just me reminding myself in a comment that I still need to do this.

**Comment by galamdring** [comment]
Understood. Just looking for where I can start contributing.

**Comment by aykevl** [comment]
Looks like this is fixed in the dev branch.
