### ISSUE TITLE
As script run and build window nt kernel

### ISSUE THREAD

**Issue by ddkwork** [tinygo-org/tinygo#2425]
Hello, how to use this language As script run and build window nt kernel driver

**Comment by aykevl** [comment]
> As script run

You can use `tinygo run` for this, but it's a bit slow.

> build window nt kernel driver

Technically possible, but probably a lot of work. We don't support anything like that yet.

**Comment by dkegel-fastly** [comment]
Are you looking for a nice language to write kernel drivers in?
Rust is one candidate, see e.g. https://not-matthias.github.io/kernel-driver-with-rust/
