### ISSUE TITLE
make config make: *** No rule to make target 'config'.  Stop.

### ISSUE THREAD

**Issue by toffentoffen** [tinygo-org/tinygo#244]
Following the (installation steps)[https://tinygo.org/getting-started/installation/] tells you that:

> It means something is wrong with your LLVM installation. Make sure LLVM 7 is installed (Debian package llvm-7-dev). If it still doesn’t work, you can try running:
```
cd $GOPATH/src/github.com/tinygo-org/go-llvm
make config
```
But there is no make target called config.
I've checked Makefile's history and could fine any trace of a target called config.

Did it ever exist?

**Comment by aykevl** [comment]
Did you run `make config` in `$GOPATH/src/github.com/tinygo-org/go-llvm`? It must be run in the directory of this dependency, not in the tinygo directory.

**Comment by toffentoffen** [comment]
😂 OMG, sorry! I don't even know how to copy paste
