### ISSUE TITLE
github.com/pkg/errors build fails with "type *runtime.Func has no field or method FileLine"

### ISSUE THREAD

**Issue by lz1998** [tinygo-org/tinygo#2445]
```bash
../../../../../../pkg/mod/github.com/pkg/errors@v0.9.1/stack.go:39:16: fn.FileLine undefined (type *runtime.Func has no field or method FileLine)
```

**Comment by dgryski** [comment]
We can easily add these fields so this package compiles, but they will be stubbed out and not contain the true values.

**Comment by dkegel-fastly** [comment]
What package were you trying to build?

**Comment by lz1998** [comment]
> What package were you trying to build?

errors.New

errors.Wrapf

**Comment by dkegel-fastly** [comment]
I can add stubs for those this week if nobody beats me to it...

**Comment by dankegel** [comment]
Try the dev branch now...

**Comment by deadprogram** [comment]
Closing since it appears to have been addressed. Please reopen if needed.
