### ISSUE TITLE
Invalid bitcast LLVM ERROR: Broken function

### ISSUE THREAD

**Issue by BoskyWSMFN** [tinygo-org/tinygo#2456]
Hello!
Found an issue using coroutines with avr:
running following command
``tinygo build -gc=conservative -scheduler=coroutines -target=arduino -o ./main.hex ./main.go``
with main.go containing
```
package main

import "time"

func yetAnotherAsyncFunc() {
	for {
		time.Sleep(time.Second)
	}
}

func main() {
	go yetAnotherAsyncFunc()
	println("Hello!")
}
```
leads to this error:
```
Invalid bitcast
i8* bitcast (void (i8*, i8*) addrspace(1)* @main.yetAnotherAsyncFunc to i8*)
LLVM ERROR: Broken function
SIGABRT: abort
PC=0x7fa581a50fbb m=5 sigcode=18446744073709551610
```
However I managed to build this code with commenting the `import` section.

Thank you and happy holidays!

**Comment by dgryski** [comment]
Note that coroutines are buggy and are being removed:
https://github.com/tinygo-org/tinygo/issues/2174
https://github.com/tinygo-org/tinygo/pull/2448

**Comment by BoskyWSMFN** [comment]
Thank you for the information! Didn't read PRs yet.
Since coroutines are being removed is there a "tiny-go" way to use go routines with AVR MCUs? I couldn't manage the tasks scheduler work unfortunately.

**Comment by niaow** [comment]
The `tasks` scheduler is supposed to work. What issue did you run into with it?

**Comment by niaow** [comment]
One thing to note with that program you provided is that Go considers the program "done" as soon as `main` exits. As such, that program will terminate as soon as it finishes printing `Hello!`.

**Comment by BoskyWSMFN** [comment]
> The `tasks` scheduler is supposed to work. What issue did you run into with it?

Blinking user LED on Mega and Nano boards without any other signs of getting to `main`. For example - the code I provided above.



> One thing to note with that program you provided is that Go considers the program "done" as soon as `main` exits. As such, that program will terminate as soon as it finishes printing `Hello!`.

And `main` should never exit, yes.

Oh, Happy New Year! =)

**Comment by niaow** [comment]
> Blinking user LED on Mega and Nano boards without any other signs of getting to main. For example - the code I provided above.

Hmm. . . I don't have a Mega/Nano to test with, but it seems to have worked on my Uno - it prints hello and stops correctly.
Can you provide your blinking code (the provided code does not blink)?

**Comment by BoskyWSMFN** [comment]
> Hmm. . . I don't have a Mega/Nano to test with, but it seems to have worked on my Uno - it prints hello and stops correctly.
> Can you provide your blinking code (the provided code does not blink).

Well... The code above does blink on my mega. Tested just now. Looks like some kind of error code but I can't find anything.
May be there is an issue with a bootloader and fuses...

**Comment by niaow** [comment]
Oh, I see. I guess I just misunderstood what you were saying.

**Comment by niaow** [comment]
Did you find the problem?

**Comment by BoskyWSMFN** [comment]
> Did you find the problem?

Not yet. I'll try to later and reopen this issue when there is something to show.
