### ISSUE TITLE
runtime (avr): timer code fails with -opt=1 or during init()

### ISSUE THREAD

**Issue by niaow** [tinygo-org/tinygo#2464]
When debugging `testdata/goroutine.go`, I came up with this minimal test case (the loop isn't necessary, but it makes things easier to test on the actual hardware):
```
package main

import "time"

func init() {
        time.Sleep(time.Millisecond)
}

func main() {
        for {
                println("hello")
        }
}
```

If you check the scheduler output, the chip goes to sleep at which point simavr recognizes that it cannot wake up. This also reproduced on real hardware (my Arduino Uno). It reproduces with or without a scheduler.

Another way to replicate this is to run `examples/blinky1` with `-opt=1`.

**Comment by aykevl** [comment]
I think I know the cause, will make a PR now.

**Comment by aykevl** [comment]
Fix: https://github.com/tinygo-org/tinygo/pull/2470
