### ISSUE TITLE
assert-test-linux "test stdlib packages" reports success despite test failing to link?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2466]
In the CI results for https://github.com/tinygo-org/tinygo/pull/2462, 
in the assert-test-linux CI run, 
in the "test stdlib packages" step, there is an error linking one test, but the build does not terminate.

Log fragment:
```
tinygo:ld.lld: error: undefined symbol: syscall.RawSyscall
>>> referenced by zsyscall_linux_amd64.go:1661 (/opt/hostedtoolcache/go/1.17.5/x64/src/syscall/zsyscall_linux_amd64.go:1661)
>>>               /tmp/tinygo2693500925/main.o:(os_test.TestSmokePipe)
failed to run tool: ld.lld
```

This bug isn't about the link failure; it's about the test suite passing despite the link failure.

**Comment by niaow** [comment]
I think I see what the problem is here.

**Comment by dkegel-fastly** [comment]
Thanks!  Filed https://github.com/tinygo-org/tinygo/issues/2474 for the missing syscall magic.
