### ISSUE TITLE
TestClearenv flaky?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2483]
I've seen this error twice now:

```
--- FAIL: TestClearenv
    Setenv("", "\x00\x00\x00\x00\x00\x00P\x00\x00\x00\x00\x00") failed during reset: setenv: errno 22
```

This time it was on my mac, can't remember where it was last time.

**Comment by dkegel-fastly** [comment]
This is now my most frequent flaky test.

**Comment by dgryski** [comment]
This is bizarre that this test is flaky.  Almost points to some bigger underlying issue.  I'll maybe take a look.

**Comment by dkegel-fastly** [comment]
The test expects the return value of Environ() to remain valid (i.e. noncorrupt) after the environment is modified, as on upstream go, but it is disappointed because Tinygo does not copy the environment.  Instead, Environ() contains live pointers into the real environment, so it goes kerblooie if you modify the environment and try to use the results from an old call to Environ().

env.go needs a bit of work.

**Comment by dankegel** [comment]
Fixed by https://github.com/tinygo-org/tinygo/pull/2647
