### ISSUE TITLE
TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function

### ISSUE THREAD

**Issue by tuananh** [tinygo-org/tinygo#2484]
i'm just testing the example here at https://github.com/tinygo-org/tinygo/tree/master/src/examples/wasm/export and i got this error when browsing with firefox/chrome

```
TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function
```

tinygo version is 

```
tinygo version 0.21.0 linux/amd64 (using go version go1.17 and LLVM version 11.0.0)
```

**Comment by Mahmoud02** [comment]
me too

**Comment by bluntelk** [comment]
ahh, figured it out

you want to copy the TINYGO wasm_exec.js - not the golang one
```cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js wasm_exec_tiny.js```
