### ISSUE TITLE
Enhancement request: export WASM from multiple files

### ISSUE THREAD

**Issue by jzabinski-dolios** [tinygo-org/tinygo#2540]
If I have a setup like this:
```
./lib
./lib/a.go
./main.go
```

And `a.go` has a function:

```
package balloons
...
func Add(x,y int) int {
  return x+y
}
```

I can consume that function in `main.go`:
```
package main
import (
  lib "projectname/balloons"
)
...
func addThese(x,y int) int {
  return lib.Add(x,y)
}
```

But assuming that `main.go` has something to export to WASM, I can't also export `balloons.add` to WASM directly using the `export` keyword. That is, in `a.go`:
```
package balloons
...
//export add
func add(x,y int) int {
  return x+y
}
```

TinyGo expects all exported functions to appear in a single path/file. I can work around the lack of functionality by making a shell function somewhere in `main`:

```
package main
import (
  lib "projectname/balloons"
)
...

//export add
func addShell(x, y int) int {
   return lib.add(x,y)
}
```

It would be more convenient to use `export` directly in the library, and instruct TinyGo to traverse a directory path, hunting for standalone exported functions to compile/link into a single WASM file.

**Comment by aykevl** [comment]
> TinyGo expects all exported functions to appear in a single path/file. I can work around the lack of functionality by making a shell function somewhere in `main`:

TinyGo doesn't work like this. All `//export` lines are processed, not just the ones in the main package. So I'm not sure why it doesn't work for you.

Are you sure you compiled the _package_, not a Go file? The normal way to build is by specifying the path to the main package, not to a particular .go file.

**Comment by jzabinski-dolios** [comment]
Thanks, and never mind: this seems to work as intended. (My setup had a toolchain issue. I'll be sure to reproduce isolated issues using a more standard toolchain next time.)
