### ISSUE TITLE
 reflect.DeepEqual returns an incorrect result on wasm in one case

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2553]
Comparing two deserialized json structs with reflect.DeepEqual compiled and ran on tinygo, and even produced correct results when run on darwin, but said two equal structs were not equal on wasm.

I worked around it successfully by comparing the output of fmt.Sprintf("%v", foo).

I will add a test case when I get a chance.

**Comment by dgryski** [comment]
Do you have a test case for this yet?

**Comment by dkegel-fastly** [comment]
Nope.  I do see the spot that failed, but it no longer fails when using reflect, so perhaps it was cured by tincture of time.
