### ISSUE TITLE
too many stale branches make selecting dev branch harder in github ui

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2557]
This is an awfully small point, but every time I look at tinygo on github, I have to search for the dev branch.

This is fine, but it would be neat if the dev branch was in the first few branches in the pulldown, so devs don't have to type dev to find that branch. 

That would mean deleting a dozen or so of the twenty stale branches that come before 'dev' alphabetically.

**Comment by deadprogram** [comment]
I just deleted a bunch of my own stale or simply dead branch of my own.

Perhaps @aykevl would like to do the same? :smiley_cat:

**Comment by dgryski** [comment]
Ping @aykevl

**Comment by deadprogram** [comment]
Closing since this is an ongoing task... :smiley_cat:
