### ISSUE TITLE
Minor inaccuracy in WASM examples README

### ISSUE THREAD

**Issue by jzabinski-dolios** [tinygo-org/tinygo#2568]
The README says:

"This examples folder contains two examples that can be built using `make`:
`make export`
`make main`"

 Looking in [Makefile](https://github.com/tinygo-org/tinygo/blob/release/src/examples/wasm/Makefile), it looks like `make` instructions are included for ALL examples (`callback`, `slices`, etc). The folder does include the listed examples, but from the README, developers might assume that `make` instructions for other examples do not exist.

**Comment by codefromthecrypt** [comment]
I agree #3137 should fix this.
