### ISSUE TITLE
DotStar support for the itsybitsy m0

### ISSUE THREAD

**Issue by Elara6331** [tinygo-org/tinygo#2591]
The itsybitsy m0 and some other adafruit boards have an integrated DotStar LED. There is currently no support for it in TinyGo as far as I can tell. 

Here is the arduino library for DotStar LEDs: https://github.com/adafruit/Adafruit_DotStar

**Comment by deadprogram** [comment]
The DotStar is actually an APA102. Please see https://github.com/tinygo-org/drivers/tree/release/examples/apa102

**Comment by Elara6331** [comment]
That should probably be documented somewhere, or at least have a pin alias for it similar to `machine.NEOPIXEL`.

**Comment by deadprogram** [comment]
Perhaps you would like to submit a PR to the TinyGo site? See https://github.com/tinygo-org/tinygo-site

**Comment by Elara6331** [comment]
> Perhaps you would like to submit a PR to the TinyGo site? See https://github.com/tinygo-org/tinygo-site

Yes, thank you, I can do that. Where would be a good place to document this? Would I put it in the microcontrollers page for all the boards with a DotStar? Or maybe it's better to make a dedicated page for DotStar.

**Comment by deadprogram** [comment]
> Would I put it in the microcontrollers page for all the boards with a DotStar?

I would suggest add to each, with something in the "Notes" section.

https://github.com/tinygo-org/tinygo-site/blob/release/content/docs/reference/microcontrollers/itsybitsy-m0.md#notes

**Comment by Elara6331** [comment]
Closed since the PR was merged.
