### ISSUE TITLE
fmt.Scanf()  does not work.

### ISSUE THREAD

**Issue by bmentink** [tinygo-org/tinygo#2597]
I get a  runtime "panic: (319:0x20001970)" whenever I try to use Scanf in the form:

fmt.Scanf("%s", &command)

Is it implemented yet?

**Comment by deadprogram** [comment]
What target are you compiling for @bmentink and can you please show a bit more of your code?

**Comment by bmentink** [comment]
@deadprogram  Hi Ron,

I am compiling for the RaspberryPi pico target. Code is part of a much larger project(sensorless BLDC motor drive), the relevant part is:

import (
 "fmt"
)

var command, data string

println("Enter command:")
fmt.Scanf("%s %s", &command, &data)		
fmt.Printf("Command = %s, Data = %s\r\n", command, data)

EDIT: A single  fmt.Scanf("%s", &command)  .. does the same panic ...
Also, the form fmt.Scan(&command) causes the same panic.

Cheers,

**Comment by dgryski** [comment]
Does the pico have an `os.Stdin`?  `fmt.Scanf` works for me on native but ends up panicing on wasi due to EOF.  I wonder if its a similar issue.

**Comment by bmentink** [comment]
@dgryski  Yes, there is an `os.Stdin`

**Comment by bmentink** [comment]
@deadprogram 
Do you need any more info to progress this?

**Comment by deadprogram** [comment]
> Yes, there is an os.Stdin

On the rp2040? Hmm, I am not too sure that is true. Have to look into that.

**Comment by bmentink** [comment]
@deadprogram 
You might be right. I just assumed there was because the TinyGo plugin/Pico target (VS Code ) gave me the popup prompt for os.Stdin when I started typing it ....

**Comment by bmentink** [comment]
I am implementing a brushless BLDC motor drive as an excuse to test how feasible TinyGo is with coding for the RPi Pico. It seems I have run into the 1st road block, by not having a serial in. Serial  is essential for me, as I am controlling this drive over a Bluetooth->Serial connection. (Also PIO support would have been nice for this project as well, but have got around that with PWM drivers)

@deadprogram  .. any luck with looking into this ?

**Comment by deadprogram** [comment]
You do have serial in/out without any problem for example using the UART. What you do not have is any operating system to provide stdin. Hence why you cannot just use `fmt.Scanf()`.

See https://github.com/tinygo-org/tinygo/blob/release/src/examples/echo/echo.go for some ways to read/write to serial.

**Comment by bmentink** [comment]
So how come I have a fmt.Printf() but not a fmt.Scanf()?

**Comment by deadprogram** [comment]
Output is mapped so that `println()` can be implemented. Note I am not referring to `fmt.Println()` but just the lower level `println()`.

**Comment by bmentink** [comment]
`fmt.Printf()` works for me, haven't tried `fmt.Println`

**Comment by bmentink** [comment]
@deadprogram 
`fmt.Println`  works for me as well
`uart.Read()` works, but not sure how to make it read up to CR, instead it requires you to know how many characters you are expecting. Maybe I am not understanding the function correctly ..

I was doing something like the following to input a string.


input := make([]byte, 32)
	println("Type something:")
	for {
		if uart.Buffered() > 4 {
			uart.Read(input)
			println(string(input))
			break
		}
	}

It would return after 4 characters are typed and print the result  ..

EDIT: I ended up using `uart.ReadByte()` in a loop, to do it byte for byte.

**Comment by bmentink** [comment]
Upate:  `fmt.Fscanf()` creates a panic as well, I used it in the following way:

func parseSerialCommands() {
	var command, data string
	for {
		in_string := ReadSerialCommand() // Returns a string
		r := strings.NewReader(in_string)
		fmt.Fscanf(r, "%s %s", command, data)
		fmt.Printf("Command=%s Data=%s\r\n", command, data)
	}
}

**Comment by bmentink** [comment]
`fmt.Sscanf(in_string, "%s %s", command, data)` produces a panic for me as well.

I would have thought that this should work, as it's not using stdin ...

**Comment by sago35** [comment]
@bmentink 
You can use `fmt.Fscanf()` like below.

```go
fmt.Fscanf(uart, "%s", &command)
```

**Comment by sago35** [comment]
Stdin, etc. do not work on the baremetal target at this time.
But I feel like it's time to get moving.
I'll work on it later.

https://github.com/tinygo-org/tinygo/blob/3883550c446fc8b14115366284316290f3d3c4b1/src/os/file_other.go#L11-L15

**Comment by sago35** [comment]
PR created.
* #2625

**Comment by bmentink** [comment]
@sago35  Awesome!

**Comment by deadprogram** [comment]
Now closing as this feature was implemented quite a while back. Thanks everyone!
