### ISSUE TITLE
Executing functions from RAM

### ISSUE THREAD

**Issue by iamjackg** [tinygo-org/tinygo#2599]
I'm not very familiar with the internals of TinyGo, so forgive me if this doesn't make any sense.

Is there any way to declare that a function should be copied to RAM and executed from there? Similar to what `IRAM_ATTR` does in the ESP32 framework.

For more context, I'm asking because there are certain things on the Game Boy Advance that can only be done when running from RAM, like writing data to the flash chip that contains the ROM itself in rewriteable cartridges.

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
