### ISSUE TITLE
Windows release missing `wasm-opt.exe`

### ISSUE THREAD

**Issue by inkeliz** [tinygo-org/tinygo#2601]
The new version [22](https://github.com/tinygo-org/tinygo/releases/tag/v0.22.0), doesn't include `wasm-opt.exe` for Windows. That was included in the previous version (/bin/wasm-opt.exe).

-------------

That causes the following error:

```
error: could not find wasm-opt, set the WASMOPT environment variable to override
```

**Comment by stephane-moreau** [comment]
Just tested the tinygo version 0.22 on my dev environment every thing worked fine after installing binaryen version 105 from https://github.com/WebAssembly/binaryen/

**Comment by deadprogram** [comment]
`scoop install binaryen` will install the needed dependencies. Seems like we still need to update the docs with this info!

**Comment by zzxwill** [comment]
I fixed it by `sudo npm i wasm-opt -g`.

**Comment by deadprogram** [comment]
Closing since that was previously addressed. Thanks everyone!

**Comment by GageHowe** [comment]
> I fixed it by `sudo npm i wasm-opt -g`.

3 years later, this was the fix. Thanks!
