### ISSUE TITLE
Likely stackoverflows on golang/snappy.TestSmallCopy and google/licensecheck.init()

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2611]

**Comment by dgryski** [comment]
For snappy, the creation of a 32kb table overflows the stack which then clobbers globals.  When run with `gcAsserts=true`, we see that `metadataStart` has been set to `0` by the memset call.

**Comment by dgryski** [comment]
The `google/licensecheck` issue seems to be a regular stack-overflow.

**Comment by dgryski** [comment]
Fix for the snappy bug: https://github.com/tinygo-org/tinygo/pull/2628

**Comment by deadprogram** [comment]
Since this appears to have previously been addressed, I am closing. Please reopen if needed. Thank you!
