### ISSUE TITLE
Fedora package out of date

### ISSUE THREAD

**Issue by JuanM04** [tinygo-org/tinygo#2621]
The Fedora package is out to date. Today, the latest release is 0.22.0, while Fedora only hast 0.16.0

https://packages.fedoraproject.org/pkgs/tinygo/tinygo/

**Comment by deadprogram** [comment]
cc/ @QuLogic

**Comment by QuLogic** [comment]
Yes, I could not update without LLVM 12 support, but I just finished updating and fixing bugs last night. Updates for [F35](https://bodhi.fedoraproject.org/updates/FEDORA-2022-a1abd860fd) and [F34](https://bodhi.fedoraproject.org/updates/FEDORA-2022-898397147b) should be out soon.

**Comment by QuLogic** [comment]
The updates are now stable.
