### ISSUE TITLE
os.Environ() returns live environment rather than copy

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2646]
Tinygo's os tests include TestClearenv from upstream, but it fails frequently because it assumes os.Environ() returns a copy of the environment.
This is the case upstream, but in tinygo, it returns pointers to the live environment. Thus in tinygo, os.Environ() can go invalid the moment any environment variable is deleted.

We should probably disable TestClearenv until that's fixed, otherwise TestClearenv will continue to fail, causing spurious failures on unrelated changes in CI.

**Comment by dgryski** [comment]
Assuming we don't care about the extra memory pressure, this seems easy enough to fix.
