### ISSUE TITLE
No access to argv in target wasm?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2651]
On slack, Frank Rehwinkel asked (https://gophers.slack.com/archives/CDJD3SUP6/p1645591985252649):

_Hello. I'ld like to pass testing package arguments to node and the wasm_exec.js it runs to be picked up by the tinygo runtime. It seems the plumbing is almost there. ... it seems easy to use js.Global().Get("process").Get("argv") right in the proc.go init() for os.Args. As it is the only target I build, I can change it directly in my copy._ 

(Offhand, seems like the right place for that might be runtime/runtime_wasm_js.go, analogous to the init routine in runtimeruntime_wasm_wasi.go ?)

**Comment by deadprogram** [comment]
I think that https://github.com/tinygo-org/tinygo/pull/2780 addresses this request, does it not?

**Comment by dkegel-fastly** [comment]
Indeed, fixed.

**Comment by JounQin** [comment]
Hi, I'm not sure to understand, there is still no `go.argv` in `wasm_exec.js`, so how can I pass `argv` inside?

Sorry, I'm a bit newbie for go/tinygo.

---

Edit: This seems a different issue from the original one, or I should use method arguments instead in tinygo?
