### ISSUE TITLE
[wasm-problems] `copy` performance  is very very slow now.

### ISSUE THREAD

**Issue by cocotyty** [tinygo-org/tinygo#2656]
`copy` performance  is very very slow now.

How about use `memory.copy` instead of `$memcpy`?

https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-memory

**Comment by cocotyty** [comment]
After add a ` -llvm-features "+bulk-memory" ` flag , everything is ok here.

**Comment by aykevl** [comment]
Yes, we don't add that feature to support older (legacy) browsers and Node.js.
