### ISSUE TITLE
Support for reflect package in TinyGo

### ISSUE THREAD

**Issue by srikarrao** [tinygo-org/tinygo#2660]
Is the reflect package implemented in the latest version of Tinygo? I'm trying to decode the JSON in Go WASM and I have been getting the below error that `reflect.Type.NumMethod() is unimplemented`. I found a couple of issues reported earlier, I'm not sure if this is implemented. However, the [TinyGo's supported libs document](https://tinygo.org/docs/reference/lang-support/stdlib/) says it does allow importing `encoding/json` package.

**Previous Issues:**
https://github.com/tinygo-org/tinygo/pull/907
https://github.com/tinygo-org/tinygo/issues/575

**Versions used:**
```
> go version 
	go1.17.6 darwin/amd64
> tinygo version
	tinygo version 0.22.0 darwin/amd64 (using go version go1.17.6 and LLVM version 13.0.0)
> proxy-wasm-go-sdk version
	github.com/tetratelabs/proxy-wasm-go-sdk v0.16.0
```

**Error logs:**
```
proxy_1        | [2022-03-02 02:08:03.668][1][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: panic: unimplemented: (reflect.Type).NumMethod()
proxy_1        | [2022-03-02 02:08:03.668][1][error][wasm] [source/extensions/common/wasm/wasm_vm.cc:38] Function: proxy_on_tick failed: Uncaught RuntimeError: unreachable
proxy_1        | Proxy-Wasm plugin in-VM backtrace:
proxy_1        |   0:  0x170f - runtime._panic
proxy_1        |   1:  0x326d - (reflect.rawType).NumMethod
proxy_1        |   2:  0x6c23a - (*gopkg.in/square/go-jose.v2/json.decodeState).indirect
proxy_1        |   3:  0x696e5 - (*gopkg.in/square/go-jose.v2/json.decodeState).object
proxy_1        |   4:  0x687dc - (*gopkg.in/square/go-jose.v2/json.decodeState).value
proxy_1        |   5:  0x2af8b - gopkg.in/square/go-jose.v2/json.Unmarshal
proxy_1        |   6:  0x65be4 - (*gopkg.in/square/go-jose.v2.JSONWebKey).UnmarshalJSON
proxy_1        |   7:  0x64cef - proxy_on_tick

```

**Comment by dkegel-fastly** [comment]
Only a subset of reflect is implemented.    The supported package page is overdue to have a "passes tests" column, see
https://github.com/tinygo-org/tinygo-site/pull/110

Work is ongoing to improve reflect, see https://github.com/tinygo-org/tinygo/pull/2640.

**Comment by joeblew99** [comment]
Hey @srikarrao 

I know that https://github.com/buger/jsonparser is used with tinygo where you need to do JSON serialisation. 

You can find the entry point here at https://github.com/genjidb/genji.js/blob/master/scripts/buildgo.sh#L27, which compiles the golang code using tinygo to wasm

**Comment by johnkeates** [comment]
I ran into the same issue with `golang-jwt` in a WASI target, it tries to do a `(reflect.rawType).NumMethod` during JSON decoding and that panics because it's simply not there (yet).

Edit: I tried to see if this is something I can implement but it seems much more complicated than expected, especially when referring to to 'full' go reflect package and all the additional functions that it needs to get this method in rtype.

**Comment by dgryski** [comment]
`encoding/json` "should" be working once my last few reflect fixes are in.  Please let me know if you're still encountering issues.  I will try to test with golang-jwt.

**Comment by dgryski** [comment]
The next release of tinygo will support validating jwt:  (I had to disable the http listener example)

```
~/go/src/github.com/golang-jwt/jwt $ tinygo test -tags="purego noasm" -target=wasi
ok  	github.com/golang-jwt/jwt/v5	1.766s
```

**Comment by ricardbejarano** [comment]
Thank you so much! When can we expect that release to happen?

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!

**Comment by HarikrishnanBalagopal** [comment]
Is it possible to implement this? https://github.com/tinygo-org/tinygo/blob/731532cd2b6353b60b443343b51296ec0fafae09/src/reflect/type.go#L1012
Related to cobra library support https://github.com/tinygo-org/tinygo/issues/2704#issuecomment-1571999301

Using Go version 1.21.0 I am able to both compile and run the program that uses cobra CLI library.
```
$ go version
go version go1.21.0 darwin/arm64
$ GOOS=wasip1 GOARCH=wasm go build -o ./bin/foo.wasm
$ wasmer ./bin/foo.wasm
...........
```

With TinyGo I am able to compile but at runtime I get a panic
```
$ tinygo version
tinygo version 0.30.0 darwin/amd64 (using go version go1.21.0 and LLVM version 16.0.1)
$ CGO_ENABLED=0 tinygo build -o ./bin/foo.wasm -target=wasi .
$ wasmer ./bin/foo.wasm
panic: unimplemented: (reflect.Type).NumOut()
error: RuntimeError: unreachable
╰─▶ 1: RuntimeError: unreachable
make: *** [run] Error 1
```

**Comment by dkegel-fastly** [comment]
no necromancy, please :-). Filed https://github.com/tinygo-org/tinygo/issues/3943 for the cobra problem.
