### ISSUE TITLE
regression: "panic: runtime error: out of memory" error on some tests on target cortex-m-qemu

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2666]
Using the command

    tinygo test -v -target=cortex-m-qemu $foo

the following tests pass on both 0.21 and 0.23-dev:

container/heap
container/list
container/ring
encoding
hash/fnv
internal/itoa
reflect
testing/iotest
unicode/utf16

but the following tests pass on 0.21 and fail on 0.23-dev:

crypto/des
encoding/ascii85
encoding/hex
math/cmplx
net/mail
text/scanner
unicode/utf8

In all cases, the log shows "panic: runtime error: out of memory".

**Comment by dgryski** [comment]
The biggest pain I've had with trying to bisect between `release` and `dev` is the llvm version change.  Maybe start with 3a4e0c94e1cbad7227d311e652a0903b26e47273 and narrow down from there?  I can maybe take a look this evening once I get qemu set up.

**Comment by aykevl** [comment]
TinyGo still supports LLVM 11, so that shouldn't be a problem. Just compile with `go install -tags=llvm11`.

**Comment by dgryski** [comment]
Unsurprisingly,  bisecting gives a536ddcda8025233ad093f5f76d9d728ab67fa3f which brought in the `regexp` package to `testing`.

**Comment by dkegel-fastly** [comment]
Bleah.    Dropping support for -run on small platforms doesn't sound great, but neither does switching to some other sort of matching than regexp...

**Comment by dgryski** [comment]
We could build a string matcher that just uses `strings.Contains` on "small" platforms.  That way we still have *some* sort of matching behaviour, but it's not a full regexp engine..

**Comment by dankegel** [comment]
Probably the best option.

**Comment by dkegel-fastly** [comment]
OK, I'll bite.  Who calls MainStart?

**Comment by aykevl** [comment]
I already replied on Slack, but for anybody reading this: try `tinygo list -deps -test -json <package>` to get the path to the generated file (the generated main package is the last package in the output).

**Comment by dankegel** [comment]
https://github.com/tinygo-org/tinygo/pull/2711 should fix it.
