### ISSUE TITLE
SPI.Tx() in atsamd51 is slowing down in tinygo 0.21

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#2696]
Benchmarks using pyportal_boring show a clear SPI slowdown as of version 0.21.

I put D6.Toggle() in the following location to measure the waveform.
Is this because HasBit() is slow?
Need to look into this a bit more.

```go
func (pd *spiDriver) write8sl(b []byte) {
	machine.D6.Toggle()
	pd.bus.Bus.CTRLB.ClearBits(sam.SERCOM_SPIM_CTRLB_RXEN)

	for i, c := 0, len(b); i < c; i++ {
		for !pd.bus.Bus.INTFLAG.HasBits(sam.SERCOM_SPIM_INTFLAG_DRE) {
		}
		machine.D6.Toggle()
		pd.bus.Bus.DATA.Set(uint32(b[i]))
	}

	pd.bus.Bus.CTRLB.SetBits(sam.SERCOM_SPIM_CTRLB_RXEN)
	for pd.bus.Bus.SYNCBUSY.HasBits(sam.SERCOM_SPIM_SYNCBUSY_CTRLB) {
	}
}
```

tinygo 0.20 : 36 fps
![image](https://user-images.githubusercontent.com/9251039/157653640-9c106f65-bd57-41e9-b8f1-95a5b75be44b.png)

tinygo 0.21 : 25 fps : There is a large gap between bytes in the SPI transmission.
![image](https://user-images.githubusercontent.com/9251039/157653738-75c87a3e-8a81-428a-8e04-f5b70c6a5545.png)

source code
https://github.com/tinygo-org/drivers/tree/release/examples/ili9341/pyportal_boing
https://github.com/tinygo-org/drivers/blob/a15f2167cc7e46864d82e08904a3ddaa3e610d5e/ili9341/spi_atsamd51.go#L56-L68

**Comment by sago35** [comment]
Adding `-opt s` seems to restore the original speed.

* tinygo 0.20 : 37 fps
* tinygo 0.21 : 37 fps


Did the opt setting change somewhere?

**Comment by deadprogram** [comment]
@sago35 is this still an issue with the latest `dev` branch?

**Comment by deadprogram** [comment]
@sago35 is this still an issue or can we close now?

**Comment by deadprogram** [comment]
Closing since I think this was addressed. @sago35 please reopen if needed.
