### ISSUE TITLE
No CI test verifying tinyfs compatibility?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2709]
https://github.com/tinygo-org/tinygo/commits/release/src/os/filesystem.go shows the commits that added ReadAt() and Seek() methods to os.FileHandle.
These methods are not present in https://github.com/tinygo-org/tinyfs/blob/release/tinyfs.go, which presumably breaks some uses of tinyfs in tinygo
But CI did not flag those as a problem.  Perhaps we need a tinyfs smoke test in "make smoketest" to verify interoperability.

**Comment by deadprogram** [comment]
Solved by this PR: https://github.com/tinygo-org/tinygo/pull/2710

**Comment by dkegel-fastly** [comment]
Awesome. 

Those FileHandle changes still aren't flagged as a problem, fwiw.

**Comment by deadprogram** [comment]
Yes, that seems like the smoke tests in that repo need more coverage.
