### ISSUE TITLE
tinygo does not yet build and pass tests with go 1.18 installed

### ISSUE THREAD

**Issue by slzatz** [tinygo-org/tinygo#2718]
I am sure you're aware but hoping you can clarify the situation.  With go 1.18 released, tinygo won't build with the check for go version that is in builder/config.go.  Should we reinstall 1.17 or is 1.18 compatibility coming soon?

**Comment by dkegel-fastly** [comment]
No ETA yet.  Personally, I'm sticking with 1.17 for the moment.

It's being worked on; see https://github.com/tinygo-org/tinygo/pull/2515 and related pull requests.

**Comment by dkegel-fastly** [comment]
See https://github.com/tinygo-org/tinygo/pull/2725

**Comment by dkegel-fastly** [comment]
Closing duplicate

**Comment by dkegel-fastly** [comment]
See https://github.com/tinygo-org/tinygo/issues/2762 for the remaining test.
