### ISSUE TITLE
RP2040 returns incorrect result when we reading multi-ADCs in sequence

### ISSUE THREAD

**Issue by elbert-wong** [tinygo-org/tinygo#2738]
When reading multiple ADC channels in sequence on RP2040, we got result of incorrect channel.  

`
		val0 = sensor0.Get()   // correct
		val1 := sensor1.Get()  // correct
		val2 := sensor2.Get()  // incorrect now
`

It should be because we didn't reset ADC channel bits before we set it. 

diff src/machine/machine_rp2040_adc.go  /usr/local/lib/tinygo/src/machine/machine_rp2040_adc.go

1d0
< //go:build rp2040
34a34
>       rp.ADC.CS.ClearBits((uint32(0x03) << rp.ADC_CS_AINSEL_Pos))

**Comment by lincolngill** [comment]
Fixed in PR #2737

**Comment by deadprogram** [comment]
Closing since it was fixed in release v0.23.0 thank you!
