### ISSUE TITLE
Improved Nix support

### ISSUE THREAD

**Issue by eliasnaur** [tinygo-org/tinygo#2752]
I have [a patch](https://github.com/NixOS/nixpkgs/pull/167556) for upgrading to TinyGo v0.22.0 in Nixpkgs. This issue is about the patch for `libclang` and sysroot headers: https://github.com/NixOS/nixpkgs/pull/167556/files#diff-ac0392bc2a2bd75b8b62dc1dcbed09ac203fd9f9ab022c4ae02b30fc12318abc. Can any of the changes be upstreamed or done in a better way, thereby slimming the Nix configuration for future releases?

**Comment by deadprogram** [comment]
Was this already addressed?

**Comment by eliasnaur** [comment]
I believe it's good enough as is.
