### ISSUE TITLE
Tinygo error: requires go version 1.15 through 1.17, got go1.18

### ISSUE THREAD

**Issue by andyzyb** [tinygo-org/tinygo#2758]
$tinygo version: 

tinygo version 0.22.0 linux/amd64 (using go version go1.18 and LLVM version 13.0.0)

$ tinygo build  -o main.wasm main.go
error: requires go version 1.15 through 1.17, got go1.18

This seems strange why it only supports <= 1.17 but itself built with 1.18

**Comment by dankegel** [comment]
We've been holding off applying e8737d8285aeaa868bb449c4e4a947646204af36 from 
https://github.com/tinygo-org/tinygo/pull/2725 because it fails a test on windows.
We probably shouldn't wait.  In the meantime, you can apply it yourself.

**Comment by dankegel** [comment]
Try it now.

**Comment by freecodewu** [comment]
![image](https://user-images.githubusercontent.com/96016540/162803569-51223859-7d68-4e55-b275-5b47c1824adf.png)

I also have the issue.

**Comment by freecodewu** [comment]
> ![image](https://user-images.githubusercontent.com/96016540/162803569-51223859-7d68-4e55-b275-5b47c1824adf.png)
> 
> I also have the issue.

macOS

**Comment by dkegel-fastly** [comment]
The fix is in the dev branch and will be part of tinygo 0.23 when it is released.

If you want to try it now, it's not too hard to build the dev branch.

**Comment by freecodewu** [comment]
> 

if I use go1.17 , will the issue exist。

**Comment by dkegel-fastly** [comment]
tinygo 0.22 supports go 1.17.  Using go 1.17 for now is easiest.
