### ISSUE TITLE
tinygo version 0.22.0 darwin/amd64 (using go version go1.18 and LLVM version 13.0.0)

### ISSUE THREAD

**Issue by freecodewu** [tinygo-org/tinygo#2768]
![image](https://user-images.githubusercontent.com/96016540/162803232-52ffb43d-4fe0-42f4-8bd0-1ed9629ce949.png)

os:Macos

**Comment by dkegel-fastly** [comment]
This is expected.  Tinygo 0.22 does not support go 1.18.  The fix for that will be in tinygo 0.23.
If you like, you can try the fix now by building the dev branch.
