### ISSUE TITLE
misc hashmap cleanups

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#2771]
A reminder to myself to extract some of the common calculations to small helper functions and add `//go:nobounds` to avoid the extra nil-pointer checks.

**Comment by dgryski** [comment]
Also clear out buckets when deleting keys to avoid pinning allocations.

Ancient patch rescued from `git stash` for some of the above cleanups.

[hashmap-extract-functions.patch](https://github.com/tinygo-org/tinygo/files/11047205/hashmap-extract-functions.patch)

**Comment by dgryski** [comment]
Also size hinting should pre-allocate enough buckets so that we can actually insert `n` items without allocating.  Note that because of the logic in `hashmapShouldGrow` we need to *over* allocate to take into account the load factor calculation.   Move that calculation out to its own routine so that we don't need to duplicate the logic.

**Comment by dgryski** [comment]
https://github.com/tinygo-org/tinygo/pull/3605

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
