### ISSUE TITLE
List actual microcontrollers in the "microcontrollers" documentation?

### ISSUE THREAD

**Issue by sybrenstuvel** [tinygo-org/tinygo#2789]
Hey folks,

The [Microcontrollers chapter of the docs](https://tinygo.org/docs/reference/microcontrollers/) doesn't actually list microcontrollers, but rather lists boards. If I want to know whether an ATmega328pb or ATtiny85 is supported, where would I look?

Cheers,
Sybren

**Comment by deadprogram** [comment]
You need to define a board to flash code on it with TinyGo. 

For all current MPU supported see https://github.com/tinygo-org/tinygo/tree/release/src/machine

For info on adding a board/processor see https://github.com/tinygo-org/tinygo/wiki/Adding-a-new-board

**Comment by deadprogram** [comment]
Closing since this question was answered. Thank you!
