### ISSUE TITLE
tinygo/lib/compiler-rt/lib/builtins/absvdi2.c: could not locate Clang headers

### ISSUE THREAD

**Issue by arbourd** [tinygo-org/tinygo#2795]
Strange new behaviour when building an arm64 container from source (which worked fine prior to `v0.22.0`). I don't have any experience with `clang` or `llvm` so I'd love some help understanding why this is happening.

Ran:
- `make llvm-source` ✅
- `make llvm-build` ✅
- `make wasi-libc` ✅
- `make` ✅
- `make release` ❌

Fails on the last bit of `build/release` https://github.com/tinygo-org/tinygo/blob/v0.22.0/Makefile#L644:

```
#0 148.0 ./build/tinygo build-library -target=cortex-m0     -o build/release/tinygo/pkg/thumbv6m-unknown-unknown-eabi-cortex-m0/compiler-rt     compiler-rt
#0 148.1 error: failed to build /root/tinygo/lib/compiler-rt/lib/builtins/absvdi2.c: could not locate Clang headers
```

**Comment by aykevl** [comment]
Can you tell a bit more about the environment? OS, etc

**Comment by arbourd** [comment]
Absolutely! Thank for taking the time @aykevl.

I am attempting to build both `amd64` and `arm64` on Linux using a different Dockerfile (for our purposes). It is here if that helps. It is located here: https://github.com/suborbital/subo/blob/6e49f277e7c064c9f8a2de08b878adb0c66c9c9b/builder/docker/tinygo/Dockerfile.base#L28-L29

We're purposely skipping some other steps. With `v0.21.0` we've had no issues building. I'm guessing it might have been [this change](https://github.com/tinygo-org/tinygo/commit/3883550c446fc8b14115366284316290f3d3c4b1) that is causing issues, I just don't understand why the clang headers would have moved 😅

**Comment by aykevl** [comment]
I don't think it's https://github.com/tinygo-org/tinygo/commit/3883550c446fc8b14115366284316290f3d3c4b1, but you can confirm by reverting this commit.

TinyGo assumes that the Clang headers are in a particular location. The logic is here: https://github.com/tinygo-org/tinygo/blob/release/builder/env.go#L17
I see you're storing the LLVM source in a non-default location, that may be causing these issues. If you really want to know which commit is causing this, you could try bisecting this issue.

**Comment by aykevl** [comment]
Actually, this might be pretty simple to solve. Can you patch the lines here to be `./build/release/tinygo/bin/tinygo` instead of `./build/tinygo` and see whether that fixes the issue? The difference is that the former is already like a release build including Clang headers while the latter is the regular build location.

https://github.com/tinygo-org/tinygo/blob/3883550c446fc8b14115366284316290f3d3c4b1/Makefile#L644-L649

**Comment by arbourd** [comment]
that seems to have worked @aykevl! thank you.

should we patch it this way in `dev` as well? whats the justification for using the "regular build location"?

**Comment by arbourd** [comment]
Ah I understand what's going on now, I just needed to move the headers from `clang/lib/Headers`

**Comment by aykevl** [comment]
> should we patch it this way in `dev` as well? whats the justification for using the "regular build location"?

If you want to make a PR, that would be great!
