### ISSUE TITLE
Using js bindings in another package

### ISSUE THREAD

**Issue by phillvancejr** [tinygo-org/tinygo#2810]
Is it possible to crate bindings to Js functions in packages that are not main and then use that package in the main file?

I've tried something like this:

project structure:
    main.go
    add/add.go
    

js used to setup wasm
```js
// normal gobal import
go.importObject.env['main.greet']= ()=>console.log('hello')

go.importObject.env['add.AddFive']= num =>num + 5

// wasm instantiation
```
add/add.go
```go
package add
func AddFive(num int) int
```
main.go
```go
package main
import "./add"

func main() {
  println(add.AddFive(10))
}
```
I'm using `GO111MODULE=off` right now for simplicity. Is there a way to implement the AddFive function in Javascript, but have it defined in a package other than main so that I can have sub packages?

**Comment by aykevl** [comment]
Yes, this should be possible.

1. Please use Go modules and absolute imports. I'm not sure how relative imports exactly work and Go modules simplify this.
2. Use `//export` to export the `Add` function (technically it's an import not an export but it is needed for a standardized ABI). This is not limited to the main package.

Example:

```go
//export add
func Add(int x) int
```

**Comment by phillvancejr** [comment]
> Yes, this should be possible.
> 
> 1. Please use Go modules and absolute imports. I'm not sure how relative imports exactly work and Go modules simplify this.
> 2. Use `//export` to export the `Add` function (technically it's an import not an export but it is needed for a standardized ABI). This is not limited to the main package.
> 
> Example:
> 
> ```go
> //export add
> func Add(int x) int
> ```

Hey thanks! This worked but 'main.addFive' didn't work, I had to drop the 'main.' and just use `go.importObject.env['addFive'] = num => num + 5`

**Comment by aykevl** [comment]
Yes, if you use `//export addFive` then the external name will be `addFive`.
