### ISSUE TITLE
"tinygo test archive/zip" fails on linux; gophercolor16x16.png wrong length?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2839]
I just created an ubuntu 22.04 test VM (with 16GB RAM and 100GB root volume), installed tools with (IIRC)
```
sudo apt update
sudo apt dist-upgrade
sudo apt install golang-go build-essential cmake ninja-build
curl https://wasmtime.dev/install.sh -sSf | bash
sudo shutdown -r now
```
and built dev from source.
"make test" and "make smoketest" passed (up until esp32; I don't have xtensa-esp32-elf-ld installled).
"make tinygo-test-wasi-fast" also passed.

But "make tinygo-test" seemed to hang on archive/zip.
Running "build/tinygo test -v archive/zip" by itself took a minute, and failed like this:
```
FAIL: TestReader/test.zip
   gophercolor16x16.png: len=785, want 664
...
FAIL: TestReader/test-trailing-junk.zip
    gophercolor16x16.png: len=785, want 664
```

But  ```unzip -v /usr/share/go-1.18/src/archive/zip/testdata/test.zip```
says gophercolor16x16.png is indeed 785 bytes.

wat

**Comment by dgryski** [comment]
Hmmm.. memory corruption perhaps then?

**Comment by dkegel-fastly** [comment]
Ha, no, it's an artifact of overzealous ubuntu 22.04 apt compression of datafiles, I think.  
Unpacking the .deb with ar, then unpacking data.tar.* with tar -xf, shows the image file in question
got compressed harder.

Anyone who runs into this can just install go from golang.org to work around the problem.

I will file upstream bug reports... closing.

**Comment by dankegel** [comment]
pkgbinarymangler dunnit, see https://bugs.launchpad.net/bugs/1972735
