### ISSUE TITLE
"make test-corpus" fails on chewxy/math32, which has changed

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2841]
On my ubuntu 2022.04 vm, with a freshly built dev, "make test-corpus" fails for me
on chewxy/math32 with errors like

FAIL: TestVetMath32
   FAIL: TestVetMatch32/GOOS=linux?GOARCH=arm64
      fork/exec /usr/lib/go-1.18/bin/go: operation not implemented

https://github.com/chewxy/math32/blob/master/math32_test.go shows what's going on;
it's trying to run the go compiler with various values for GOARCH and GOOS,
which isn't going to fly since tinygo doesn't actually support fork/exec.

How was this passing for anyone?  Easy: it's a recent feature, see their commit history,
https://github.com/chewxy/math32/commits/master

So chewxy/math32's tip is no longer suitable for "make test-corpus".

**Comment by dkegel-fastly** [comment]
Confirming "make test-corpus" fails also on mac with everything but chewxy/math32 removed.

**Comment by dgryski** [comment]
The yaml file supports a module `Version`, so we can pin it to an earlier version without that feature.

**Comment by dkegel-fastly** [comment]
I will submit a fix to chewxy, too

**Comment by dkegel-fastly** [comment]
Fixed.
