### ISSUE TITLE
Can you use tinygo with the normal runtime?

### ISSUE THREAD

**Issue by lanza** [tinygo-org/tinygo#2846]
Simple question, could tinygo be used with with the runtime from the normal go project? I'm interested in the LLVM backend but not the embedded CPU aspect, so using the normal runtime would be my aim.

**Comment by dgryski** [comment]
No, I don't believe so. The compiler and runtime are tightly integrated, and that's true for both the tinygo project and the main Go project.

**Comment by aykevl** [comment]
@lanza TinyGo can't do this. But you may be interested in gollvm:
https://go.googlesource.com/gollvm/

**Comment by aykevl** [comment]
Also, TinyGo also supports Linux/macOS/Windows as a compilation target, it's not just limited to embedded systems.

**Comment by lanza** [comment]
> @lanza TinyGo can't do this. But you may be interested in gollvm:
https://go.googlesource.com/gollvm/

Interesting. This was removed from llvm due to it being dead for years, but evidently people have been supporting it on that googlesource repo. Thanks for the link.

> Also, TinyGo also supports Linux/macOS/Windows as a compilation target, it's not just limited to embedded systems.

Yup, this was my motivation in asking. I figured if it could target everything go could then it probably doesn't have a hard coupling to the runtime. I was hoping there was some `--use-go-runtime` flag override. 

> No, I don't believe so. The compiler and runtime are tightly integrated, and that's true for both the tinygo project and the main Go project.

How so? The runtime is clearly part of the project, but looking over the commits that added the runtime files from go, they seem like a copy/paste job. Do you know of a sticking point that would cause an issue?
