### ISSUE TITLE
Running tinygo test ./... fails

### ISSUE THREAD

**Issue by jcchavezs** [tinygo-org/tinygo#2892]
Running `tinygo test ./...` does not properly resolve all the packages recursively.

**Comment by dkegel-fastly** [comment]
Seems to resolve recursively here on at least some packages.  Can you give a real-world example?  e.g.
```
$ git clone https://go.googlesource.com/image
$ cd image
$ tinygo test ./...
# golang.org/x/image/font/inconsolata
font/inconsolata/bold8x16.go:8:2: could not import golang.org/x/image/font/basicfont (Config.Importer.Import(golang.org/x/image/font/basicfont) returned nil but no error)
FAIL
```
(That's just an example of the kind of detail that would be great in this bug report)

**Comment by jcchavezs** [comment]
In this very same repository, you can run

```
➜  tinygo git:(fixes_three_dots) ✗ tinygo test ./tests/testing/... 
error: Linking globals named 'main.tests': symbol multiply defined!
```
and after the change you get
```
➜  tinygo git:(fixes_three_dots) ✗ ~/Workspace/gource/bin/tinygo test ./tests/testing/... 
ld.lld: error: undefined symbol: _notARealFunction
>>> referenced by /var/folders/s7/qmqrxc894d55fymyt4x506300000gn/T/tinygo1047012886/main.o
error: failed to link /var/folders/s7/qmqrxc894d55fymyt4x506300000gn/T/tinygo1047012886/main: exit status 1
--- FAIL: TestFail (0.00s)
    fail
FAIL
FAIL    github.com/tinygo-org/tinygo/tests/testing/fail 0.326s
?       github.com/tinygo-org/tinygo/tests/testing/nothing      [no test files]
ok      github.com/tinygo-org/tinygo/tests/testing/pass 0.176s
FAIL
````

But all this started in the repository github.com/corazawaf/coraza where running `tinygo test ./...` only tested first package `github.com/corazawaf/coraza/v2`:

```
Run tinygo test ./...
# github.com/corazawaf/coraza/v2
Error: collection.go:23:2: could not import github.com/corazawaf/coraza/v2/types/variables (Config.Importer.Import(github.com/corazawaf/coraza/v2/types/variables) returned nil but no error)
Error: transaction.go:29:2: could not import github.com/corazawaf/coraza/v2/bodyprocessors (Config.Importer.Import(github.com/corazawaf/coraza/v2/bodyprocessors) returned nil but no error)
Error: transaction.go:30:2: could not import github.com/corazawaf/coraza/v2/loggers (Config.Importer.Import(github.com/corazawaf/coraza/v2/loggers) returned nil but no error)
Error: transaction.go:3[4](https://github.com/corazawaf/coraza/runs/6661735281?check_suite_focus=true#step:6:5):7: could not import github.com/corazawaf/coraza/v2/utils/url (Config.Importer.Import(github.com/corazawaf/coraza/v2/utils/url) returned nil but no error)
FAIL
Error: transaction.go:34[5](https://github.com/corazawaf/coraza/runs/6661735281?check_suite_focus=true#step:6:6):25: invalid operation: cannot compare tx.bodyProcessor != nil (operator != not defined on untyped nil)
Error: Process completed with exit code 1.
```

**Comment by dkegel-fastly** [comment]
I think it stops at the first failure.  It'll be a while before coraza builds with tinygo, I think.

Here's a PR to add a smoke test for "tinygo test ./...": https://github.com/tinygo-org/tinygo/pull/2894

I think your branch currently fails that smoke test, FWIW.

**Comment by jcchavezs** [comment]
> I think it stops at the first failure. It'll be a while before coraza builds with tinygo, I think.

I am working on making it support tinygo, see https://github.com/corazawaf/coraza/pull/254

> I think your branch currently fails that smoke test, FWIW.

I just left you a comment, I think the test has a bug, see https://github.com/tinygo-org/tinygo/pull/2894#discussion_r889616906

**Comment by dkegel-fastly** [comment]
That explains a lot :-). Glad to see your work!

Thank you for reviewing my test; I checked your theory, seems it is incorrect; it would have been correct had I been quoting the result of the wc.
