### ISSUE TITLE
Execute cmd in tinygo works differently?

### ISSUE THREAD

**Issue by spaceslums** [tinygo-org/tinygo#2917]
In "fat" go this code 
```go
package main

import (
	"os"
	"os/exec"
	"strings"
)

func main() {
	cmd := exec.Command("su", "-c", "id")
	cmd.Stdin = strings.NewReader("toor")
	cmd.Stdout = os.Stdout
	cmd.Run()
}
```
works correctly and print `uid=0(root) gid=0(root) groups=0(root)`. But in tinygo this code print nothing. Why?

**Comment by dankegel** [comment]
Because exec is not yet supported in tinygo.

**Comment by spaceslums** [comment]
@dankegel oh, okay.

**Comment by probonopd** [comment]
Reference: 
* https://github.com/tinygo-org/tinygo/issues/632
