### ISSUE TITLE
print() complains "unknown arg type: []byte"

### ISSUE THREAD

**Issue by Rail-dex** [tinygo-org/tinygo#2922]
Trying to use a byte array throws a compilation error : 

unknown arg type: []byte

Doesnt matter if self written or in any predesigned struct like bytes.buffer{}

tinygo version 0.23.0 windows/amd64 (using go version go1.18.3 and LLVM version 14.0.0)
MCU used: RPI PICO

**Comment by aykevl** [comment]
What is the code you're compiling?

**Comment by Rail-dex** [comment]
package main

	func main() {

		buffer := []byte{'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd'}

		print(buffer)

	}

**Comment by dgryski** [comment]
TinyGo's `print` builtins don't supprt `[]byte`: https://github.com/tinygo-org/tinygo/blob/release/compiler/compiler.go#L1304

Try `print(string(buffer))` instead.

**Comment by deadprogram** [comment]
This was addressed by #2925 quite a while ago, so closing. Thanks again everyone!
