### ISSUE TITLE
RP2040 sometimes does not start up

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#2938]
As shown in the following image, pressing the RESET button while Blinky1 is running may not start it.
It always seems to work immediately after `tinygo flash`.
It may not work after pressing RESET or turning the power back on.
There may be a problem with the initialization code.

Reproduced with TinyGo 0.23 and dev branch.

![image](https://user-images.githubusercontent.com/9251039/176149592-4f7df52e-43cd-46f0-ba44-13607901c4f1.png)

**Comment by kenbell** [comment]
@sago35 I've noticed some slight weirdness on reset sometimes - putting a sleep at the start of main fixed it for me.  Wonder if it's just a timing thing?

**Comment by sago35** [comment]
After making the changes in #2960, the problem has been completely resolved.

From @kenbell's advice, I was able to check pico and notice it.
Thank you very much.
