### ISSUE TITLE
Serialer interface does not have DTR

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#2978]
The new changes that added the `Serialer` interface cause a problem in the drivers repo, because it does not have a `DTR()` function.

https://github.com/tinygo-org/drivers/runs/7292184926?check_suite_focus=true#step:7:287

**Comment by sago35** [comment]
Okay.  I think we should add it.

**Comment by deadprogram** [comment]
`RTS()` also :smiley_cat:
