### ISSUE TITLE
wasi: imported and exported functions do not result in identical signatures.

### ISSUE THREAD

**Issue by james-lawrence** [tinygo-org/tinygo#3000]
I've created a standalone repository that reproduces this [issue](https://github.com/james-lawrence/tinygo-wasi-bug).

essentially functions that are imported from the runtime and functions that are exported do not generate the same function signature making them unusable.

```golang
//export github.com/james-lawrence/tinygo-wasi-bug/wasi/runtime/env.Boolean
func Boolean(fallback bool, keys ...string) bool {
	return false
}
```

```
// imported function by a wasm module
func Boolean(fallback bool, keys ...string) bool
```

the example repository will fail to execute with the following result (output is truncated for brevity):
```
exported github.com/james-lawrence/tinygo-wasi-bug/wasi/runtime/env.Boolean ( i32, i32, i32, i32 ) i32
imported github.com/james-lawrence/tinygo-wasi-bug/wasi/runtime/env.Boolean ( i32, i32, i32, i32, i32 ) i32
import[4] func[env.github.com/james-lawrence/tinygo-wasi-bug/wasi/runtime/env.Boolean]: signature mismatch: i32i32i32i32i32_i32 != i32i32i32i32_i32
```
reproduction steps from the repository above:
```
tinygo build -target wasi -wasm-abi generic -o module1.wasm ./impl/wasi/runtime/runtime.go
tinygo build -target wasi -wasm-abi generic -o module2.wasm main.go
go run ./cmd/wasibug/main.go
```

**Comment by aykevl** [comment]
Right, I see. The way to solve this is to mark them both as "exported" - which really means to make the function available externally. For example like this:

```go
// imported function by a wasm module
//export github.com/james-lawrence/tinygo-wasi-bug/wasi/runtime/env.Boolean
func Boolean(fallback bool, keys ...string) bool
```

Functions without an `//export` pragma will use an internal calling convention that's not stable. Functions with an `//export` pragma will try to match the C calling convention.

**Comment by codefromthecrypt** [comment]
@james-lawrence is there anything else to do on this one?

ack that [`//export` isn't intuitive to mark something as an import](https://github.com/tinygo-org/tinygo/pull/455#issuecomment-531603663), but for today `//export` is how it is done.

**Comment by james-lawrence** [comment]
@codefromthecrypt that is very unintuitive. ;) i'll take it for a spin this weekend and see if it works. if it does I'll point out documentation that should probably be updated for others. ;)

**Comment by codefromthecrypt** [comment]
@james-lawrence opened https://github.com/tinygo-org/tinygo/issues/3147 for follow-up. maybe close this out unless there's something else to do here?

**Comment by james-lawrence** [comment]
Sounds good to me; will put my notes in that issue.
