### ISSUE TITLE
go 1.20's "tinygo test -skip" unimplemented

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#3056]
upstream sprouted a test -skip flag on tip today: https://go-review.googlesource.com/c/go/+/421439/

We should consider implementing it, too.

**Comment by dgryski** [comment]
This shouldn't be too hard..

**Comment by dgryski** [comment]
I'll wait until https://github.com/golang/go/issues/41583 is actually closed.

**Comment by dkegel-fastly** [comment]
It's closed now.

**Comment by aykevl** [comment]
Sorry I misclicked
