### ISSUE TITLE
Execute code from RAM, on Raspberry pi Pico

### ISSUE THREAD

**Issue by 0xcafed00d** [tinygo-org/tinygo#3078]
Is there currently anyway to mark a TinyGo function as executing from RAM? Something like the //go:inline directive?
If not is it possible then is there any way to mark a cgo function as executing from RAM?

I've tried to mark reproduce the `__no_inline_not_in_flash_func` macro used in the pico sdk, but the code doesnt seem to get put the the correct location in the elf file produced...

```c++
#define __not_in_flash(group) __attribute__((section(".time_critical." group)))
#define __not_in_flash_func(func_name) __not_in_flash(__STRING(func_name)) func_name
#define __no_inline_not_in_flash_func(func_name) __attribute__((noinline)) __not_in_flash_func(func_name)
```

**Comment by aykevl** [comment]
Correct, we don't support anything like this at the moment. Perhaps we should.
Here is a similar issue: https://github.com/tinygo-org/tinygo/issues/2599, and I'm sure I've seen this come up before.

**Comment by aykevl** [comment]
Also related: https://github.com/tinygo-org/tinygo/pull/1759

**Comment by deadprogram** [comment]
This has been implemented in the `dev` branch as part of https://github.com/tinygo-org/tinygo/pull/3536/commits/796b7bd4416dcd110db271797f75c60cf1667322

Please see https://github.com/tinygo-org/tinygo/blob/dev/src/examples/ram-func/main.go

Marking this issue to be closed as part of next release.

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
