### ISSUE TITLE
panic: compiler: could not store type code number inside interface type code

### ISSUE THREAD

**Issue by tucnak** [tinygo-org/tinygo#3090]
No idea what this this does as there's no verbose mode.

I've been trying to build [gioui/kitchen](https://git.sr.ht/~eliasnaur/gio-example/tree/b12a70663a15/item/kitchen) for wasm when this occured after 10 or so minutes of `tinygo build` flaming at full power:

Steps to reproduce:

```
git clone https://git.sr.ht/~eliasnaur/gio-example ge
cd ge/kitchen
tinygo build -o main.wasm -target wasm .
```

I had to do a little fix for `gioui/app/datadir.go` to basically silently get rid of `os.UserConfigDir` missing in tinygo.

But aside from that it's supposed to be fine, I think.

```
panic: compiler: could not store type code number inside interface type code

goroutine 520 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect({0x600000008040?})
	/Users/runner/work/tinygo/tinygo/transform/reflect.go:187 +0x978
github.com/tinygo-org/tinygo/transform.Optimize({0xc011acadf0?}, 0xc00028e450, 0x2, 0x0?, 0x5)
	/Users/runner/work/tinygo/tinygo/transform/optimizer.go:119 +0x39e
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x60004ed76020?}, 0xc00028e450)
	/Users/runner/work/tinygo/tinygo/builder/build.go:1100 +0x20d
github.com/tinygo-org/tinygo/builder.Build.func5(0xc015a4c000)
	/Users/runner/work/tinygo/tinygo/builder/build.go:561 +0x5ed
github.com/tinygo-org/tinygo/builder.runJob(0xc015a4c060, 0x0?)
	/Users/runner/work/tinygo/tinygo/builder/jobs.go:222 +0x4f
created by github.com/tinygo-org/tinygo/builder.runJobs
	/Users/runner/work/tinygo/tinygo/builder/jobs.go:123 +0x5db
```

**Comment by aykevl** [comment]
This issue consists of two separate issues.

> I've been trying to build [gioui/kitchen](https://git.sr.ht/~eliasnaur/gio-example/tree/b12a70663a15/item/kitchen) for wasm when this occured after 10 or so minutes of `tinygo build` flaming at full power:

This is the first issue. My guess is that it's an issue with interp, but it could also be #3019. Hard to know without digging into it.

>     panic: compiler: could not store type code number inside interface type code

This is the second issue. It will be fixed by #2640.

**Comment by tucnak** [comment]
Is there anything I can help with triage-wise, some debug information to share, perhaps? I'm not sure whether if this is platform dependent, as I'm rocking an arm64 darwin— is where the issue occurred initially.

**Comment by dgryski** [comment]
The new reflect work is in and should fix this issue.

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing this issue. Thanks!
