### ISSUE TITLE
flash -target wioterminal fails

### ISSUE THREAD

**Issue by czyt** [tinygo-org/tinygo#3105]
go version :  go1.19 windows/amd64
tinygo version : 0.25.0 windows/amd64 (using go version go1.19 and LLVM version 14.0.0)
fails with error
```
D:\tinygo\src\runtime\gc_globals_conservative.go:13:6: markGlobals redeclared in this block
D:\tinygo\src\runtime\gc_globals.go:14:6:       other declaration of markGlobals
```

**Comment by aykevl** [comment]
I think you installed TinyGo over a previous version. The file gc_globals_conservative.go has been renamed.

Try removing D:\tinygo and reinstalling it to fix the issue.

**Comment by czyt** [comment]
@aykevl thanks，I reinstalled tinygo as you commented,it worked.
