### ISSUE TITLE
allow turning on gcAsserts with a build tag

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#3138]

**Comment by aykevl** [comment]
Seems reasonable. Perhaps better would be a build tag to enable asserts for the runtime package as a whole (for example, also including the scheduler asserts). That seems simpler to me.

**Comment by dgryski** [comment]
Oh, good point.  Yeah, I'll do that.

**Comment by dgryski** [comment]
This is https://github.com/tinygo-org/tinygo/pull/3191

**Comment by deadprogram** [comment]
0.27.0 has now been released, so closing. Thank you!
