### ISSUE TITLE
ci: alpine build actions/setup-go is revlocked to v2

### ISSUE THREAD

**Issue by codefromthecrypt** [tinygo-org/tinygo#3146]
Per https://github.com/actions/setup-go/issues/263 something needs to change in [build-linux](https://github.com/tinygo-org/tinygo/blob/release/.github/workflows/linux.yml#L15) or we won't be able to get fixes or features in actions/setup-go@v3, notably cache integration which simplifies things. actions/setup-go@v2 currently still works, but was last released in feb 2022.

I think the various options are:
* do nothing until it breaks (current approach)
* workaround the GOROOT issue (unsure it will work)
* install go on alpine a different way
* switch off alpine
* your choice here

**Comment by aykevl** [comment]
Here is my attempt to fix this: https://github.com/tinygo-org/tinygo/pull/3158
