### ISSUE TITLE
USB-HID: Media/Consumer keys is not work

### ISSUE THREAD

**Issue by labrusca** [tinygo-org/tinygo#3171]
Seem Media/Consumer keys is not working on my M60 Keyboard(base on nrf52840),but the other keys is working well.
system: Windows 11

**Comment by aykevl** [comment]
What has this to do with TinyGo? Are you programming it using TinyGo?

**Comment by labrusca** [comment]
> What has this to do with TinyGo? Are you programming it using TinyGo?

I tried to write firmware for my mechanical keyboard using tinygo and it works fine so far except for the Media/Consumer keys, which don't work

**Comment by sago35** [comment]
Yes, Media/Consumer keys are not currently supported.

https://github.com/tinygo-org/tinygo/blob/v0.25.0/src/machine/usb/hid/keyboard/keyboard.go#L233

It was in the source code we based it on, but we have not been able to implement it so far.

https://github.com/ardnew/tinygo/blob/6dcabd49800981e31c94d0ce5a571376c20b854b/src/machine/usb/dhw-hid_atsamd51.go#L126

**Comment by labrusca** [comment]
@sago35 
Oh ,I see,thanks.thanks. Maybe I'll drop those keys for now until it's implemented.

**Comment by neildavis** [comment]
+1 for implementing USB Consumer Control events (e.g. volume). It's the only thing currently stopping me from using TinyGo instead of CircuitPython on my USB input boards :)

Is something blocking this or is it just a case of priority/time?

**Comment by sago35** [comment]
@labrusca @neildavis 
If you are interested, check out the following

#3436

**Comment by deadprogram** [comment]
This was completed as part of release `v0.28` so now closing. Thanks!
