### ISSUE TITLE
net.Pipe not supported

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#3187]
Looking at https://github.com/go-jose/go-jose 
#2660 covers go-jose's need for reflect.

The next problem I noticed was a test needs net.Pipe:
```
$ cd json
$ tinygo test
# github.com/go-jose/go-jose/v3/json
stream_test.go:185:15: Pipe not declared by package net
```

**Comment by johnkeates** [comment]
I did a very quick grep to see if net.Pipe is actually used directly by go-jose, but it only appears to be part of the test. Did you test other features beyond this? Or is this more of an explore-and-implement roadmap.

**Comment by dkegel-fastly** [comment]
It was the barest of "what is the next low hanging fruit" kind of exploration.

**Comment by deadprogram** [comment]
0.27.0 has now been released, so closing. Thank you!
