### ISSUE TITLE
WASM: MakeMapWithSize not declared by package reflect

### ISSUE THREAD

**Issue by gedw99** [tinygo-org/tinygo#3197]
I found the same error in https://github.com/tinygo-org/tinygo/blob/d984b55311a2acd6c1b14ef6e87ee280e737a925/testdata/corpus.yaml#L266

I am not sure what is the cause... 

Reproduction:

```
git clone https://github.com/henrixapp/pdfcomprezzor
cd pdfcomprezzor && GOOS=js GOARCH=wasm go build -o app.wasm .
go: downloading github.com/pdfcpu/pdfcpu v0.3.13
cd pdfcomprezzor && tinygo build -o app-tiny.wasm -target wasm .
# encoding/gob
/usr/local/opt/go/libexec/src/encoding/gob/decode.go:562:21: MakeMapWithSize not declared by package reflect

````

**Comment by dgryski** [comment]
This is a known limitation of the current `reflect` package.

**Comment by gedw99** [comment]
thanks @dgryski for feedback.

**Comment by leonbotros** [comment]
Running into this as well.

**Comment by aykevl** [comment]
An easy fix would be to stub it out, like here:

https://github.com/tinygo-org/tinygo/blob/b5ad81c884981f42c1ac491cc1d195aea886ddbe/src/reflect/value.go#L881-L884

Feel free to send a PR :)

**Comment by dgryski** [comment]
My recent reflect work #3470 implements this call.

**Comment by deadprogram** [comment]
This was completed as part of release `v0.28` so now closing. Thanks!
