### ISSUE TITLE
Add support for  the Tilittis Key 1

### ISSUE THREAD

**Issue by rminnich** [tinygo-org/tinygo#3202]
This is an rv32 key which uses a Lattice FPGA. All source for bitstreams and apps are available. 
https://github.com/tillitis/tillitis-key1

**Comment by deadprogram** [comment]
@rminnich I am adding it here: https://github.com/tinygo-org/tinygo/pull/4631 :smile_cat:

**Comment by deadprogram** [comment]
It is now in the `dev` branch! Tagged this issue to close after next release.
