### ISSUE TITLE
Can't flash code on stm32f407

### ISSUE THREAD

**Issue by AlexMshc** [tinygo-org/tinygo#3285]
Hey!

I have such error than i try to flash my code
error: failed to flash /var/folders/57/m1c29vwj1sx6bdsdm5p_c0tm0000gn/T/tinygo2215818869/main.hex: exec: "openocd": executable file not found in $PATH
Seems like i shoud do sth, but i really dont know what

**Comment by deadprogram** [comment]
Hello @AlexM-dev please see https://tinygo.org/docs/reference/microcontrollers/stm32f4disco/#openocd
