### ISSUE TITLE
Use Servo

### ISSUE THREAD

**Issue by TelegramXPlus** [tinygo-org/tinygo#3289]
How do I use a Servo with tinygo, the docs of the driver are not well-explained and i have no idea how to configure the PWM. I'm using Arduino btw

**Comment by soypat** [comment]
Hey! Maybe this answers a bit of your question: https://github.com/tinygo-org/tinygo/tree/release/src/examples/pwm
It's a directory with a bunch of PWM usage examples for various targets. Check out the `arduino.go` one! I'd suggest using something like 200Hz for servos and varying between 10% and 70% duty cycle. Let me know how that goes!

**Comment by deadprogram** [comment]
@TelegramXPlus you might want to take a look at the `servo` driver in the TinyGo drivers repo here: 
https://github.com/tinygo-org/drivers/blob/release/servo/servo.go

Here is an example of how to use it:
https://github.com/tinygo-org/drivers/blob/release/examples/servo/servo.go

**Comment by BerndCzech** [comment]
I tested the servo example on a raspberry pi pico and it works.
