### ISSUE TITLE
'Warning: Image file at 0x1000 is protected with a hash checksum'

### ISSUE THREAD

**Issue by donni-h** [tinygo-org/tinygo#3293]
hey folks, 
I just bought my first microcontroller (ESP32 NodeMCU) and wanted to test out the blinking LED program.

When I flash it to my ESP, the program does what is should for about 2 seconds then abruptly quits. this is my terminal output:

```
tinygo flash -target=esp32-coreboard-v2 -port=/dev/ttyUSB0 main.go 
esptool.py v4.3
Serial port /dev/ttyUSB0
Connecting......
Chip is ESP32-D0WDQ6 (revision v1.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 0c:b8:15:cd:0f:e0
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00001fff...
Warning: Image file at 0x1000 is protected with a hash checksum, so not changing the flash mode setting. Use the --flash_mode=keep option instead of --flash_mode=dout in order to remove this warning, or use the --dont-append-digest option for the elf2image command in order to generate an image file without a hash checksum
Compressed 3232 bytes to 2426...
Wrote 3232 bytes (2426 compressed) at 0x00001000 in 0.3 seconds (effective 100.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```
according to tinygo flash --help  '--flash_mode=keep' is not actually an option, so I assume it's an error caused by the esptool.
Is there any other flag that I can set so that my program keeps working?
Just in case I screwed up the code somehow, I'll attach the code too, but I doubt I messed up 5 lines of code.
Any help would be gladly appreciated! :)

```
package main

import (
  "machine"
  "time"
)

func main() {
  led := machine.Pin(2)
  led.Configure(machine.PinConfig{Mode: machine.PinOutput})
  for {
    led.Low()
    time.Sleep(time.Millisecond * 500)

    led.High()
    time.Sleep(time.Millisecond * 500)
  }
}
```

**Comment by donni-h** [comment]
> hey folks, I just bought my first microcontroller (ESP32 NodeMCU) and wanted to test out the blinking LED program.
> 
> When I flash it to my ESP, the program does what is should for about 2 seconds then abruptly quits. this is my terminal output:
> 
> ```
> tinygo flash -target=esp32-coreboard-v2 -port=/dev/ttyUSB0 main.go 
> esptool.py v4.3
> Serial port /dev/ttyUSB0
> Connecting......
> Chip is ESP32-D0WDQ6 (revision v1.0)
> Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
> Crystal is 40MHz
> MAC: 0c:b8:15:cd:0f:e0
> Uploading stub...
> Running stub...
> Stub running...
> Configuring flash size...
> Flash will be erased from 0x00001000 to 0x00001fff...
> Warning: Image file at 0x1000 is protected with a hash checksum, so not changing the flash mode setting. Use the --flash_mode=keep option instead of --flash_mode=dout in order to remove this warning, or use the --dont-append-digest option for the elf2image command in order to generate an image file without a hash checksum
> Compressed 3232 bytes to 2426...
> Wrote 3232 bytes (2426 compressed) at 0x00001000 in 0.3 seconds (effective 100.1 kbit/s)...
> Hash of data verified.
> 
> Leaving...
> Hard resetting via RTS pin...
> ```
> 
> according to tinygo flash --help '--flash_mode=keep' is not actually an option, so I assume it's an error caused by the esptool. Is there any other flag that I can set so that my program keeps working? Just in case I screwed up the code somehow, I'll attach the code too, but I doubt I messed up 5 lines of code. Any help would be gladly appreciated! :)
> 
> ```
> package main
> 
> import (
>   "machine"
>   "time"
> )
> 
> func main() {
>   led := machine.Pin(2)
>   led.Configure(machine.PinConfig{Mode: machine.PinOutput})
>   for {
>     led.Low()
>     time.Sleep(time.Millisecond * 500)
> 
>     led.High()
>     time.Sleep(time.Millisecond * 500)
>   }
> }
> ```

Edit: Well guys it was my code after all. Every tutorial I found for the ESP32-NodeMCU used Pin = 2, apparently my particular model needs to use Pin = 1 to make the LED blink.

**Comment by deadprogram** [comment]
Closing as individual issue that was resolved.
