### ISSUE TITLE
STM32 is flashed the first few times, but then it stops.

### ISSUE THREAD

**Issue by AlexMshc** [tinygo-org/tinygo#3314]
error: failed to flash /var/folders/57/m1c29vwj1sx6bdsdm5p_c0tm0000gn/T/tinygo3075307498/main.hex: exit status 1

I did it on three stm32s and this happened to all of them :(

**Comment by deadprogram** [comment]
I used STM32 boards often and do not have this problem.

Closing due to age and lack of info, please reopen if needed. Thanks!
