### ISSUE TITLE
stm32wl55

### ISSUE THREAD

**Issue by tcpipchip** [tinygo-org/tinygo#3334]
Hi

My tinygo working nice on NRF52840

Now i want to test on STM32WL55 using these libs

How can i compile this 
https://github.com/ofauchon/go-lorawan-stack

On tinygo ?

**Comment by ofauchon** [comment]
First version of lorawan stack is now part of tinygo drivers v0.24:
(https://github.com/tinygo-org/drivers/releases/tag/v0.24.0)

I propose we close this issue ... 
@deadprogram ?

**Comment by tcpipchip** [comment]
this is cool!

**Comment by deadprogram** [comment]
> I propose we close this issue ...

Agreed, we already have this in `release`. Now closing, thanks everyone!
