### ISSUE TITLE
Go routine not workin on a pico

### ISSUE THREAD

**Issue by BerndCzech** [tinygo-org/tinygo#3355]
Sorry for the bold question but **how could I debug** why go routines don´t work on my **raspberry pi pico**?

imagine code like

```go

func main(){
  go func(){ 
    blink_led()
  }

  readTemp()
}
```

In fact my led stays off and the temperature display shows 0.
It seems like the whole code is skipped.

**Comment by aykevl** [comment]
Can you also share the code for `readTemp`?

**Comment by BerndCzech** [comment]
Glad you are interested

I just use a buzzer instead of displaying a temperature to reduce the code. But the concurrency is also not working here - so it's reproducible in that sense.

```go

package main

import (
	"machine"
	"tinygo.org/x/drivers/buzzer"
)

func main(){
	btn := machine.GP10
	btn.Configure(machine.PinConfig{Mode: machine.PinInput})

	led := machine.LED
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})

	// works
	// led.High()

	// does not work
	go func() {
		led.High()
	}()

	playC := func() {
		bzrPin := machine.GP20
		bzrPin.Configure(machine.PinConfig{Mode: machine.PinOutput})
		bzr := buzzer.New(bzrPin)

		bzr.Tone(buzzer.C4, buzzer.Half)
	}

	for {
		if btn.Get() {
			playC()
		}
	}
}
```

The observed behavior is: 

* LED is off  a the beginning
* Once I touch the buzzer i hear the C playing
* The led is switched on and stays on

I would expect that the LED is not off at the beginning.

I could extend the example with some concurrency - so please ask me.

**Comment by bgould** [comment]
does it work if you update this
```
	// does not work
	go func() {
		led.High()
	}()
```

to be this instead?

```
	// does not work
	go func() {
		for {
			led.High()
			time.Sleep(500 * time.Millisecond)
			led.Low()
			time.Sleep(500 * time.Millisecond)
		}
	}()
```

Please remember that when you start a goroutine, once the function exits the goroutine also exits.

**Comment by BerndCzech** [comment]
It seems like the button click acts like a keep alive for the go routine.


https://user-images.githubusercontent.com/69037455/209587170-7b8fe5f8-e9ae-42b6-8025-f62da2ef2c9a.mp4

**Comment by BerndCzech** [comment]
I pursued this understanding and replaced

```go
  for {
    if btn.Get() {
      playC()
    }
  }
```
by 
```go
for {
  if btn.Get() {
    playC()
  } else {
    time.Sleep(time.Millisecond)
  }
}
```
and now it works without any errors. Could it be that the infinite loop occupies the whole cpu and the go routine is not handled anymore?

I would work around the issue with some kind of useless sleep command at the end of my programs. But is that behavior expected?

**Comment by bgould** [comment]
> 
> and now it works without any errors. Could it be that the infinite loop occupies the whole cpu and the go routine is not handled anymore?
> 
> I would work around the issue with some kind of useless sleep command at the end of my programs. But is that behavior expected?

yes this is expected ... if the main loop does not yield at all with blocking operations (like the time.Sleep invocation) then control will not be passed to other goroutines.  Alternative to time.Sleep you could probably use `runtime.Gosched` (https://pkg.go.dev/runtime#Gosched) to make it work.

**Comment by BerndCzech** [comment]
@bgould ty - I will close the issue now. Could you amplify what implications of your quote below are? I don´t see them myself.
 
> Please remember that when you start a goroutine, once the function exits the goroutine also exits.

**Comment by bgould** [comment]
Please disregard ... I misinterpreted the intention of your code I believe when I made that comment. Thank you!
