### ISSUE TITLE
code errors while code is fully completed

### ISSUE THREAD

**Issue by JensvandeWiel** [tinygo-org/tinygo#3363]
![image](https://user-images.githubusercontent.com/85284773/210778397-c0b4ce6e-c175-4a08-b3d0-f99fa8acc0e8.png)
this is in goland and i cant get it to work

**Comment by dgryski** [comment]
Without more information, we can't decide if this is related to tinygo or GoLand.  Maybe open an issue there?  https://youtrack.jetbrains.com/issues/GO

Closing for now.  If it does turn out to be an issue with TinyGo, please reopen.
