### ISSUE TITLE
On the ESP32 requires the use of bluetooth and WIFI,What's the solution

### ISSUE THREAD

**Issue by onism-up** [tinygo-org/tinygo#3396]

**Comment by alvonwong** [comment]
i think that's a great but hard job for developers . i expect it  on raspberry pi pico .

**Comment by onism-up** [comment]
> i think that's a great but hard job for developers . i expect it on raspberry pi pico .

Yes, TinyGo still needs a period of growth

**Comment by aykevl** [comment]
Duplicate of https://github.com/tinygo-org/tinygo/issues/2024.
