### ISSUE TITLE
I2C reads losing a byte

### ISSUE THREAD

**Issue by torntrousers** [tinygo-org/tinygo#343]
I've a bug somewhere and I'm starting to wonder if its in TinyGo. The problem is with reading data from a u-blox GPS module over I2C and it seems to lose a byte after each read. 
This is some code that recreates the problem:
```
func main() {
	println("Test1")
	machine.I2C0.Configure(machine.I2CConfig{})
	var data [10]byte
	for {
		// time.Sleep(17 * time.Millisecond)
		machine.I2C0.Tx(uint16(0x42), []byte{0xFF}, data[:])
		print("[")
		print(string(data[:]))
		println("]")
	}
}
```
and that outputs things like:
```
[,,,,*7A
$]
[NGSA,A,1,,]
```
which has lost a 'G' between the '$' and 'NGSA'

It seems to happen after each Tx call the next byte from the slave is lost.

Any ideas on how I could debug this?

**Comment by aykevl** [comment]
What target is this for? Such problems are highly chip specific.

**Comment by torntrousers** [comment]
Running on a Microbit

**Comment by torntrousers** [comment]
I think I found it, moving this line https://github.com/tinygo-org/tinygo/blob/master/src/machine/machine_nrf.go#L238 up to be just before line 235 seem to fix the problem. Doing some more testing...

**Comment by torntrousers** [comment]
Running for a couple of hours now without missing a beat so it does look like #344 fixes this

**Comment by deadprogram** [comment]
Did you happen to try your change with any other I2C devices?

**Comment by aykevl** [comment]
This could explain why I had some weird issues with I2C sometimes, with data that was off by one byte sometimes (but not always).

**Comment by torntrousers** [comment]
I've tried now with a couple of other I2C devices. The SHT31 from the open PR works with and without the fix. The BMP180 though doesn't work with this fix on. Hmm.

**Comment by torntrousers** [comment]
Seems to be some timing thing - if I put a println at the start of machine_nrf.go readLastByte then the BMP180 example works with this fix.

**Comment by torntrousers** [comment]
Fixed by moving to after the EVENTS_RXDREADY loop. So now it works with BMP180, SHT31, and the u-blox MAX-8.

**Comment by torntrousers** [comment]
Bugger, no the u-blox still misses a byte sometimes like this.

**Comment by torntrousers** [comment]
I can't figure out how to get this working with both the BMP180 and the u-blox GPS. Annoying. Any ideas anyone?

**Comment by deadprogram** [comment]
Was doing some searches and came up with this: https://github.com/sandeepmistry/arduino-nRF5/pull/137

Seems like trying to use the "short" might be the way to go here.

**Comment by torntrousers** [comment]
I've hacked around using that SHORTS/TASKS_RESUME without really understanding what I'm doing and amazingly it seems to work. Need to go but now but will show that code in a PR later on today.

**Comment by deadprogram** [comment]
This has been merged into `dev` branch, so now closing. Thanks @torntrousers for the fix.
