### ISSUE TITLE
When is the next tinygo release? (0.27)

### ISSUE THREAD

**Issue by jmoney** [tinygo-org/tinygo#3435]
I noticed it hasn't been released since october of 2022.  Curious if there is any plan to release it soon

**Comment by dgryski** [comment]
We're working on it. :) Stay tuned.

**Comment by ulisesflynn** [comment]
Along these lines, will this release include an update to allow the use of Go 1.20?
`error: requires go version 1.18 through 1.19, got go1.20`

Thank you for all the great work on tinygo!

**Comment by jmoney** [comment]
Looking forward to it.  i really just want https://github.com/tinygo-org/tinygo/commit/62594004c60cb3d8fab328aab71e5e0ea7e58119 in a release so i can test it out.  I have a bit of code that relies on `xml.Escape` from `encoding/xml` which currently fails in tinygo.

**Comment by Mossaka** [comment]
Hey! If you just want to test it out locally, feel free to grab the TinyGo 0.27 artifacts from the CI

Note: the link below is the link to Linux TinyGo SDKs. You can find artifacts for your OS in other workflows.
https://github.com/tinygo-org/tinygo/actions/runs/4085636487#artifacts

**Comment by jmoney** [comment]
I will definitely test it out and report any issues this evening.

**Comment by jmoney** [comment]
This release works perfectly for my use cases!  Anyway you can get the mac binaries out?  Right now I'm doing some nonsense docker building just to generate the wasm i need.

**Comment by Mossaka** [comment]
Here is a macos binary for amd64 https://github.com/tinygo-org/tinygo/actions/runs/4085636484#artifacts

**Comment by jmoney** [comment]
sorry again, but the arm64 ones perhaps :D  Have an M1 unfortunately.   The others will work for our CI pipeline but locally i'll need the mac arm64 ones.

**Comment by aykevl** [comment]
> sorry again, but the arm64 ones perhaps :D Have an M1 unfortunately. The others will work for our CI pipeline but locally i'll need the mac arm64 ones.

v0.27.0 (the coming release) won't have darwin/arm64 support unfortunately because GitHub Actions doesn't support this OS/arch. You have two options: build a release yourself or use Rosetta 2.

**Comment by jmoney** [comment]
Interesting, so when I do `brew install tinygo` that much be installing darwin/amd64 and then using rosetta?  In which case, i can make this work with darwin/amd64.  Thanks for the note.

**Comment by jmoney** [comment]
Ok, i have everything tested and working locally and in CI.  Now, when do you think that 0.27 will officially be released?  I'd like to remove some of the "hacks" i have in place in CI to get the built versions that have so generously been generated and looking to see when i'd be able to do so.

**Comment by dgryski** [comment]
https://github.com/tinygo-org/tinygo/releases/tag/v0.27.0
