### ISSUE TITLE
Github contribution - inexperienced user 

### ISSUE THREAD

**Issue by Gustavomurta** [tinygo-org/tinygo#3440]
I'm have no experience with github. And I wish to contribute.  I actually think it could be simpler.
Anybody can help me? 

If there is a TinyGo forum where I can ask for help, I apologize for intruding.

My project - **ROM Reader with Arduino Mega (wiht Golang and Tinygo)**
https://github.com/Gustavomurta/Arduino_Mega_Programmer/tree/main/ROM%20Reader%20with%20Arduino

I want to extend this project later. 

Thanks in advance.

**Comment by soypat** [comment]
Hey! You'll get a much better and faster response asking on the tinygo channel in [Gophers slack](https://invite.slack.golangbridge.org/). This is the link to the invite: https://invite.slack.golangbridge.org/

**Comment by Gustavomurta** [comment]
Thanks soypat!

**Comment by deadprogram** [comment]
Closing since questions appears to have been answered. Thank you!
