### ISSUE TITLE
Idiomatic way to set build constraints for wasm/wasi

### ISSUE THREAD

**Issue by inliquid** [tinygo-org/tinygo#3493]
I used Go compiler (not Tinygo) with WebAssembly quite a lot and used to set both OS and arch in order to apply build constraints, especially when client (wasm) code resides in a subdir of server project. So in this case we usually go for
```
//go:build js && wasm
```
on a wasm side, and
```
//go:build !js
```
on a server side (it's enough to set it only for main package for VS Code to not complain).

When I start using Tinygo, I've noticed that some projects use keyword (I suppose it does not match neither arch nor OS, so it's just a tag) `tinygo.wasm` as a build constraint:
```
//go:build tinygo.wasm
```
so if the line above goes for client, the server would need to have:
```
//go:build !tinygo.wasm
```

And in VS Code I have to set specific build tag for `gopls` and tools.

But now I'm wondering, what would be an idiomatic way to set constraints based on OS/arch pair? Should it be something like `wasm` for arch and maybe `wasi` for OS?

**Comment by skelouse** [comment]
I'll share what we've done at Taubyte:

[Reference](https://github.com/taubyte/go-sdk-symbols/tree/main/event)


!wasi  (compiled only for tests, and recognized as valid by VS Code)
```go
//go:build !wasi && !wasm
// +build !wasi,!wasm

package eventSym

var GetEventType = func(eventId uint32, typeid *uint32) {}
```

wasi ( compiled with `tinygo build -o ... -tags=wasi` )
```go
//go:build wasi || wasm
// +build wasi wasm

package eventSym

//go:wasm-module taubyte/sdk
//export getEventType
func GetEventType(eventId uint32, typeid *uint32)
```

**Comment by aykevl** [comment]
Right now, TinyGo uses `tinygo.wasm` to cover all WebAssembly targets (`-target=wasm` and `-target=wasi`). We can't use a plain `wasm` build tag for WASI because we currently pretend WASI is linux/arm so that the standard library won't break.

In the future, we will likely use a `wasm` build tag for WASI too, once it is fully supported in Go and enough people have switched to a supporting version.

@inliquid I hope that answers your question.

**Comment by deadprogram** [comment]
Closing since I think this question was answered. Please reopen if needed. Thanks!
