### ISSUE TITLE
add new target: cryptoauth trust platform

### ISSUE THREAD

**Issue by hugolgst** [tinygo-org/tinygo#3494]
I would love to see the CryptoAuth Trust Platform being added.
It uses ATSAMD21E18A which is already implemented.
https://www.microchip.com/en-us/development-tool/DM320118

**Comment by hugolgst** [comment]
I can't get this code to blink the LED. Any idea why? 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/15371828/223092712-5ff10ab4-62d9-45be-a96a-e8969224eb69.png">
Here are some information about the chip: https://ww1.microchip.com/downloads/aemDocuments/documents/SCBU/ProductDocuments/BoardDesignFiles/DM320118-schematics.PDF 

It seems to flash ok but the LED is not blinking

<img width="488" alt="image" src="https://user-images.githubusercontent.com/15371828/223097166-e3a45aac-17c7-4ba9-9bf3-4047df500bca.png">

**Comment by conejoninja** [comment]
I think it should be something like this instead:

```go
var led = machine.LED
led.Configure(machine.PinConfig{Mode: machine.PinOutput})
```

**Comment by hugolgst** [comment]
Yes but since it is a custom board I did not set PinOutput in the board's file yet.

**Comment by conejoninja** [comment]
Ummm, but no need to re-define the PinOutput, since it's already in the `machine_atsamd21.go` file https://github.com/tinygo-org/tinygo/blob/release/src/machine/machine_atsamd21.go#L29 plus it should be `11` not `0`


Also, let's try with 
```go
var led = machine.LED
```
instead of 

```go
var led machine.Pin = 2
```

**Comment by hugolgst** [comment]
right, I was confused with something else. Now I am indeed using LED and PinOutput, it was just this. I can't thank you enough for your help. Better read the documentation well next time. 

I will try to clean out everything and make a pull request to add my board.

Have a nice day

**Comment by conejoninja** [comment]
No problem!
Adding a new board should be easy as long as the chip is already supported like this case.

I proceed to close this issue, please open a PR when your new board is ready!

Thanks for your work

**Comment by hugolgst** [comment]
https://github.com/tinygo-org/tinygo/pull/3527
