### ISSUE TITLE
CI failing in 'net' package often on Windows

### ISSUE THREAD

**Issue by kenbell** [tinygo-org/tinygo#3603]
The stdlib-test-windows is often failing in CI.  It appears the binary that is created to run tests in the 'net' package is not being created, causing the failure.

**Comment by kenbell** [comment]
From some poking, i think this failure is related in some way to the parallelism of the tests.  The test running code tries to setup a go routine for every test package in parallel.  Given the limited resources of the CI runners, I suspect we're hitting resource constraints.  I've tried a hacky solution of running the tests sequentially with (apparently) much better success.

**Comment by kenbell** [comment]
I did an experiment here to disable parallel test execution and it didn't solve the problem (first build failed to run), so I don't think it's directly related to running tests in parallel: https://github.com/tinygo-org/tinygo/pull/3604

**Comment by deadprogram** [comment]
Closing since this was addressed. Thanks!
