### ISSUE TITLE
javascript receive number type when golang call javascript function

### ISSUE THREAD

**Issue by kuki123456** [tinygo-org/tinygo#3619]
here is defined in golang

```go
//export Hello
func Hello(par string)string

here is called in golang 
func main() {
	println("adding two numbers:", add(2, 3)) // expecting 5
	println(Hello("ooowowwwww"))
}
```
here is defined in javascript 

```javascript
    const go = new Go(); // Defined in wasm_exec.js
    const WASM_URL = 'wasm.wasm';
    go.importObject.env = {
        'add': function(x, y) {
            return x+y
        },
        'Hello':function (par){
            console.log(par)
            return String(par+"woai!")
        }
        // ... other functions
    }
```

console print
<img width="667" alt="image" src="https://user-images.githubusercontent.com/47233095/228529546-4a553a9b-b961-4001-916f-8c7e9df3a32c.png">

**Comment by aykevl** [comment]
Strings are not supported in `//export`. But you can share strings in other ways, by returning a pointer and length pair.
This is explained in some of the blog posts here: https://github.com/tinygo-org/tinygo-site/pull/352/files
