### ISSUE TITLE
reflect.TypeOf inconsistency

### ISSUE THREAD

**Issue by adranwit** [tinygo-org/tinygo#3621]
reflect.TypeOf(T) return inconsistent hashcode when initialized in global block vs within a function:

The following code show the inconsistency issue:

```go
package main

import (
	"fmt"
	"reflect"
)

type Foo struct{}
type Bar struct{}

var types = map[reflect.Type]string{
	reflect.TypeOf(Bar{}): "Bar",
	reflect.TypeOf(Foo{}): "Foo",
}

func main() {
	fooTypeName, ok := types[reflect.TypeOf(Foo{})]
	fmt.Printf("hasFoo: %v key(%p) %v\n", ok, reflect.TypeOf(Foo{}))
	fmt.Printf("fooTypeName: '%v'\n", fooTypeName)
	fmt.Printf("%p\n", reflect.TypeOf(Foo{}))
	printReflectTypeHashCodes(types)
	var rTypes = map[reflect.Type]string{
		reflect.TypeOf(Bar{}): "Bar",
		reflect.TypeOf(Foo{}): "Foo",
	}
	printReflectTypeHashCodes(rTypes)
}

func printReflectTypeHashCodes(types map[reflect.Type]string) {
	for k := range types {
		fmt.Printf("%p\n", k)
	}
}
```

I would expect that reflect.TypeOf(T) return the same consistent type with the same hashcode

**Comment by adranwit** [comment]
Output:
hasFoo: false key(%!p(T=415)) %!v(MISSING)
fooTypeName: ''
%!p(T=415)
%!p(T=4545227312)
%!p(T=4545227360)
%!p(T=447)
%!p(T=415)

**Comment by aykevl** [comment]
This seems to be working well for me, what's the bug?

```
$ go run tmp/issue3621.go
hasFoo: true key(0x1024eec40) %!v(MISSING)
fooTypeName: 'Foo'
0x1024eec40
0x1024eebe0
0x1024eec40
0x1024eebe0
0x1024eec40

$ tinygo run tmp/issue3621.go
hasFoo: true key(0x100229510) %!v(MISSING)
fooTypeName: 'Foo'
0x100229510
0x1002294a0
0x100229510
0x1002294a0
0x100229510
```

**Comment by adranwit** [comment]
Your output is correct, in my output hasFoo: is false 

tinygo version
tinygo version 0.27.0 darwin/amd64 (using go version go1.18.1 and LLVM version 15.0.0)

tinygo run  main.go
hasFoo: false key(%!p(T=447)) %!v(MISSING)
fooTypeName: ''
%!p(T=447)
%!p(T=4558944816)
%!p(T=4558944864)
%!p(T=351)
%!p(T=447)

What version of tinygo are you using?

**Comment by aykevl** [comment]
I tested on the dev branch.
We have had a lot of reflect improvements in the dev branch that are not part of the last release. I assume this is one of the bugs that got fixed.

**Comment by adranwit** [comment]
thanks for an update, I'll start using dev branch

**Comment by deadprogram** [comment]
Reopening, will close on this next release.

**Comment by adranwit** [comment]
thanks,

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing. Thank you everyone!
