### ISSUE TITLE
Use two bits of type meta byte for Comparable / IsBinary

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#3683]
These two queries still require looping over all the fields in a struct, recursively.  Caching them in the meta byte would make both these operations `O(1)`.

**Comment by deadprogram** [comment]
This is the only other open issue for milestone 0.28 @dgryski :cat2:

**Comment by deadprogram** [comment]
How about this one @dgryski ?

**Comment by dgryski** [comment]
So we only *need* these flags for structs -- everything else it's just an easy type switch.  I suppose we could either choose to use these flags instead of the type switch *or* we could add a flag byte to the struct type that includes not only these two flags but also the alignment for the struct (so we don't need to recursively calculate that either).

**Comment by deadprogram** [comment]
Tagging @aykevl to answer this question, please.

**Comment by aykevl** [comment]
No strong preference from me.



> So we only _need_ these flags for structs -- everything else it's just an easy type switch.

True. Although, these bits are currently unused so we might as well generalize to all the types - not just structs (unless you know of a better use for these bits).

A third option would be to store the bits in the meta byte, but _only_ for the struct type. I don't see a real advantage of that though - except perhaps saving a few bits for future use in non-struct types.

**Comment by dgryski** [comment]
I suppose since these are internal flags, we can always change it in the future if it turns out we have a better use for those bits.
