### ISSUE TITLE
Use pointer tagging for `*T`, `**T`, and `***T`.

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#3684]
```
- Remove the ptrTo field, it won't be necessary anymore.
- Make sure all type structs are 32-bit aligned. This means the lower two bits of the pointer are zero.
- A type *T can then be represented by adding one to the pointer (this is equivalent to setting the lower bit to one).
- A type **T can be represented by adding two to the pointer.
- Same for ***T. A type ****T cannot be represented this way, we may still need a pointer type.
- Kind() returns PointerType when the lower two bits aren't zero, or else it behaves as it already does.
- Elem() subtracts one from the pointer if it is a pointer type, else it works as it already does.
```

**Comment by deadprogram** [comment]
This is one of the few remaining open issues for the 0.28 milestone @dgryski :smile_cat:

**Comment by dgryski** [comment]
The current partial fix for this is https://github.com/tinygo-org/tinygo/pull/3691 but I hit the limit of my current knowledge (and had some other things to work on).  Needs @aykevl to figure out how to solve the remaining issue with the optimization passes.

**Comment by deadprogram** [comment]
Calling @aykevl we need you! :stethoscope:

**Comment by deadprogram** [comment]
Now that https://github.com/tinygo-org/tinygo/pull/3737 has been merged, #3691 should be unblocked, @dgryski

**Comment by deadprogram** [comment]
Moving this to release milestone 0.29 based on Slack conversation.

**Comment by dgryski** [comment]
The tagged pointer pr should be good to merge.

**Comment by deadprogram** [comment]
Does that mean we should merge it now?

**Comment by dgryski** [comment]
It just needs a final review.

**Comment by deadprogram** [comment]
Also which is the PR you are referring to?

**Comment by deadprogram** [comment]
@dgryski were you referring to https://github.com/tinygo-org/tinygo/pull/3691 ?

**Comment by dgryski** [comment]
Yes.

**Comment by deadprogram** [comment]
This is part of the `v0.28` release so now closing. Thank you everyone!
