### ISSUE TITLE
wasm: allow GOOS=wasip1 to substitute for target=wasi

### ISSUE THREAD

**Issue by codefromthecrypt** [tinygo-org/tinygo#3685]
To allow drop-in replacement with go 1.21, it would seem nice to support `GOOS=wasip1` as an alternative to `-target=wasi`.

Per activity on https://github.com/golang/go/issues/58141, `GOOS=wasip1` will ship in Go 1.21 even if a subset of functionality vs the TinyGo equivalent target.

**Comment by dgryski** [comment]
I agree we should do this. We also need to figure out how this will affect build tags. Do we migrate all of tinygo to the new tag to match upstream and add it to the list of tags exported to users, etc.

**Comment by aykevl** [comment]
Same, we should add support for `GOOS=wasip1`. And perhaps also `-target=wasip1` for consistency.

**Comment by deadprogram** [comment]
Is anyone working on this one yet?

**Comment by aykevl** [comment]
I've made a draft PR for this feature: https://github.com/tinygo-org/tinygo/pull/3861

**Comment by deadprogram** [comment]
Now that #3861 has merged, I am marking this PR to close on next release. Thanks everyone!

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thank you very much everyone!
