### ISSUE TITLE
Lorae5 dev board and ST-Link v2 not recognized on windows

### ISSUE THREAD

**Issue by ManoloEvans** [tinygo-org/tinygo#3694]
The ST-Link v2 was not recognized on my Windows 10 OS. This was remedied by downloading the ST-Link v2 drivers for windows on this 

https://www.st.com/en/development-tools/stsw-link009.html

**Comment by aykevl** [comment]
I'm not sure what this issue about. Are you suggesting an improvement to the documentation?

**Comment by ManoloEvans** [comment]
Sorry, meant this as a message to anyone who uses windows and wants to program the Lorae5 using the STlink v2, meant to also ask where anyone thinks this information should go hehe

**Comment by deadprogram** [comment]
@ManoloEvans I suggest open an issue on https://github.com/tinygo-org/tinygo-site and probably close this one?
