### ISSUE TITLE
package runtime/metrics is not in GOROOT

### ISSUE THREAD

**Issue by DazWilkin** [tinygo-org/tinygo#3705]
Similar to issue described in #1997 and solved with PR #3117 

Package is used by e.g. Prometheus Go client library:
https://github.com/prometheus/client_golang/blob/main/prometheus/internal/go_runtime_metrics.go

Could this issue be "swallowed" even if only temporarily with a stub implementation a la [`runtime/trace`](https://github.com/tinygo-org/tinygo/blob/release/src/runtime/trace/trace.go)?

**Comment by aykevl** [comment]
Yes, a stub implementation seems like a good idea to me. Once a stub is in, we can think of a real implementation at a later date if needed.

**Comment by DazWilkin** [comment]
Thank you!

I'll submit a PR when I get home from walking with my dog.
