### ISSUE TITLE
__flash_data_end incorrectly configured?

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#3707]
A number just 1 smaller appears to be correct.
Size must be +1 when modifying here.

```
__flash_data_end = ORIGIN(FLASH_TEXT) + LENGTH(FLASH_TEXT);
```

```
__flash_data_end = ORIGIN(FLASH_TEXT) + LENGTH(FLASH_TEXT) - 1;
```

**Comment by aykevl** [comment]
`__flash_data_end` points to the address just after the flash, yes.
This may seem a bit odd, but there are reasons for this:
  * This makes sure `__flash_data_end` is aligned, if we would subtract 1 (to point to the last byte in flash memory) it would not be aligned.
  * You can get the length using `__flash_data_end - __flash_data_start`. If we change it with your suggestion, getting the length of the flash would be `__flash_data_end - __flash_data_start + 1` which will likely result in off-by-one errors.

**Comment by deadprogram** [comment]
Closing as answered, please reopen if needed @sago35
