### ISSUE TITLE
Unable to verify flash chip connection ESP32C3 

### ISSUE THREAD

**Issue by Timwxc** [tinygo-org/tinygo#3721]
I uploaded 2 codes with "usb cdc on boot: "enable" " set. After uploading the first code, the serial monitor showed what was expected. However, when I uploaded the second code, I encountered an error.

First code:
```
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.print("cool");
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.print("cool");
}
```
Second code:
```
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

BLECharacteristic *pCharacteristic;

#define LED_PIN 10

bool ledState = false;

class MyServerCallbacks: public BLEServerCallbacks {
    void onConnect(BLEServer* pServer) {
      Serial.println("Connected");
    }

    void onDisconnect(BLEServer* pServer) {
      Serial.println("Disconnected");
    }
};

void setup() {
  Serial.begin(115200);

  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  BLEDevice::init("Receiver");
  BLEServer *pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks());
  BLEService *pService = pServer->createService(BLEUUID((uint16_t)0x180F));
  pCharacteristic = pService->createCharacteristic(
                      BLEUUID((uint16_t)0x2A19),
                      BLECharacteristic::PROPERTY_READ |
                      BLECharacteristic::PROPERTY_WRITE
                    );
  pService->start();

  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(BLEUUID((uint16_t)0x180F));
  pAdvertising->setScanResponse(false);
  pAdvertising->setMinPreferred(0x0);  // set value to 0x00 to not advertise this parameter
  BLEDevice::startAdvertising();
}

void loop() {
  Serial.print("h");
  uint8_t value = pCharacteristic->getValue()[0];

  if (value == 1 && !ledState) {
    digitalWrite(LED_PIN, HIGH);
    ledState = true;
  } else if (value == 0 && ledState) {
    digitalWrite(LED_PIN, LOW);
    ledState = false;
  }
}
```

Upload error when upload again the first one:

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "ESP32C3 Dev Module, Disabled, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 160MHz (WiFi), QIO, 80MHz, 4MB (32Mb), 115200, None, Enabled"

Der Sketch verwendet 239078 Bytes (18%) des Programmspeicherplatzes. Das Maximum sind 1310720 Bytes.

Globale Variablen verwenden 15892 Bytes (4%) des dynamischen Speichers, 311788 Bytes für lokale Variablen verbleiben. Das Maximum sind 327680 Bytes.

esptool.py v4.5.1

Serial port COM6

Connecting...

Chip is ESP32-C3 (revision v0.4)

Features: WiFi, BLE

Crystal is 40MHz

MAC: 34:85:18:03:d6:d0

Uploading stub...

Running stub...

Stub running...

A fatal error occurred: Unable to verify flash chip connection (No serial data received.).

A fatal error occurred: Unable to verify flash chip connection (No serial data received.).

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by aykevl** [comment]
This bug tracker is for TinyGo, not for Arduino. Perhaps you can ask this question in the Arduino forum instead?
