### ISSUE TITLE
`defer panic()` doesn't work

### ISSUE THREAD

**Issue by dgryski** [tinygo-org/tinygo#3731]
```
~/go/src/github.com/dgryski/bug/defpan $ tinygo run main.go
todo: builtin: panic
todo: builtin: panic
~/go/src/github.com/dgryski/bug/defpan $ cat main.go
package main

func main() {
	println("before")
	defer panic("panic")
	println("after")
}
```

`panic` is `*ssa.Panic` which isn't handled by `defer` (or `createBuiltin`?).  I guess we need to turn it into a `b.createRuntimeInvoke("_panic", ...)`.

**Comment by joonas** [comment]
just wanted to chime in here that I'm also interested in this, but not quite sure how I could best help move things along 🙂

**Comment by aykevl** [comment]
Here is a fix: https://github.com/tinygo-org/tinygo/pull/4571
