### ISSUE TITLE
WASM file detected as invalid because bulk memory support is not enabled 

### ISSUE THREAD

**Issue by k33g** [tinygo-org/tinygo#3758]
Hello,
I build a wasm module with TinyGo like this:
```bash
tinygo build -o hello-orange.wasm \
    -scheduler=none \
    --no-debug \
    -target wasi ./main.go 
```

I would like to publish it to https://wapm.io/, but when I try this command `wapm publish`, I get this error message:

```bash
Error: WASM file "hello-orange.wasm" detected as invalid because bulk memory support is not enabled (at offset 3196)
```
I will create an [Issue](https://github.com/wasmerio/wasmer/issues/3932) on the Wasmer project, but I would like to know if I need to activate a specific flag when I build the module. Thank you 🙏

**Comment by fgsch** [comment]
Which tinygo version are you using?

**Comment by k33g** [comment]
@fgsch `0.27.0`

**Comment by aykevl** [comment]
We use bulk memory instructions, and there is no (easy) way to disable them at the moment.

> because bulk memory support is not enabled

Perhaps bulk memory can be enabled somewhere?
In any case, I don't think this is a TinyGo bug.

**Comment by k33g** [comment]
@aykevl Thank you. Apparently, it is a wapm bug, but they told me that was fixed in a previous version and closed the issue (https://github.com/wasmerio/wasmer/issues/3932) I hope they will reopen it.
