### ISSUE TITLE
Tinygo version 0.28.0 seems to have "dev" postfix, unlike in 0.27.0

### ISSUE THREAD

**Issue by inliquid** [tinygo-org/tinygo#3777]
Was going to update `tinygo` everywhere, but noted that unlike in 0.27.0, 0.28.0 has "dev" postfix. Tried Windows and Linux, took them from "assets" section on github release tab.

Is it correct?

**Comment by aykevl** [comment]
Yes, we're going to publish a 0.28.1 to fix this.

**Comment by inliquid** [comment]
Windows archive has wrong extension in 0.28.1, it's a ZIP archive and should be called "*.zip" but it's named "*.tar.gz".

**Comment by deadprogram** [comment]
Thanks for reporting @inliquid file extension fixed on the WIndows release for `v0.28.1`
