### ISSUE TITLE
os.ErrNoDeadline is undefined

### ISSUE THREAD

**Issue by svrakitin** [tinygo-org/tinygo#3784]
While trying to compile https://github.com/cockroachdb/cockroachdb-parser for WASI I run into the following error:

```
# github.com/cockroachdb/errors/errutil
../../go/pkg/mod/github.com/cockroachdb/errors@v1.9.0/errutil/format_error_special.go:42:6: undefined: os.ErrNoDeadline
```

It seems like `os.ErrNoDeadline` is just missing from os package and it should be trivial to add it there, similar to how `os.ErrDeadlineExceeded` is backported from `poll` package. I will make a PR.

**Comment by deadprogram** [comment]
Added tag to close this on next release.

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thank you!
