### ISSUE TITLE
Missing container images for tinygo 0.28.0 and 0.28.1 releases

### ISSUE THREAD

**Issue by flavio** [tinygo-org/tinygo#3787]
The container image for the 0.28.1 is missing from the Docker Hub. The same applies to 0.28.0, which IMHO could be skipped.

**Comment by deadprogram** [comment]
Forgot to push the tags, thanks for pointing this out @flavio 

Images are building now.

**Comment by deadprogram** [comment]
Images are now available, so closing. Thanks again!
