### ISSUE TITLE
define unsafe.IntegerType

### ISSUE THREAD

**Issue by codefromthecrypt** [tinygo-org/tinygo#3789]
I'd like code that uses `unsafe.IntegerType` to compile with TinyGo, but it currently doesn't.

For example, 
```go
	return unsafe.String((*byte)(ptr), unsafe.IntegerType(size))
```

The work-around compiles with TinyGo, but not Go
```go
	return unsafe.String((*byte)(ptr), size /* unsafe.IntegerType */)
```

**Comment by soypat** [comment]
Why? Isn't IntegerType not part of the language? In any case we should try to make Go match TinyGo?

> IntegerType is here for the purposes of documentation only and is not actually part of the unsafe package. It represents any arbitrary integer type.

**Comment by aykevl** [comment]
@codefromthecrypt can you give a complete example? I can't get it to compile in regular Go: https://go.dev/play/p/r3Zh3T9opz8

**Comment by codefromthecrypt** [comment]
Sorry it seems the Goland IDE is happy with unsafe.IntegerType, but you can't actually compile it. My mistake to open this (I was trying to get the compilation warning to go away).
