### ISSUE TITLE
error: cannot locate $GOROOT, please set it manually

### ISSUE THREAD

**Issue by labrusca** [tinygo-org/tinygo#3791]
$GOROOT seem missing, there is some information:
```
PS D:\SourceCode\git\Mordecai\prototype> tinygo build -o kb-m60.uf2 -target nrf52840 main.go
error: cannot locate $GOROOT, please set it manually
```
```
PS D:\SourceCode\git\Mordecai\prototype> tinygo version
tinygo version 0.28.1 windows/amd64 (using go version <unknown> and LLVM version 15.0.0)
```
```
PS D:\SourceCode\git\Mordecai\prototype> tinygo env
GOOS="windows"
GOARCH="amd64"
GOROOT=""
GOPATH="C:\\Users\\Paul\\go"
GOCACHE="C:\\Users\\Paul\\AppData\\Local\\tinygo"
CGO_ENABLED="1"
TINYGOROOT="C:\\Users\\Paul\\scoop\\apps\\tinygo\\current"
```
```
PS D:\SourceCode\git\Mordecai\prototype> go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Paul\AppData\Local\go-build
set GOENV=C:\Users\Paul\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Paul\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Paul\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\Paul\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\Paul\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Paul\AppData\Local\Temp\go-build582803746=/tmp/go-build -gno-record-gcc-switches
```
I need some help.

**Comment by sago35** [comment]
It did not reproduce on Window11pro. @labrusca 
I assume you are installing go and tinygo from scoop, does manual install reproduce the problem?


```
C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>set PATH=C:\tinygo\tinygo0.28.1.windows-amd64\tinygo\bin;%PATH%

C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>tinygo version
tinygo version 0.28.1 windows/amd64 (using go version go1.20.5 and LLVM version 15.0.0)

C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>tinygo env
GOOS="windows"
GOARCH="amd64"
GOROOT="C:\\go"
GOPATH="C:\\Users\\sago3\\dev"
GOCACHE="C:\\Users\\sago3\\AppData\\Local\\tinygo"
CGO_ENABLED="1"
TINYGOROOT="C:\\tinygo\\tinygo0.28.1.windows-amd64\\tinygo"

C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>where tinygo
C:\tinygo\tinygo0.28.1.windows-amd64\tinygo\bin\tinygo.exe

C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>tinygo build -o out.uf2 --target xiao-rp2040 examples/blinky1

C:\tinygo\tinygo0.28.1.windows-amd64\tinygo>go version
go version go1.20.5 windows/amd64
```

**Comment by labrusca** [comment]
The problem persisted after reinstalling Golang and Tinygo from scoop and $GOROOT is still empty.
How can I set $GOROOT manually? @sago35

**Comment by sago35** [comment]
@labrusca 
There is no need to manually set up GOROOT. If you have set it up, you may want to remove the setting.
Then try installing Go and TinyGo without Scoop.

**Comment by labrusca** [comment]
Things get strange,after installing Go and TinyGo without Scoop, I can find $GOROOT by executing `tinygo env` in the `C:\Users\Paul` directory, but in other directories, the $GOROOT is still empty.

**Comment by labrusca** [comment]
after rebooting my computer, $GOROOT was gone in the `C:\Users\Paul` directory

**Comment by Gustavomurta** [comment]
GORROT is associated with Path in the **advanced system settings** (Windows).
In the system properties window, select environment variables.
There are two options - user variables or system variables.

In the System Variables section, highlight the Path variable and click the Edit button. Add or modify the path lines with the paths of the Go enviroment. 

![image](https://github.com/tinygo-org/tinygo/assets/4587366/3ff911b7-85e6-4f46-8cd6-a5d307c28a0f)


I think that the paths in your Windows should only be associated with user variables.



C:\Users\jgust>go env
set GOPATH=C:\Users\jgust\go\
set GOROOT=C:\Program Files\Go\

C:\Users\jgust>tinygo env
GOOS="windows"
GOARCH="amd64"
GOROOT="C:\\Program Files\\Go\\"
GOPATH="C:\\Users\\jgust\\go\\"
GOCACHE="C:\\Users\\jgust\\AppData\\Local\\tinygo"
CGO_ENABLED="1"
TINYGOROOT="C:\\Users\\jgust\\scoop\\apps\\tinygo\\current"

**Comment by aykevl** [comment]
In 99.9% of cases, you should leave `GOROOT` unset. The Go toolchain will figure it out itself. **Please don't mess with GOROOT unless you absolutely know what you are doing.**

In any case, this bug was likely fixed in v0.29.0, with https://github.com/tinygo-org/tinygo/pull/3745. @labrusca can you test whether you still hit this issue in the latest stable version?

**Comment by Gustavomurta** [comment]
In my case, the GOROOT and GOPATH settings were defined by the Go and TinyGo installation programs.
My recommendation is about configuring PATH variables in Windows.

**Comment by labrusca** [comment]
After upgrading to the latest version, all issues have been resolved.
Thank you all.
