### ISSUE TITLE
Question: http server for microcontroller

### ISSUE THREAD

**Issue by ferllings** [tinygo-org/tinygo#3793]
Hello,

I'm currently working on a [WebOfThings](https://w3c.github.io/wot-thing-description/) framework that I'm building using GoFiber.
I'm thinking of creating a TinyGo version that would allow me to easily create custom home automation devices, with esp32, pi pico,...

As I'm a new to TinyGo and GoFiber may be not compatible and too heavy for microcontrolers,
What would be the best option to run an http (json) api server, with websockets support?
Am I limited to use net/http? or is there another option?

Thanks for you time

**Comment by deadprogram** [comment]
Oops I forgot to answer this question.

@ferllings please see https://github.com/tinygo-org/drivers/blob/release/examples/net/webserver and https://github.com/tinygo-org/drivers/tree/release/examples/net/webstatic for some examples.

**Comment by ferllings** [comment]
Thank you!
