### ISSUE TITLE
Use mount points to find UF2 devices instead of checking hardcoded paths

### ISSUE THREAD

**Issue by aykevl** [tinygo-org/tinygo#3814]
Right now we check for two fixed paths on Linux: `/run/media/*` and `/media/*`. Instead, we should read the list of mount points and use that instead.

This should fix an issue on NixOS that it doesn't automatically find the device.

**Comment by aykevl** [comment]
Fixed in https://github.com/tinygo-org/tinygo/pull/3816 - hopefully.

**Comment by marcofeltmann** [comment]
Tried with `tinygo version 0.29.0-dev-c83f712c linux/amd64 (using go version go1.20.5 and LLVM version 15.0.0)` and it just works!

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thanks a lot!
