### ISSUE TITLE
Tinygo binary in wasm tests

### ISSUE THREAD

**Issue by radkomih** [tinygo-org/tinygo#3815]
Is there a particular reason why wasm tests use the system installed tinygo
```
run(t, "tinygo build -o "+wasmTmpDir+"/chan.wasm -target wasm testdata/chan.go")
```

instead of the one build from source? 
```
run(t, "../../build/tinygo build -o "+wasmTmpDir+"/chan.wasm -target wasm testdata/chan.go")
```

**Comment by dgryski** [comment]
Is there anything that sets the path up so the built-from-source one comes first?
