### ISSUE TITLE
Cannot use machine.NoPin with rp2040

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo#3819]
The machine.Pin implementation of the RP2040 is as follows

https://github.com/tinygo-org/tinygo/blob/v0.28.1/src/machine/machine_rp2040_gpio.go#L123-L129

Perhaps just adding a guard in this area will eliminate the problem.
I will check later.

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thank you!
