### ISSUE TITLE
Exclude `.vscode` folder from source control

### ISSUE THREAD

**Issue by soypat** [tinygo-org/tinygo#3835]
I understand many developers here use VSCode as their daily driver IDE.

Could we add a line to `.gitignore` to exclude the settings directory from being tracked when committing changes?

Also, props to whatever change allowed us to work inside the tinygo repo with intellisense! It's been such a boon to my productivity!

**Comment by aykevl** [comment]
> Could we add a line to `.gitignore` to exclude the settings directory from being tracked when committing changes?

I have this in my global `.gitignore` (`$HOME/.gitignore`):

```
.vscode
go.work
go.work.sum
```

We could of course add `.vscode` but in my opinion this is really the responsibility of TinyGo developers (there are so many different IDEs with each their own config and temporary files).

> Also, props to whatever change allowed us to work inside the tinygo repo with intellisense! It's been such a boon to my productivity!

Nothing changed on our side. It has always been possible to use gopls for the compiler, but the machine package previously didn't work well. Apparently it does now? I didn't really check.

**Comment by soypat** [comment]
I had no idea configuring gitignores globally was possible. For future reference this is done by adding the file to git's global config:
```
git config --global core.excludesfile $HOME/.gitignore
```

Marking issue as resolved/closed.

**Comment by soypat** [comment]
> Apparently it does now? I didn't really check.

@aykevl  Does on my end!
![image](https://github.com/tinygo-org/tinygo/assets/26156425/4e3f8dd9-76df-4e09-bd16-3354aee51d8c)

**Comment by aykevl** [comment]
> For future reference this is done by adding the file to git's global config:

Oh, I see, I forgot I added that file in my `.gitconfig` file.

For locally ignored files (in a specific checkout), you can also modify `.git/info/exclude`. That's like `.gitignore` but won't be committed.
