### ISSUE TITLE
Interrupts on Arduino Nano

### ISSUE THREAD

**Issue by natty-light** [tinygo-org/tinygo#3847]
I'm just getting started with writing tinygo for my Arduino and am struggling to find information about how to implement interrupt handlers. Is this a supported feature in tinygo for the ATmega328p? If so, is there sample code showing how it is done?

**Comment by deadprogram** [comment]
Hello @natty-light please see https://github.com/tinygo-org/tinygo/pull/3841 

This is already in the `dev` branch, and will be part of the next release.

**Comment by natty-light** [comment]
@deadprogram Thanks for the info, will keep an eye out for that release!

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thank you everyone!
