### ISSUE TITLE
dev: on clean systems, git submodule update --init can have authn issues

### ISSUE THREAD

**Issue by kenbell** [tinygo-org/tinygo#3856]
The new renesas SVD submodule has an SSH 'URL' unlike the other submodules which are HTTPS.  This can lead to public key errors (repro case unclear).

We should use an HTTPS url for this submodule, the same as other submodules.

**Comment by deadprogram** [comment]
Since the Renesas submodule was merged only in the current `dev` branch, now closing this. Thanks @kenbell for the fix!
