### ISSUE TITLE
Any plans for ESP32?

### ISSUE THREAD

**Issue by tapir** [tinygo-org/tinygo#391]
Are there any plans to support ESP32 boards?

**Comment by aykevl** [comment]
See this FAQ entry: https://tinygo.org/faq/what-about-esp8266-esp32/
It is still not in a usable state. I would really like to add support, but they'll first need to implement machine code generation (they seem to be working on that), they need to rebase on top of a recent LLVM, and to make testing/distribution easier, the Xtensa backend would need to be merged upstream (even if it's experimental). Expect this to take at least a few months.
