### ISSUE TITLE
Waweshare RP2040-Plus compatibility

### ISSUE THREAD

**Issue by marekor555** [tinygo-org/tinygo#3930]
The RP2040-Plus is simmilar to raspberry pi pico(same processor), but has more pins.
is it compatible when using target as rpi pico, if not, is it possible to make some workaround?
I'm new to go and microcontrollers.

edit:
if so, can i use the same target for all pico compatible/rp2040 boards? for eg. seeduino xiao rp2040

**Comment by aykevl** [comment]
> is it compatible when using target as rpi pico

I don't know, I don't have the hardware. But I think there is a high chance it will work.

> if not, is it possible to make some workaround?

Yes, by adding full support for this board.

> if so, can i use the same target for all pico compatible/rp2040 boards? for eg. seeduino xiao rp2040

Why would you want to do this? At least the Xiao RP2040 is natively supported by TinyGo.
There are some differences between boards, but mostly they are differences in flash size, available pins, and maybe flash configuration.

**Comment by marekor555** [comment]
> > is it compatible when using target as rpi pico
> 
> I don't know, I don't have the hardware. But I think there is a high chance it will work.
> 
> > if not, is it possible to make some workaround?
> 
> Yes, by adding full support for this board.
> 
> > if so, can i use the same target for all pico compatible/rp2040 boards? for eg. seeduino xiao rp2040
> 
> Why would you want to do this? At least the Xiao RP2040 is natively supported by TinyGo. There are some differences between boards, but mostly they are differences in flash size, available pins, and maybe flash configuration.

just wanted to know, because i have some quite uncommon boards, and i wasn't sure if they would work,
thanks for the quick reply
