### ISSUE TITLE
Is it possible upgrade firmware online to STM32F4xx by Tinygo?

### ISSUE THREAD

**Issue by hgmmym** [tinygo-org/tinygo#3961]
This is not a bug report.

I'm using STM32F407, and I can connect to network through this development board.
Assuming I can download the bin file to the board, how can I upgrade the firmware?
Like a Boot-Loader or something?

**Comment by Gustavomurta** [comment]
Discussions are now permitted on TinyGo:
_https://github.com/orgs/tinygo-org/discussions_

**Comment by hgmmym** [comment]
@Gustavomurta I didn't even know there was a discussion in Github. Thanks.
