### ISSUE TITLE
wasmtime v14 breaks `-target=wasi`

### ISSUE THREAD

**Issue by ydnar** [tinygo-org/tinygo#3970]
Wasmtime v14 introduced a new CLI structure, with two changes relevant to TinyGo:

https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#1400

1. `--mapdir=GUEST::HOST` becomes `--dir=HOST::GUEST`: https://github.com/bytecodealliance/wasmtime/pull/7301
2. Arguments after the Wasm module to run are passed to the guest, instead of arguments after `--`: https://github.com/bytecodealliance/wasmtime/pull/6925

**Comment by deadprogram** [comment]
Tagged to close this issue after next release.

**Comment by dgryski** [comment]
We still need to update argument construction if we haven't already.

**Comment by ydnar** [comment]
I think argument construction is correct now.

**Comment by dgryski** [comment]
Ah yes, thanks.  Was trying to figure out why I was getting this warning from wasmtime.  Needed to rebase my branch against the latest `dev`:
```
~/go/src/github.com/dgryski/bug/intf $ tinygo run -target=wasi main.go
warning: this CLI invocation of Wasmtime will be parsed differently in future
         Wasmtime versions -- see this online issue for more information:
         https://github.com/bytecodealliance/wasmtime/issues/7384

         Wasmtime will now execute with the old (<= Wasmtime 13) CLI parsing,
         however this behavior can also be temporarily configured with an
         environment variable:

         - WASMTIME_NEW_CLI=0 to indicate old semantics are desired and silence this warning, or
         - WASMTIME_NEW_CLI=1 to indicate new semantics are desired and use the latest behavior
```

**Comment by deadprogram** [comment]
Completed with `v0.31.0` so now closing. Thank you!
