### ISSUE TITLE
Validating signature of JWT gives `undefined symbol: crypto/internal/bigmod.addMulVVW1024`

### ISSUE THREAD

**Issue by rica-graca** [tinygo-org/tinygo#3973]
## Description

Currently, I am trying to validate the signature of a JWT inside a wasm filter that is compiled with tinygo. My code is the following:

```
import (
	"github.com/golang-jwt/jwt/v4"
)

...
	parser := jwt.NewParser()
	signedToken, err := parser.Parse(token, func(t *jwt.Token) (interface{}, error) {
		return keyToValidateToken, nil
	})
```

And the result of:

`tinygo build -o code.wasm -scheduler=none -target=wasi code.go`

is: 

`tinygo:wasm-ld: error: /tmp/tinygo3147844765/main.o: undefined symbol: crypto/internal/bigmod.addMulVVW1536`

## Question
Is there any solution to this. Is there a way to validate a JWT signature without the need of this crypto library or this specific function bigmod.addMulVVW1536 which I do not get why is it undefined? I would be very grateful if someone has a solution. There should definitely be a way to verify a signature as in WASM code compiled with tinygo

**Comment by lann** [comment]
This may solve your problem: https://github.com/tinygo-org/tinygo/issues/3919#issuecomment-1730312952

**Comment by rica-graca** [comment]
Thank you so much @lann
