### ISSUE TITLE
docs: Update compatibility matrix to include Go 1.21

### ISSUE THREAD

**Issue by hariso** [tinygo-org/tinygo#4026]
Hey all!

Firstly, thanks to all the maintainers and contributors to this project! TinyGo is a great addition to the Go ecosystem.

Secondly, the compatibility matrix at https://tinygo.org/docs/reference/go-compat-matrix/ doesn't mention Go 1.21, but looking at the [0.29.0 release](https://github.com/tinygo-org/tinygo/releases/tag/v0.29.0), Go 1.21 is supported.

**Comment by deadprogram** [comment]
@hariso perhaps you can please report this issue over on https://github.com/tinygo-org/tinygo-site where the site content lives?

**Comment by hariso** [comment]
@deadprogram definitely!
