### ISSUE TITLE
Support PN532 NFC peripheral

### ISSUE THREAD

**Issue by paulcager** [tinygo-org/tinygo#4039]
[PN532](https://www.nxp.com/docs/en/user-guide/141520.pdf) is an NFC chip, often used in NFC breakout boards, such as [this](https://www.adafruit.com/product/364) Adafruit board.

Interaction is supported over I2C, SPI and UART.

It would be great to support it in TinyGo.

**Comment by deadprogram** [comment]
Hello @paulcager probably this issue would be better off created in the TinyGo Drivers repo here: https://github.com/tinygo-org/drivers
