### ISSUE TITLE
reflect: setting an interface value

### ISSUE THREAD

**Issue by radkomih** [tinygo-org/tinygo#4040]
I have encountered an issue and was able to create a small example to reproduce it. 
When running the code with standard Go, it prints out the value '13', however, with TinyGo, it prints out '35008' instead.

**Env:** `tinygo version 0.30.0 darwin/amd64 (using go version go1.21.0 and LLVM version 16.0.1`

`tinygo run -target=wasi main.go`

```go
package main

import (
	"reflect"
)

func main() {
	var value interface{} = uint16(0)

	// get the pointer to the interface value
	inPtr := reflect.ValueOf(&value)

	// dereference to get the actual value (an interface)
	inElem := inPtr.Elem()

	// create a new value of the same concrete type
	uint16Type := reflect.TypeOf(uint16(0))
	newUint16Value := reflect.New(uint16Type).Elem()
	newUint16Value.Set(reflect.ValueOf(uint16(13)))

	// set the new value to the interface
	inElem.Set(newUint16Value)

	println(value.(uint16))
}
```

**Comment by dgryski** [comment]
Thanks for the bug report.  I'll see what I can do.

**Comment by dgryski** [comment]
Can you please try https://github.com/tinygo-org/tinygo/pull/4041 and see if that fixes your problem?  (It solves your test case, but I want to make sure it works on your real code base.)

**Comment by radkomih** [comment]
@dgryski it works for my case
thank you ❤️
