### ISSUE TITLE
tinygo uses wrong go version

### ISSUE THREAD

**Issue by Jnoack331** [tinygo-org/tinygo#4044]
I Just followed the instruction for ubuntu to install tinygo. But instead of a supported Go version, tinygo outputs the following wrong go version:

`tinygo version 0.30.0 linux/amd64 (using go version go1.16.2 and LLVM version 16.0.1)`

![2023-12-15_13-42](https://github.com/tinygo-org/tinygo/assets/17640771/1f47514e-0e36-44dd-bf59-f4abcec01b8e)

so i cant build my project as it requires newer version:
`error: requires go version 1.18 through 1.21, got go1.16`

The full build command was:

`GOARCH=wasm GOOS=js tinygo build -target wasm -o web/app.wasm -size full /home/noack/go/src/go-pwa` 

I use `20.04.1-Ubuntu`

Is there some quirk i need to follow to fix this?

**Comment by Jnoack331** [comment]
I tried changing the go environment to the required go version but that did not work:

```
GOPATH=/home/noack/go/ GOROOT=/home/noack/go/go1.20.12/ tinygo version                                                                                                                                                                                                                                                                                                                                                
tinygo version 0.30.0 linux/amd64 (using go version go1.16.2 and LLVM version 16.0.1)
```

**Comment by Jnoack331** [comment]
I fixed it. I uninstalled to default go version from the ubuntu lts version by executing:
`sudo apt remove golang`

This removed the old go version from the PATH. Then i added the new go version, installed via jetbrains goland, to the path by adding the following to my `~/.zshrc` and opening a new terminal window:
`PATH="/home/noack/go/go1.20.12/bin:$PATH"`

This needs to be done because tinygo seems to select the go version via PATH instead of GOROOT.

I hope this is helpful to someone in the same situation :smile:

**Comment by aykevl** [comment]
> This needs to be done because tinygo seems to select the go version via PATH instead of GOROOT.

Correct, we just look up the `go` binary. This means that all you need to do to make sure TinyGo is working, is to make sure the `go version` command outputs the right version.

You don't need to uninstall the old version, you can also put the right directory to the start of the `$PATH` variable. For example, I have the following:

```sh
if [ -d "/usr/local/go/bin" ]; then
    PATH="/usr/local/go/bin:$PATH"
fi
```
