### ISSUE TITLE
Make three version of wasm_exec.js 

### ISSUE THREAD

**Issue by mvestnik** [tinygo-org/tinygo#4066]
Hi!
As i understand it, wasm_exec.js built using the Esbuild bundler. With a special flag you can compile a js file for node.js for browser and for node.js and browser at the same time. This is necessary to shorten wasm_exec.js file and for correct linting (eslint swears a lot). 
Can you compile the three variants? 
If there is no time, where can I get the wasm_exec.js source code instead of ready-made bundle?

**Comment by aykevl** [comment]
We don't ship a ready-made bundle, we only provide the source code (in targets/wasm_exec.js). So I don't think there's anything to fix here.
Where did you get the idea wasm_exec.js is processed by ESbuild?
