### ISSUE TITLE
type assertion panics

### ISSUE THREAD

**Issue by gggrafff** [tinygo-org/tinygo#4079]
The behavior of type assertions in tinygo differs from the standard go compiler. I get panic when I try to make a valid type assertion.

Example:
https://github.com/gggrafff/tinygo_issue

**Comment by gggrafff** [comment]
Probably it's fixed:
https://github.com/tinygo-org/tinygo/issues/3788
https://github.com/tinygo-org/tinygo/pull/3986

Let's make minor release with fixes?

**Comment by deadprogram** [comment]
@gggrafff I think we are getting very close to the next release.

**Comment by deadprogram** [comment]
Completed with `v0.31.0` so now closing. Thank you!
