### ISSUE TITLE
support newly-released go 1.22

### ISSUE THREAD

**Issue by andrewhsu** [tinygo-org/tinygo#4120]
go 1.22 was [just released](https://go.dev/blog/go1.22)

would be good to have tinygo also support that version. currently, builder has guard on version check:

https://github.com/tinygo-org/tinygo/blob/731532cd2b6353b60b443343b51296ec0fafae09/builder/config.go#L30-L34

**Comment by iapicca** [comment]
cc @aykevl

**Comment by QuLogic** [comment]
This is available in v0.31.0.
