### ISSUE TITLE
time.NewTimer() fails from init()

### ISSUE THREAD

**Issue by xudongzheng** [tinygo-org/tinygo#4123]
The following code results in a fault:

```
package main

import "time"

var timer = time.NewTimer(time.Second * 5)

func main() {
	println("Hello world!")
}
```

Issue also happens if `time.NewTimer()` is called from `init()`.

The following code works correctly

```
package main

import "time"

var timer *time.Timer

func main() {
	timer = time.NewTimer(time.Second * 5)
	println("Hello world!")
}
```

This was tested on both desktop `tinygo build -o ~/hello ~/hello.go` and RP2040 Pico.

It looks like `tn.timer.f` here is `nil`: https://github.com/tinygo-org/tinygo/blob/f4395147039fc356277399853821cb772ebda883/src/runtime/time.go#L39

**Comment by aykevl** [comment]
Thanks, here is a fix: https://github.com/tinygo-org/tinygo/pull/4134

**Comment by xudongzheng** [comment]
Thanks! Closing as I've confirmed the fix.
