### ISSUE TITLE
Official system requirements

### ISSUE THREAD

**Issue by programmingkidx** [tinygo-org/tinygo#4144]
What are the official system requirements for TinyGo? I ask that a page be dedicated to the system requirement needed to run TinyGo. I downloaded the release version on Mac OS 10.12 and was disappointed to see that TinyGo could not run due to missing symbols. 

Thank you.

**Comment by aykevl** [comment]
We don't support macOS releases that aren't supported by Apple anymore because we can't test it in CI. I'm afraid macOS 10.12 (Sierra) is no longer supported.

What you probably can do, however, is build TinyGo from source: https://tinygo.org/docs/guides/build/ - I don't see why that wouldn't work.

I'm not sure there's much to document here.

**Comment by programmingkidx** [comment]
@aykevl Thank you very much for the information. I am currently trying to build it.

**Comment by programmingkidx** [comment]
I think an informative page would answer these questions:
(all of these are the minimum version)
Mac OS version:
Windows version:
Cmake version:
clang version:
clang++ version:
libstdc++ version:
C version:
C++ version: 
llvm version:
make version:
disk space required:
suggested amount of RAM:

**Comment by aykevl** [comment]
Most of those are not relevant for binary releases, they don't depend on things like Cmake or clang.

For building from source, [this](https://llvm.org/docs/GettingStarted.html#requirements) page might be helpful. Or better yet, the [page for that particular LLVM version](https://releases.llvm.org/17.0.1/docs/GettingStarted.html#requirements).

**Comment by deadprogram** [comment]
Closing since this question appears to have been answered. Thanks everyone!
