### ISSUE TITLE
ldflag variable set will not overwrite default, even if blank

### ISSUE THREAD

**Issue by crypto-smoke** [tinygo-org/tinygo#4165]
```go
package main

import "time"

var Name ="unchanged"

func main() {
	println("name:", Name)
}

```

Run this with `tinygo run -ldflags '-X main.Name="test"'  main.go` and you get `unchanged` 
Run this with `go run -ldflags '-X main.Name="test"'  main.go` and you get `test` 

The only case where tinygo will set the variable is if it is defined as `var Name string`. Even a `var Name = ""` will keep it from being set.

**Comment by deadprogram** [comment]
Hello @crypto-smoke 

This is known, please see https://tinygo.org/docs/guides/tips-n-tricks/#how-to-set-build-time-variables

Thanks, now closing.
