### ISSUE TITLE
Joystick USB HID device - changing identity

### ISSUE THREAD

**Issue by andrewfstratton** [tinygo-org/tinygo#4179]
Firstly it's great to have so much working already...

When I use https://pkg.go.dev/github.com/tinygo-org/tinygo/src/machine/usb/hid/joystick this works fine but has an issue with identification/description, e.g.

- Using https://hardwaretester.com/gamepad, with a Badger2040, this is identified as 'Badger 2040 (Vendor: 2e8a Product: 0003)'
- this has the following effects:
  - The Buttons are shown as B0 to B15
    - ~~N.B. B16 (Home) isn't shown~~ Actually Home is mapped to B6 :)
    - Note: using a button number beyond 15 **appears to crash**
  - There are 9 Axis shown (I haven't tested these yet...)
  
Suggestion:
- Could the USB HID Descriptor be changed (by api) to allow XBox 360 (or similar) to be selected?
  - I have tested this with an 8BitDo controller, which identifies itself as 'Xbox 360 Controller (XInput STANDARD GAMEPAD)' - this then shows the capabilities as B0 to B16 (i.e. including Home button) and Axis 0 to 3
  - It seems that the USB HID Descriptor could do this - but I got lost in the detail...

**Comment by sago35** [comment]
The following may be of some assistance to you.

https://github.com/SWITCHSCIENCE/ffb_steering_controller/
https://github.com/SWITCHSCIENCE/ffb_steering_controller/blob/93c76de0c67f00f1dda0c8022c9cb2f45eb603db/control/wheel.go#L17-L30

**Comment by andrewfstratton** [comment]
I now no longer think the identity needs to change - I may add a different issue later - I'm still testing the default descriptor and trying to get one working beyond the browser test page I was using...
