### ISSUE TITLE
Hello, thank you Tinygo. Can I use ESP8266's WiFi now

### ISSUE THREAD

**Issue by pdxrlj** [tinygo-org/tinygo#4184]
Hello, thank you Tinygo. Can I use ESP8266's WiFi now

**Comment by aykevl** [comment]
No.
Please look at https://github.com/tinygo-org/tinygo/issues/1427 and https://github.com/tinygo-org/tinygo/issues/2024 instead. It's unlikely I'll ever write support for the ESP8266, but maybe for newer chips like the ESP32-C3.
