### ISSUE TITLE
//go:linkname doesn't work for already defined functions

### ISSUE THREAD

**Issue by akvlad** [tinygo-org/tinygo#4185]
Hello everyone.

I have a small test code 
```
package main

import (
	"sync"
	_ "unsafe"
)

//go:linkname get sync.(*Pool).Get
func get(p *sync.Pool) any {
	panic("GET POOL")
}

func main() {
	print("1\n")
	p := sync.Pool{}
	a := p.Get()
	_ = a
}

```

`go run main.go` works as expected: it panics

` ~/tinygo/tinygo-v0.31.2/bin/tinygo build -target wasm -o test.wasm test.go`
`node wasm_exec.js test.wasm`
this doesn't panic.

Is there a way to make this linkname directive working?

**Comment by aykevl** [comment]
I'm surprised this works in the Go toolchain. Generally it's not possible to replace a function defined in another package, at least not in TinyGo. Why are you doing this?

**Comment by akvlad** [comment]
I'm experimenting with some tiny-go GC approaches. Apparently it touches another internal aspects and I prefer not to fork the entire project, but make an extension to it.

**Comment by aykevl** [comment]
If you want to modify this, you really should modify TinyGo directly. Any other approach will likely lead to issues because TinyGo wasn't designed to be extended like this.

**Comment by akvlad** [comment]
Ok. Thanks for the information.
Feel free to close the issue then.
