### ISSUE TITLE
Flash error on M2 Mac

### ISSUE THREAD

**Issue by RiRa12621** [tinygo-org/tinygo#4216]
## Description
Trying to flash an rp2040. connected via USB-C to MicroUSB cable with the sample code to make the LED blink:

## Code

```golang
package main

import (
	"machine"
	"time"
)

func main() {
	led := machine.LED
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})
	for {
		led.Low()
		time.Sleep(time.Millisecond * 500)

		led.High()
		time.Sleep(time.Millisecond * 500)
	}
}

```

## Error

```shell
$ tinygo flash -target=nano-rp2040 main.go
error: failed to flash /var/folders/7g/rfh2cs2j4n35ztrch4hfzvq40000gq/T/tinygo658487081/main.uf2: unable to locate any volume: [RPI-RP2]
```

## System

```
$ tinygo version
tinygo version 0.31.2 darwin/arm64 (using go version go1.22.1 and LLVM version 17.0.1)
```

Same result with the latest dev build:

```
$ ./tinygo version
tinygo version 0.32.0-dev-2733e37 darwin/arm64 (using go version go1.22.1 and LLVM version 17.0.1)

```

```
$ sudo uname -a
Password:
Darwin F7MQJ63XL2 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64
```

**Comment by RiRa12621** [comment]
Quickly verified that there's no issue with the arduino itself by using the arduino IDE with a blink example:

```
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
  delay(1000);                      // wait for a second
  digitalWrite(LED_BUILTIN, LOW);   // turn the LED off by making the voltage LOW
  delay(1000);                      // wait for a second
}
```

works as expected

**Comment by RiRa12621** [comment]
Tinygo error seems to come from here https://github.com/tinygo-org/tinygo/blob/dev/main.go#L972

`flashUF2UsingMSD` called with options here https://github.com/tinygo-org/tinygo/blob/dev/main.go#L484

issue seems to be the `config.Target.FlashVolume` that's part of the config built here https://github.com/tinygo-org/tinygo/blob/dev/main.go#L374 


So we're calling the `Flash` function if the option is `flash` https://github.com/tinygo-org/tinygo/blob/dev/main.go#L1635

 the config is built https://github.com/tinygo-org/tinygo/blob/release/builder/config.go#L14 because what in there is related to this https://github.com/tinygo-org/tinygo/blob/dev/main.go#L1514

target: https://github.com/tinygo-org/tinygo/blob/release/builder/config.go#L38

Okay, so we have the flash volume in there https://github.com/tinygo-org/tinygo/blob/6384ecace093df2d0b93915886954abfc4ecfe01/compileopts/target.go#L53

Okay so we load from https://github.com/tinygo-org/tinygo/blob/release/targets/nano-rp2040.json

and then the inherits https://github.com/tinygo-org/tinygo/blob/release/targets/rp2040.json

okay, but where does the flashvolume come from? This is kinda where I'm getting lost

**Comment by deadprogram** [comment]
Via Slack:
you probably need to manually kick-in the bootloader the first time flashing that particular board
> Hold down the BOOTSEL button while plugging the board into USB.
you only need to do that once. afterwards, tinygo will detect it is being flashed and kick into bootloader mode
usually if the rp2040 board has already been flashed with something like arduino, it will also work without manual bootloader

**Comment by RiRa12621** [comment]
local machine issue: fixed by reboot
