### ISSUE TITLE
Status of support for maps

### ISSUE THREAD

**Issue by lei-april** [tinygo-org/tinygo#422]
According to https://tinygo.org/lang-support/#maps:
> A map can store at most 8 entries. The exception is when it is initialized as a global variable, in which case it can store more entries.

What would exactly happen if I initialize a map as a local variable, and then insert more than 8 entries into it?

I experimented with the following code, using the latest dev branch, and it seems to work:
```go
package main

import "strconv"

func main() {
    m := make(map[string]string)
    for i := 0; i < 100; i++ {
        k := "key" + strconv.Itoa(i)
        v := "val" + strconv.Itoa(i)
        m[k] = v
    }

    for _, v := range m {
        println(v)
    }
}
```

**Comment by aykevl** [comment]
Ah yes, the docs are outdated. Maps are now better supported and should now work for the most common cases. However, they're still pretty slow for larger maps: lookups happen linearly unless you pass the right size when you make the map (for example, with `make(map[string]string, 100)`).

Leaving this issue open as a reminder that the docs need to be updated.

**Comment by deadprogram** [comment]
This commit updated the docs https://github.com/tinygo-org/tinygo-site/commit/b80ca669e0b7f636e48a350210a3f1ece9dcc863 I an going to close this issue now. Please reopen if needed. Thank you!
