### ISSUE TITLE
latest versioning of compatible matrix of tinygo/go

### ISSUE THREAD

**Issue by hy950921** [tinygo-org/tinygo#4233]
I am using fastly to build my tinygo APP, I am having tinygo0.27.0 go golang1.20.6 installed, but having an issue with build process https://github.com/tinygo-org/tinygo/issues/2950
which needs to be fixed by tinygo0.28.0. However still having build errors while installing different versions.

**Comment by hy950921** [comment]
@orsinium, thanks for your help

**Comment by orsinium** [comment]
Could you provide a code example, steps to reproduce, `tinygo version` output, and the build command output, please?
