### ISSUE TITLE
Support LLVM 18

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#4256]
LLVM 18 has been out for a bit. Homebrew installs it by default now.

**Comment by deadprogram** [comment]
This is a new feature included in LLVM18 that I really want: https://github.com/llvm/llvm-project/pull/76777

**Comment by aykevl** [comment]
Working on it!
I actually hit a compiler bug when working on LLVM 18: https://github.com/llvm/llvm-project/issues/92648

**Comment by aykevl** [comment]
Oh and in other news: https://github.com/espressif/llvm-project/pull/94 (LLVM 18 released for Xtensa)

**Comment by aykevl** [comment]
Here it is: ~https://github.com/tinygo-org/tinygo/pull/4266~ #4271

**Comment by deadprogram** [comment]
This was released with `v0.32.0` so now closing. Thank you everyone!
