### ISSUE TITLE
Very long indexing in IDE GoLand.

### ISSUE THREAD

**Issue by eleimt** [tinygo-org/tinygo#4262]
Tell me why indexing dependencies might take a long time?
![image](https://github.com/tinygo-org/tinygo/assets/16452150/86ce7636-f5a4-4ebf-96d5-223190ed5f8c)
![image](https://github.com/tinygo-org/tinygo/assets/16452150/bb8284e2-d6d9-40ed-bf14-d1ac2a5c3a4d)
![image](https://github.com/tinygo-org/tinygo/assets/16452150/9b618540-6ca5-4f0f-bc5c-17eb6508082d)
Indexing seems endless
PC 32Gb, i5-13600K

**Comment by white0dew** [comment]
似乎是goland的版本问题，正在尝试下载之前的版本

**Comment by aykevl** [comment]
I don't know. This is really an issue with the TinyGo extension for GoLand (which we don't maintain), so this issue should be reported there.
