### ISSUE TITLE
Compiling programs SIGKILL on latest arm mac

### ISSUE THREAD

**Issue by austinabell** [tinygo-org/tinygo#4272]
commands to repro:
```console
make llvm-source && make llvm-build

# All programs crash the same
./build/tinygo build -x testdata/string.go
Killed: 9
```

Seems independent from the go version installed, I've tried a few. This worked about a week ago, and I don't think anything had changed meaningfully since then. Are there versions that are recommended, or ones I should look into configuring correctly? Tried using as close to CI build as possible, also using llvm17.

Tried reinstalling xcode completely, as well as trying many combinations of versions. Also tried the dockerfile, and that seemed to be broken?

Appreciate in advance any help :)

**Comment by austinabell** [comment]
nevermind, seemed to have been an incompatibly versioned gcc

**Comment by puhitaku** [comment]
@austinabell I've hit exactly the same problem. I'd be happy if I could know the details and how you solved the issue. Thanks!
