### ISSUE TITLE
Missing C.CBytes

### ISSUE THREAD

**Issue by hectorchu** [tinygo-org/tinygo#4284]
C.CString is present but C.CBytes is not.

Workaround is unsafe.Pointer(C.CString(string(data))) but that's ugly.

**Comment by deadprogram** [comment]
Looks like someone almost got it added here https://github.com/tinygo-org/tinygo/pull/3318

Probably we just need to rebase that PR?

**Comment by leongross** [comment]
I rebased PR #3318 since the original author was not really responsive anymore in their PR.
Here is the rebased version, all tests pass https://github.com/tinygo-org/tinygo/pull/4470.

@deadprogram would you mind giving this a review?

**Comment by leongross** [comment]
@deadprogram I think this can be closed then?

**Comment by deadprogram** [comment]
@leongross it has been labeled to be closed on the next release.

**Comment by deadprogram** [comment]
Now closing. Thanks everyone!
