### ISSUE TITLE
Cgo doesn't support bitshifted constants

### ISSUE THREAD

**Issue by hectorchu** [tinygo-org/tinygo#4285]
If I change the `#define foo 3` to `#define foo (3 << 0)` in `cgo/testdata/const.go`, the test fails with `testdata/const.go:4:17: unexpected token ILLEGAL, expected end of expression`.

**Comment by aykevl** [comment]
Thank you for the report! I have created a PR to fix this: https://github.com/tinygo-org/tinygo/pull/4286

**Comment by deadprogram** [comment]
This was released with `v0.32.0` so now closing. Thank you everyone!
