### ISSUE TITLE
wasm: -target=wasi is now trying to use GOOS=wasip1, which is not existent in Go 1.20

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#4313]
The latest release of TinyGo removed the `-target=wasi` in favor of the newer `GOOS/GOARCH` values, however those do not exist in Go 1.20 so it causes an issue for those users.

See https://github.com/tetratelabs/wazero/pull/2210#pullrequestreview-2126375711

**Comment by aykevl** [comment]
I was aware of this, but didn't think it would break too many users. Apparently I was wrong.

I should point out that Go 1.20 is not supported by the Go team anymore (so it doesn't get security updates anymore).

**Comment by aykevl** [comment]
See: https://github.com/tinygo-org/tinygo/pull/4175

**Comment by deadprogram** [comment]
Closing since it appears to have been addressed previously.
