### ISSUE TITLE
cannot use `tinygo build -ldflags "-X 'main.WASM_NAME=ws_conn.wasm'"` to modify variable WASM_NAME

### ISSUE THREAD

**Issue by longkui-clown** [tinygo-org/tinygo#4328]
when i use cmd `tinygo build -ldflags "-X 'main.WASM_NAME=ws_conn.wasm'"` to change the variable `WASM_NAME` in main package like golang, i got the return val in default val, is it not work?
![image](https://github.com/tinygo-org/tinygo/assets/39942604/ef171d79-8208-46b0-873b-8ae05fc455fd)
![image](https://github.com/tinygo-org/tinygo/assets/39942604/47f3b468-afd5-49c4-acda-a9970cfe2fd7)

**Comment by Tush-r** [comment]
The documentation mentions that if a default value is set for a variable, value passed with ldflags will be ignored. 

```
One important thing to note is that you cannot use a default value in your code if you want to be able to set that value using -ldflags. If you set the variable to a default value, then the value you pass using ldflags will be ignored.
```
Source: [How to set build-time variables](https://tinygo.org/docs/guides/tips-n-tricks/)

**Comment by longkui-clown** [comment]
thanks，i got it

**Comment by deadprogram** [comment]
Closing since the question was answered. Thank you!
