### ISSUE TITLE
Flash USB from https://play.tinygo.org/ on Chromebook?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tinygo-org/tinygo#4357]
Hi! I'm trying to flash a Pi Pico attached via USB, from https://play.tinygo.org/, on Chromebook, which supports WebUSB . The button doesn't seem to do anything. Is it supposed to work?

**Comment by deadprogram** [comment]
The playground does not support WebUSB.

So you must download the UF2 file from the playground site, boot the RP2040 into bootloader mode, then drag/drop the UF2 file to the RP2040 drive that should appear.

**Comment by GeoffreyPlitt** [comment]
How does the "flash" button work then?

**Comment by deadprogram** [comment]
It should compile and download the UF2 file to your normal "Downloads" directory.

**Comment by deadprogram** [comment]
Closing since this question was answered. Thanks!

**Comment by aykevl** [comment]
The idea is that you put the device in firmware download mode (often by double pressing the reset button, though for the Pico you need to keep the "bootsel" button pressed while connecting via USB). Then it will present itself as a mass storage device. You can then download the file to this device like any other file you download from the internet.
