### ISSUE TITLE
maps.Clone link error (missing maps.clone)

### ISSUE THREAD

**Issue by ldemailly** [tinygo-org/tinygo#4382]
Using https://pkg.go.dev/maps#Clone (present since go 1.21)

macOS:

ld.lld: error: undefined symbol: _maps.clone

wasm:

wasm-ld: error: undefined symbol: maps.clone

**Comment by dgryski** [comment]
Need to add https://github.com/golang/go/blob/release-branch.go1.23/src/runtime/map.go#L1616 to our runtime (specialized for our own map implementation of course)
