### ISSUE TITLE
ci: error while loading shared libraries: libLLVM-17.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leongross** [tinygo-org/tinygo#4515]
In the ci the `nix-test` step fails with the following error [1]

```
/home/runner/go/bin/tinygo: error while loading shared libraries: libLLVM-17.so.1: cannot open shared object file: No such file or directory
```

The `Restore LLVM source cache` uses LLVM v.18, so we should bump the version here.

[1]: https://github.com/tinygo-org/tinygo/actions/runs/11272306601/job/31346952510?pr=4378#step:8:108

**Comment by aykevl** [comment]
> The `Restore LLVM source cache` uses LLVM v.18, so we should bump the version here.

We use LLVM 18, so this is correct.
