### ISSUE TITLE
Devices/esp missing?

### ISSUE THREAD

**Issue by MrNavaStar** [tinygo-org/tinygo#4528]
Most of the directories under devices have a [device name].go that has all of the memory registers mapped out. The esp ones seem to be missing from the repo.

I am trying to work on my esp canbus driver, however I am stuck on this. Any help appreciated. 

Thanks

**Comment by sago35** [comment]
You should probably run `make gen-devices`.

https://tinygo.org/docs/guides/build/additional-requirements/

**Comment by MrNavaStar** [comment]
Thanks so much, this seems like what I was looking for
