### ISSUE TITLE
darwin releases missing wasm-opt?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#4551]
Shades of https://github.com/tinygo-org/tinygo/issues/3977, but for darwin:

```
% tar -tf ~/Downloads/tinygo0.33.0.darwin-arm64.tar.gz | grep -i wasm-opt || echo bupkis
bupkis
% tar -tf ~/Downloads/tinygo0.33.0.darwin-amd64.tar.gz | grep -i wasm-opt || echo bupkis 
bupkis
% tar -tf ~/Downloads/tinygo0.33.0.linux-amd64.tar.gz | grep -i wasm-opt || echo bupkis 
tinygo/bin/wasm-opt
```

Persists in 0.34-pre

**Comment by deadprogram** [comment]
The homebrew recipe installs it https://github.com/tinygo-org/homebrew-tools/blob/master/tinygo.rb#L6

**Comment by dkegel-fastly** [comment]
Right.  I guess that's how most people get it, so including it in the tarball is low priority.

I use brew for everything but go and tinygo, I don't trust it to not screw up... otherwise I wouldn't have noticed.

**Comment by deadprogram** [comment]
@dkegel-fastly is there some action required here or can we close this issue?

**Comment by deadprogram** [comment]
Closing since it is not the typical use case.
