### ISSUE TITLE
os Args are not implemented

### ISSUE THREAD

**Issue by talentlessguy** [tinygo-org/tinygo#456]
I tried to compile Go program with `cli` package but it requires `os.Args` in `flag.go`

`os.Args` is used [here](https://github.com/golang/go/blob/f518a96e009157c51f8ecf619032bbb7873228f9/src/flag/flag.go#L579)

**tinygo version**: tinygo version 0.7.0 linux/amd64

**Comment by deadprogram** [comment]
I am going to close this as a duplicate, as https://github.com/tinygo-org/tinygo/issues/541 has a slightly more complete discussion.

**Comment by talentlessguy** [comment]
@deadprogram okay
