### ISSUE TITLE
Version parsing fails for Go betas

### ISSUE THREAD

**Issue by QuLogic** [tinygo-org/tinygo#458]
With Go 1.13beta1 installed, tinygo smoketests fail when [parsing the version](https://kojipkgs.fedoraproject.org//work/tasks/3072/36453072/build.log):

> error: could not read version from GOROOT (/usr/lib/golang): failed to parse minor version: strconv.Atoi: parsing "13beta1": invalid syntax

**Comment by deadprogram** [comment]
I'm not sure that we support running TinyGo inside anything but the currently released Go, but that seems like something that could be changed. Also useful for testing with the next version of Go.

**Comment by aykevl** [comment]
I think it would be useful to support this, for testing newer versions. Patches are welcome :)
And yes, TinyGo only has been tested with Go 1.11 and Go 1.12.

**Comment by deadprogram** [comment]
This has been addressed in the `dev` branch, thanks to @QuLogic 

I will close this issue now. Thanks for the PR!
