### ISSUE TITLE
Slice out of range when calling `encoding/pem.Decode`

### ISSUE THREAD

**Issue by rellfy** [tinygo-org/tinygo#4583]
Hello,

I am compiling some code to WASM (WASI p1 specifically), [see the original code function here](https://github.com/coinbase/cdpcurl/blob/master/internal/auth/auth.go#L41) -- only this function and its direct requirements are ported to WASM, not the entire program in that repo btw.

The code involves a few libs like `encoding/pem`, `crypto/x509` etc. I see that while TinyGo compiles `encoding/pem`, [there are test errors at runtime](https://tinygo.org/docs/reference/lang-support/stdlib/#encodingpem) (`panic: unimplemented: (reflect.Type).NumOut()`), but this is not what I am getting and I was hoping the part of `encoding/pem` I require (`pem.Decode`) does not require reflection (which, from what I looked, it does not, but I could be wrong).

I get this error thrown once the function above reaches `pem.Decode`:

```
panic: runtime error: slice out of range
2024-11-05T00:50:10.448131Z ERROR error while executing at wasm backtrace:
    0: 0x214a2 - runtime.abort
                    at ~/.local/tinygo/src/runtime/runtime_tinygowasm.go:78:6              - runtime.runtimePanicAt
                    at ~/.local/tinygo/src/runtime/panic.go:90:7
    1: 0x3170 - runtime.slicePanic
                    at ~/.local/tinygo/src/runtime/panic.go:177:16
    2: 0x10d148 - (*main.ApiKey).BuildJWT
    3: 0x1067dc - main!entry_point
```

My host environment is Rust/Wasmtime.
`tinygo version 0.34.0 linux/amd64 (using go version go1.23.2 and LLVM version 18.1.2)`

Is `pem.Decode` supposed to throw this error in the current TinyGo version? Otherwise, something else is wrong with my code that can hopefully be fixed separately. Because the error message I get is not the same as indicated in TinyGo's website, I am not sure what is the cause of the problem. I would like to note that once compiled as a regular linux program, the same code runs fine.

**Comment by dgryski** [comment]
The `encoding/pem` package passes tests (after commenting out the Fuzz test that requires `testing/quick`):
```
~/go/src/go.googlesource.com/go/src/encoding/pem $ tinygo test encoding/pem
ok  	encoding/pem	1.527s
~/go/src/go.googlesource.com/go/src/encoding/pem $ git diff
diff --git a/src/encoding/pem/pem_test.go b/src/encoding/pem/pem_test.go
index 56a7754b22..a9a5268329 100644
--- a/src/encoding/pem/pem_test.go
+++ b/src/encoding/pem/pem_test.go
@@ -236,6 +236,7 @@ func TestLineBreaker(t *testing.T) {
 }

 func TestFuzz(t *testing.T) {
+       return
        // PEM is a text-based format. Assume header fields with leading/trailing spaces
        // or embedded newlines will not round trip correctly and don't need to be tested.
        isBad := func(s string) bool {
```

Can you provide a smaller reproducer of the failing code?  It could be something else -- like a missing error check or unexpected nil value.

**Comment by rellfy** [comment]
Hey @dgryski, thanks for your response.

I was debugging this and realised that the function could be called just fine through the `start` function, if I compiled it with:

```bash
tinygo build -o module.wasm -target=wasi
```
However in my use case I don't actually use the start function, I expose other functions that are called by the program (like `entry_point` seen in my logs above).

So it was very weird because the exact same code worked fine in `start` but not in `entry_point`.

I was able to fix it by building it with

```bash
tinygo build -o module.wasm -target=wasi -buildmode=c-shared
```

Which exports the `_initialize` function instead of `_start`. I had to explicitly call `_initialize` in my host runtime, but then it works fine.

I hope this is useful info for anyone else that happens to run across this issue. I can't tell if there is something wrong on the side of TinyGo, or if it was an error on my side.

**Comment by aykevl** [comment]
This is working as intended. Indeed you can't export functions and call them without first calling `_initialize` or `_start`.

If you used `//go:wasmexport` you _should_ have gotten a panic saying the runtime wasn't initialized. Did you use `//export` or `//g:wasmexport`?

**Comment by rellfy** [comment]
@aykevl I ended up using both exports as I was going back and forth between Go and TinyGo.

Btw just to be clear, I had the issue even if I called `_start` and then called an exported function. I was only able to get it to work by calling `_initialize`, without `fn main`. This is what I wanted so I'm happy, but it seems a bit weird to me that no other exported functions would work properly if using `_start`.

**Comment by aykevl** [comment]
> Btw just to be clear, I had the issue even if I called `_start` and then called an exported function.

Huh odd. That should not happen. If this is still an issue for you, feel free to create a new issue for this.

**Comment by inliquid** [comment]
@rellfy did you try to run it with Wazero? We build a production solution based on `tinygo` + Wazero with classic approach using "Command" modules (`_start` + exports) as opposed to "Reactor" modules (`_initialize` + exports) and everything works.

There is also interesting [note](https://github.com/tetratelabs/wazero/blob/main/RATIONALE.md#why-do-we-only-return-a-sysexiterror-on-a-non-zero-exit-code) in documentation. Not sure, however that it's related to you case:

> ### Why do we only return a sys.ExitError on a non-zero exit code?
> It is reasonable to think an exit error should be returned, even if the code is success (zero). Even on success, the module is no longer functional. For example, function exports would error later. However, wazero does not. The only time sys.ExitError is on error (non-zero).
> This decision was to improve performance and ergonomics for guests that both use WASI (have a _start function), and also allow custom exports. Specifically, Rust, TinyGo and normal wasi-libc, don't exit the module during _start. If they did, it would invalidate their function exports. This means it is unlikely most compilers will change this behavior.
> GOOS=waspi1 from Go 1.21 does exit during _start. However, it doesn't support other exports besides _start, and _start is not defined to be called multiple times anyway.

**Comment by aykevl** [comment]
Oh right I see, you can't call exported functions after `_start` returns (it may or may not work, but it is not defined behavior). If you want to call those, it's only valid to do this from within `_start` (so you could call a `//go:wasmimport` function from Go, and that imported function could then call an exported function).
