### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by jwenz723** [tinygo-org/tinygo#465]
I am new to tinygo (just got introduced at Gophercon San Diego) and am wondering what the suggested IDE/editor is for writing tinygo programs?

I usually use Intellij, but the problem with continuing to use it for tinygo coding is that it does not know where to look for the "machine" package or the other tinygo specific packages so I end up with a bunch of highlighted errors all over my code. I tried to modify GOROOT to point at the tinygo directory (the directory that contains the `src` folder). Unfortunately, Intellij fails to set the GOROOT with an error of "The selected directory is not a valid home for Go SDK".

I am hoping to be able to get code hints in an editor and wondering if this is possible. I'm ok with using an alternate editor if that is required.

**Comment by aykevl** [comment]
I'm usually using vim so no IDE, but I hope to work together with @ramya-rao-a soon to support this. One solution could be to rename TinyGo-specific packages so it becomes something like tinygo.org/machine. Currently you should be able to import github.com/tinygo-org/tinygo/src/machine as a workaround.
