### ISSUE TITLE
testing package does not support Benchmarks

### ISSUE THREAD

**Issue by 13rac1** [tinygo-org/tinygo#491]
The following test file:

```golang
package main

import (
	"testing"
)

func BenchmarkTest(b *testing.B) {
}
```

Fails with:
```
$ tinygo test
# github.com/user/test
main_test.go:7:31: B not declared by package testing
```

Would be nice if the test file would compile, but ignore Benchmarks. ~Probably a good starter PR for myself.~ Done.

*Definitely a low priority issue for now*

**Comment by deadprogram** [comment]
This has been released with 0.8.0 so now closing. Thank you.
