### ISSUE TITLE
Teensy: 4.0 support

### ISSUE THREAD

**Issue by wdevore** [tinygo-org/tinygo#512]
Hi, is there any effort in progress or planned for supporting the **Teensy 4.0** board?
It uses the *ARM Cortex-M7*.

Thanks.

**Comment by aykevl** [comment]
Hi @wdevore, there is no support right now but multiple people have requested it.
Step one is this PR: https://github.com/posborne/cmsis-svd/pull/82

**Comment by deadprogram** [comment]
That PR was merged into the cmsis-svd repo, so now it can be brought into TinyGo to generate the device wrapper.

**Comment by firelizzard18** [comment]
In #863, I tweaked the generator, so `src/device/nxp/mimxrt1062.go` is now generated, but there's a lot of work to do, most of which I am unfamiliar with

**Comment by jbpratt** [comment]
I think this can be closed, there is now a `teensy40` target!

**Comment by deadprogram** [comment]
Indeed! Now closing.
