### ISSUE TITLE
Blocking interface calls

### ISSUE THREAD

**Issue by jadr2ddude** [tinygo-org/tinygo#514]
Whenever we create a blocking implementation of an interface (at least with the mode using LLVM coroutines), this generates an inconsistency which prevents the code from compiling. We need to properly make interface wrappers blocking when necessary.

**Comment by jadr2ddude** [comment]
This is a prerequisite for making mutexes block.

**Comment by deadprogram** [comment]
Has this now been implemented?

**Comment by aykevl** [comment]
I don't think so. I haven't done any work in that area.
