### ISSUE TITLE
Import cycle with Go 1.13

### ISSUE THREAD

**Issue by QuLogic** [tinygo-org/tinygo#519]
With #458 fixed, the next issue is that compiling a smoketest fails due to an import cycle:
```
+ make smoketest AVR=0 RISCV=0
# test all examples
tinygo build -size short -o test.elf -target=pca10040            examples/blinky1
error: import cycle:
	examples/blinky1
	machine
	errors
	internal/reflectlite
	runtime
	machine
 at $TINYGOROOT/src/runtime/runtime_nrf.go:8:2
```

**Comment by DestyNova** [comment]
Unsurprisingly, it also doesn't work with Go 1.13 which was released about 2 days ago.

**Comment by deadprogram** [comment]
Hello @QuLogic please also test your issue with this PR and go1.13 to see if it has been corrected:

https://github.com/tinygo-org/tinygo/pull/585

**Comment by deadprogram** [comment]
The Go1.13 PR is now in the `dev` branch, so please try it out there.

Thanks!

**Comment by QuLogic** [comment]
This is working in the `dev` branch.
