### ISSUE TITLE
Unsupported instructions in wasm with Go 1.13 rc1

### ISSUE THREAD

**Issue by QuLogic** [tinygo-org/tinygo#521]
I haven't figured out #519 yet, but with the wasm smoketest, it doesn't invoke the import cycle. It does run into a slice issue, but this can be fixed by backporting #472 and #502. Once that's done though, it seems that there are some new unsupported instructions:

```
# make smoketest
tinygo build             -o wasm.wasm -target=wasm               examples/wasm/export
unsupported instruction during init evaluation:
  %invoke.func.cast = inttoptr i32 %invoke.func to %runtime._interface (i8*, i8*, i8*)*, !dbg !10
```

Note this is with 0.7.1 + the above patches. I might try out the `dev` branch in a little bit as well, to see if something else might have fixed it.

**Comment by deadprogram** [comment]
Hi @QuLogic if you have a chance please try out this PR with go1.13:

https://github.com/tinygo-org/tinygo/pull/585

Thanks!

**Comment by deadprogram** [comment]
The Go1.13 PR is now in the `dev` branch, so please try it out there.

Thanks!

**Comment by QuLogic** [comment]
This is working in the `dev` branch.
