### ISSUE TITLE
Runtime error when using reflect.Field()

### ISSUE THREAD

**Issue by lei-april** [tinygo-org/tinygo#530]
The following code:
```go
package main

import "reflect"

type Foo struct {
	Bar int
}

func main() {
	f := Foo{12345}
	v := reflect.ValueOf(f)
	i := v.Field(0).Interface()
	println(i.(int))
}
```

when compiled with TinyGo, panics at runtime:
```
panic: runtime error: type assert failed
```

Any clue?

**Comment by deadprogram** [comment]
Is this also an issue in the current `dev` branch, @lei-april ?

**Comment by lei-april** [comment]
> Is this also an issue in the current `dev` branch, @lei-april ?

Yes. Sorry I forgot to mention that.

The `reflect.Field` function isn't implemented in the `master` branch yet.

**Comment by deadprogram** [comment]
I just verified that this has been addressed in the `dev` branch already, so now closing. Thanks!
