### ISSUE TITLE
still I was faced this issue . #309

### ISSUE THREAD

**Issue by SuryaprakashBS** [tinygo-org/tinygo#540]
still I was faced this issue in dev branch . #309

_Originally posted by @SuryaprakashBS in https://github.com/tinygo-org/tinygo/issues/309#issuecomment-528205301_

**Comment by deadprogram** [comment]
This code has not yet been released, @SuryaprakashBS please try the `dev` branch to get this update.

Closing as duplicate, thanks!

**Comment by SuryaprakashBS** [comment]
Bro I was faced this issue in *dev* branch . So please check this issue for all cases.

**Comment by aykevl** [comment]
If you can give a small case that reproduces this issue in the dev branch, we can take another look. But as far as I'm aware, it should be fixed.
