### ISSUE TITLE
How to parse cli arguments?

### ISSUE THREAD

**Issue by dongweigogo** [tinygo-org/tinygo#541]
Since tinygo does not support flag package currently, is there a way to get around this problem?

**Comment by aykevl** [comment]
Exactly, we need to add support for the `os.Args` array, which should be initialized from here:

https://github.com/tinygo-org/tinygo/blob/7d481c179faa35c9b2d53774a2d13f923cd50591/src/runtime/runtime_unix.go#L47-L48

**Comment by talentlessguy** [comment]
hi, any progress on this?

**Comment by deadprogram** [comment]
I know that the Args stubs were merged. Has anyone tried to implement the needed OS support for linux or darwin (or windows)?

**Comment by aykevl** [comment]
See #1410.

**Comment by deadprogram** [comment]
This was released with v0.18 so now closing. Thank you!
