### ISSUE TITLE
flash: perform 1200 baud reset before flashing for platforms that support it

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#614]
I propose that we add a new key to the target that support it named `flash-1200-bps-reset`.

The purpose of this key will be to toggle the serial port to 1200 baud, which on many platforms such as Arduino and Adafruit will kick the board into the bootloader mode for flashing without having to tap the reset button on the board.

We can use an implementation similar to that used by the Arduino CLI that uses the serial package `go.bug.st/serial.v1`

See https://github.com/arduino/arduino-cli/blob/master/commands/upload/upload.go#L258 for details.

**Comment by aykevl** [comment]
Fixed by #616.
