### ISSUE TITLE
wasm_exec: copyBytesToJS is missing

### ISSUE THREAD

**Issue by ktye** [tinygo-org/tinygo#631]
for 0.9.0 which uses go 1.13, the new methods copyBytesToJS and CopyBytesToGo are missing in wasm_exec.js

**Comment by EntityB** [comment]
Also it seems that `wasm_exec.js` is quite different now and might be incompatible in other ways.

**Comment by deadprogram** [comment]
That is likely true, hence my comment in https://github.com/tinygo-org/tinygo/issues/645#issuecomment-546289779

**Comment by deadprogram** [comment]
This code has now been released, so closing. Thanks!

**Comment by aykevl** [comment]
Pretty sure it's not: https://github.com/tinygo-org/tinygo/pull/702

**Comment by deadprogram** [comment]
Oops. Reopening, then.

**Comment by justinclift** [comment]
In theory, this should be fixed by #933. :smile:

**Comment by deadprogram** [comment]
This has now been released, so now closing. Thanks!
