### ISSUE TITLE
wasm_exec: publish to npm 

### ISSUE THREAD

**Issue by darky** [tinygo-org/tinygo#642]
In javascript community npm used for fetch javascript packages

**Comment by aykevl** [comment]
Why?
The wasm_exec.js file is compiler specific and should always be copied from targets/wasm_exec.js. It may change with every TinyGo release. It doesn't make sense to put it in a dependency management system.

**Comment by darky** [comment]
> The wasm_exec.js file is compiler specific

Why it reason not push it to npm?

> should always be copied from targets/wasm_exec.js

It's very annoying for js developer. 99,9% of packages I fetch from npm, but for `wasm_exec.js` need special way

> It may change with every TinyGo release

You can update `wasm_exec.js` for every TinyGo release.

Example of Golang `wasm_exec.js`: https://www.npmjs.com/package/@woodenfish/golang-wasm_exec

**Comment by darky** [comment]
Ok, I think this task more related to JavaScript community instead of Golang community.
I think it can be resolved via thrird party person like this example https://www.npmjs.com/package/@woodenfish/golang-wasm_exec
