### ISSUE TITLE
wasm_exec: avoid use Go in global

### ISSUE THREAD

**Issue by darky** [tinygo-org/tinygo#644]
Mutate global object, it's bad taste in javascript community.
Good case, to use commonjs or EcmaScript modules for this purposes.

**Comment by aykevl** [comment]
Which global do you mean?

**Comment by darky** [comment]
This place https://github.com/tinygo-org/tinygo/blob/8a771e3f89679e32aa1f7eeaf630fe1263b91803/targets/wasm_exec.js#L74

Would be better: `export class Go ...`

**Comment by jccit** [comment]
Using ES modules here doesn't make much sense, since the wasm_exec.js is not expected to be ran through a bundler. I just tried to build it with webpack and wouldn't compile due to webpack tripping the `isNodeJS` variable.

**Comment by darky** [comment]
Ok, I think refactor `wasm_exec.js` to proper format is unnecessary
