### ISSUE TITLE
How can I build a go binary file with tinygo and the binary file can run on an embedded linux?

### ISSUE THREAD

**Issue by TonyAsian** [tinygo-org/tinygo#652]
In my situation, there is an embedded linux OS on my ARM processor, so I cannot flash the binary code to the flash directly.

**Comment by jadr2ddude** [comment]
So if you run the tinygo compiler on an ARM system, you can run:
```
tinygo build -o someProgram.elf my/package
```

Then `someProgram.elf` is a runnable linux executable.

**Comment by TonyAsian** [comment]
@jadr2ddude Thank you! I'll try it.

**Comment by aykevl** [comment]
Did you try setting the GOARCH variable? That should work.

```
GOARCH=arm tinygo build -o someProgram.elf my/package
```

You may need to install cross compilation tools (like `arm-none-eabi-gcc`).

**Comment by deadprogram** [comment]
Closing this issue due to age and also that this question has been answered in other places. Please reopen if needed. Thanks everyone!
