### ISSUE TITLE
Wasm only compile error: function is already defined:internal/bytealg.CountString

### ISSUE THREAD

**Issue by justinclift** [tinygo-org/tinygo#699]
With current TinyGo dev branch, using `strings.Split()` causes a compile failure when compiling to wasm:

```
$ tinygo build -target wasm -o foo main.go
../../../../../../../usr/local/go/src/internal/bytealg/count_generic.go:19:6: function is already defined:internal/bytealg.CountString
$ go version
go version go1.13.4 linux/amd64
```

The compile failure **only** happens when the target is `wasm`.  Without `-target wasm`, the compilation will succeed.

A minimal 100% reproducer:

```
package main

import (
	"strings"
)

func main() {
	s := strings.Split("An example string", "\n")
	println(len(s))
}
```

**Comment by justinclift** [comment]
That reproducer also fails when run in the TinyGo playground, so it's not just me (wasn't sure). :smile:

**Comment by aykevl** [comment]
I think this problem was introduced with the following PR: https://github.com/tinygo-org/tinygo/issues/424

**Comment by justinclift** [comment]
Thanks @aykevl, #424 did fix this. :smile:
