### ISSUE TITLE
sync: mutex does not yet support Lock() from multiple goroutines

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#722]
```
panic: todo: block on locked mutex
```

**Comment by jadr2ddude** [comment]
The current problem blocking this is async interface calls. Some things using interfaces break right now when they try to use a blocking mutex because of this.

**Comment by jadr2ddude** [comment]
Since #736 is merged in, this should be fairly trivial to implement. The naïve solution would be to put a channel in the mutex. It would also be possible to make an efficient version by directly manipulating tasks, but that would require #607 to be merged in first.

**Comment by jaddr2line** [comment]
This should be fixed once #881 is merged.

**Comment by niaow** [comment]
PR #881 has been merged so this has been fixed.
