### ISSUE TITLE
Deb package does not set path to tinygo command

### ISSUE THREAD

**Issue by kgolding** [tinygo-org/tinygo#725]
After a fresh install on Kubuntu 19.04, the tinygo command is not in the PATH and thus can't be easily run.

The proposal is to add a symlink like so `ln -s /usr/local/tinygo/bin/tinygo .`

**Comment by deadprogram** [comment]
Since tinygo does not run well as a symlink, we need to handle this by either adding to PATH or making sure we document it.

@aykevl what do you think?

**Comment by aykevl** [comment]
IIRC TinyGo can work just fine with a symlink. A symlink should be created by the .deb package, but I haven't looked into how to do that with `fpm`.

**Comment by deadprogram** [comment]
At least one person ran into this problem recently at SCaLE who had installed the `deb package.

**Comment by aykevl** [comment]
I have a fix in #1107.

**Comment by deadprogram** [comment]
This was released with v0.14.0 so now closing. Please reopen if needed. Thanks!
