### ISSUE TITLE
Add Runtime Error Interface

### ISSUE THREAD

**Issue by bgokden** [tinygo-org/tinygo#752]
I would like to add Runtime Error interface defined here: https://golang.org/pkg/runtime/#Error
to solve the problem of compiling text/template/parse as defined here: https://tinygo.org/lang-support/stdlib/#text-template-parse

I am testing some wasm libraries and they include text-template-parse. Adding this error interface may solve the problem.

**Comment by aykevl** [comment]
That would be a welcome improvement! You could add it to src/runtime/panic.go.

For the `runtime.Error` type, see: https://golang.org/ref/spec#Run_time_panics

Note that TinyGo doesn't currently use such a type and honestly there isn't really a good reason to until it supports the `recover()` builtin. So the main benefit to having this type would be to get existing code to compile.

**Comment by yznts** [comment]
I understand that it's not `tinygo` main domain, but I'm exploring possibility of using this compiler to build WASM modules for edge workers. And I'm really missing `html/template`. Maybe there is some ETA to bring this standard lib into `tinygo`?

**Comment by dgryski** [comment]
`text/template` relies heavily on `reflect` which is one of tinygo's weak points. You might be better off looking for a code-generation template library if possible.

**Comment by yznts** [comment]
Ok, I understand. Many thanks for reply!

**Comment by deadprogram** [comment]
This was addressed quite some time back so now closing. Thanks everyone!
