### ISSUE TITLE
Package/symbol name problem

### ISSUE THREAD

**Issue by j7b** [tinygo-org/tinygo#76]
Test program tst.go:
```
package main

func x() int

func main() {
        println(x())
}
```

Build ```tinygo build -target wasm -o withfile.ll tst.go``` output contains:
```declare i32 @main.x() local_unnamed_addr``` as expected, import object key 'main.x'

Build ```tinygo build -target wasm -o withdot.ll .``` output contains:
```declare i32 @..x() local_unnamed_addr``` import object key '..x'

**Comment by deadprogram** [comment]
Is this still a problem? Also is it specific to WASM?

**Comment by aykevl** [comment]
It is not specific to WebAssembly, but you wouldn't generally notice it otherwise.
I hope it is gone after #89 but I'm not entirely sure, I haven't tested this.

**Comment by aykevl** [comment]
Most likely not, I didn't touch that code (and I've seen the issue myself recently).

**Comment by jaddr2line** [comment]
What is the intended behavior here? Right now, when building, it compiles and the linker just complains about the symbol not being found.

**Comment by aykevl** [comment]
It would be nice to name the main package `main`, so you have the symbol `main.main`. This is what the Go toolchain does. I haven't seen a direct need for this, however.

**Comment by jaddr2line** [comment]
Okay I guess I just misunderstood the issue.

**Comment by deadprogram** [comment]
OK I must be missing something here: https://play.golang.org/p/jqxNrK9fi_R

The output of the submitted test program does not work on the normal Go Playground either:

```
./prog.go:3:6: missing function body

Go build failed.
```

I feel like for the first time I am questioning what exactly this issue is about? Can anyone please clarify? Thank you.

**Comment by niaow** [comment]
This now seems to produce the expected name.

> The output of the submitted test program does not work on the normal Go Playground either:

The standard Go implementation requires an assembly file to be included in the package to allow this.

It would probably be more correct for this to use `//export` or similar though.

**Comment by dgryski** [comment]
Agree.  This is fixed I'm pretty sure.
```
~/go/src/github.com/dgryski/bug $ tinygo build -target wasm -o withdot.ll .
~/go/src/github.com/dgryski/bug $ grep 'declare i32.*x.*local_unnamed' withdot.ll
declare i32 @main.x(ptr) local_unnamed_addr #2
```
