### ISSUE TITLE
How to disable CGO?

### ISSUE THREAD

**Issue by xaionaro** [tinygo-org/tinygo#771]
Hello.

I need to set something like `CGO_ENABLED=0`. There's some code that has different implementations for cases if CGo is supported (`+build cgo`) and if CGo is not supported (`+build !cgo`). And I need to compile the second variant. It would be nice if you would help me to understand how can I do it without manually modifying all my dependencies (which could use CGo)?

**Comment by deadprogram** [comment]
I'm not sure you can compile a TinyGo program without CGo support at this time. @aykevl can confirm or correct that.

**Comment by aykevl** [comment]
That's correct, CGo support cannot currently be disabled.

Ideally I hope to make CGo "just work" (more reliably than the standard Go toolchain), but we're not there yet. Until that time, adding support for `CGO_ENABLED` seems sensible.

**Comment by aykevl** [comment]
@xaionaro can you test this PR? https://github.com/tinygo-org/tinygo/pull/821

**Comment by xaionaro** [comment]
@aykevl : As experiment I've tried to make similar changes within tinygo (as in the PR) and it didn't help. But I was hurrying so I suppose I just missed something. Yes, I will test it within a week. Thank you :)

**Comment by xaionaro** [comment]
Sorry for the late answer. It works. Thank you.
