### ISSUE TITLE
Driver request for DHT-11 and DHT-22

### ISSUE THREAD

**Issue by homebrew79** [tinygo-org/tinygo#835]
I would like to request a driver for the DHT-11 and DHT-22 Temperature/Humidity sensor. I have seen a few libraries on github for go, but they seem to be specific to raspberry pi.

**Comment by deadprogram** [comment]
Hi @homebrew79 I suggest adding this issue to the TinyGo drivers repo here, please: https://github.com/tinygo-org/drivers

Thanks!

**Comment by homebrew79** [comment]
Will do. Thanks
