### ISSUE TITLE
undeclared name: C.CString

### ISSUE THREAD

**Issue by gertcuykens** [tinygo-org/tinygo#854]
I will create repo later to have full example. Here is just `main.go` for now that works in normal go but not in tinygo (latest dev branch)

```sh
% tinygo build -o a.out
# c
main.go:13:7: undeclared name: C.CString
main.go:15:12: cannot initialize 2 variables with 1 values
main.go:17:11: undeclared name: C.hello
main.go:19:11: undeclared name: C.hello3
```

```go
package main

// #cgo CFLAGS: -D BUILD=5
// #include <stdlib.h>
// #include "file.h"
// #include "hello.h"
// #include "cgo_hello.h"
import "C"
import "unsafe"
import "fmt"

func main() {
	s := C.CString("unexist.txt")
	defer C.free(unsafe.Pointer(s))
	n, err := C.file(s)
	fmt.Println(n, err)
	n, err = C.hello()
	fmt.Println(n, err)
	n, err = C.hello3()
	fmt.Println(n, err)
}

//export hello2
func hello2() int{
	fmt.Println("hello from go")
	return 0
}
```
PS maybe introduce a github cgo label to tag all cgo issues. Thanks

**Comment by aykevl** [comment]
Yes these helper functions have not been implemented yet. They're blocked on libc support, which I'm working on in #845 and #849.

**Comment by hammadtq** [comment]
Hey @aykevl are these available yet or do you know the workaround? I am getting this error on the latest release `undeclared name: C.CString`

**Comment by bgould** [comment]
These functions aren't yet implemented by the compiler but libc support does exist on all TinyGo platforms now so it is possible to implement this functionality such as https://github.com/bgould/go-littlefs/blob/master/go_lfs.go#L415-L430 as a workaround

**Comment by deadprogram** [comment]
I am pretty sure this feature now exists ever since libc support was merged. Now closing, please reopen if needed. Thanks!

**Comment by aykevl** [comment]
No, this feature has not yet been implemented. Libc support is now in place (which is a prerequisite), but this feature still doesn't exist in TinyGo.

**Comment by aykevl** [comment]
See https://github.com/tinygo-org/tinygo/pull/2249
