### ISSUE TITLE
Wasm: cwa_main vs _start

### ISSUE THREAD

**Issue by vshymanskyy** [tinygo-org/tinygo#866]
As far as I understand, `_start` should be the entry function (at least is now commonly used in wasm world). However in TinyGo:
https://github.com/tinygo-org/tinygo/blob/da857108947aa35ff6e6b5ce16c96359e72fe47c/src/runtime/runtime_wasm.go#L25-L34

I'm wondering if that could be changed.

**Comment by vshymanskyy** [comment]
Or maybe, `_start` should just call `callMain()` as well...

**Comment by aykevl** [comment]
Yes I agree, as in #868 it's a leftover from [CommonWA](https://github.com/CommonWA/cwa-spec). It is removed in #873.

**Comment by vshymanskyy** [comment]
Fixed. Thanks!
