### ISSUE TITLE
Wasm: env.io_get_stdout gets called and then the result is dropped

### ISSUE THREAD

**Issue by vshymanskyy** [tinygo-org/tinygo#868]
In the `initAll` function, I get these wasm instructions:
```
    call $env.io_get_stdout
    drop
```
it wouldn't bother me too much, but this also creates:
```
(import "env" "io_get_stdout" (func $env.io_get_stdout (type $t3)))
```

Would it be possible to have some flag to eliminate it?

**Comment by aykevl** [comment]
I have created #873, which addresses this. The `io_get_stdout` is a leftover from [CommonWA](https://github.com/CommonWA/cwa-spec) which has practically been superseded by WASI.

**Comment by vshymanskyy** [comment]
Fix confirmed
