### ISSUE TITLE
"llvm-ar-9" does not exist on Arch/Manjaro

### ISSUE THREAD

**Issue by jaddr2line** [tinygo-org/tinygo#882]
In #845 we added a build of wasi-libc to the tinygo build. The build uses the commands `llvm-ar-9` and `llvm-nm-9`, however on Arch/Manjaro these are called `llvm-ar` and `llvm-nm` instead. This can be worked around using environment variables for now, but we should add a workaround for this before we release.

**Comment by aykevl** [comment]
This is now fixed by #902 and will be included in the next release.
