### ISSUE TITLE
tinygo flash on linux does not work

### ISSUE THREAD

**Issue by mickey-happygolucky** [tinygo-org/tinygo#885]
i tried to flash the  program to STM32F4Discovery on linux.
however I faced error as follows.

```txt
$  tinygo flash --target stm32f4disco examples/blinky1
error: unable to locate a USB device to be flashed
```

this error means tinygo could not find default flash port such a `/dev/ttyACMx`.

https://github.com/tinygo-org/tinygo/blob/master/main.go#L150-L153

I believe this cheking is not need it for devices that does use the openocd to flash the program like a STM32F4Discovery.

this code was added by  34ee3883d64da99e216ed478d72556ef76274851

but i cannot understand this check is need.
I think ttyACMx does not always exist.

I  modifed code as follows and tried.

```diff
@@ -146,11 +146,12 @@ func Test(pkgName string, options *compileopts.Options) error {
 // Flash builds and flashes the built binary to the given serial port.
 func Flash(pkgName, port string, options *compileopts.Options) error {
        if port == "" {
-               var err error
-               port, err = getDefaultPort()
-               if err != nil {
-                       return err
-               }
+               //              var err error
+               //              port, err = getDefaultPort()
+               port, _ = getDefaultPort()
+               // if err != nil {
+               //      return err
+               // }
        }
 
        config, err := builder.NewConfig(options)
@@ -470,7 +471,7 @@ func flashUF2UsingMSD(volume, tmppath string) error {
        }
        if d == nil {
                return errors.New("unable to locate UF2 device: " + volume)
-       }
+}
 
        return moveFile(tmppath, filepath.Dir(d[0])+"/flash.uf2")
 }
```

tinygo flash the program correctly.

but I do not know the right way that to fix this problem.

let me know your opinion?

thanks.

**Comment by aykevl** [comment]
This issue has most likely already been fixed in the dev branch: https://github.com/tinygo-org/tinygo/pull/858.

Can you test with the dev branch? Feel free to reopen if it hasn't been fixed.
