### ISSUE TITLE
Missing 0.12.0 Windows release

### ISSUE THREAD

**Issue by ethanent** [tinygo-org/tinygo#887]
https://github.com/tinygo-org/tinygo/releases/download/v0.12.0/tinygo0.12.0.windows-amd64.zip does not exist and is linked to from https://tinygo.org/getting-started/windows/

**Comment by deadprogram** [comment]
Whoops! @aykevl if you can upload that otherwise I will do it in a few hours, hopefully.

**Comment by alankrantas** [comment]
Any updates yet?

**Comment by gshields** [comment]
Looking at github the whole ./releases path is gone

**Comment by aykevl** [comment]
Done!

It took a while because we were at FOSDEM.
