### ISSUE TITLE
Windows 10, can’t compile the project.

### ISSUE THREAD

**Issue by evseevt** [tinygo-org/tinygo#909]
Need help, i am newbie)

**Error in VS Code:**
cannot find package "machine" in any of:
	C:\Go\src\machine (from $GOROOT)
	E:\Development\Go\projects\src\machine (from $GOPATH)

**VS Code terminal**
#Env and PATH
PS E:\Development\Go\projects> tinygo version
tinygo version 0.12.0 windows/amd64 (using go version go1.13.8)
PS E:\Development\Go\projects> tinygo env
GOOS="windows"
GOARCH="amd64"
GOROOT="C:\\Go"
GOPATH="E:\\Development\\Go\\projects;"
GOCACHE="C:\\Users\\Никита\\AppData\\Local\\tinygo"
CGO_ENABLED="1"
TINYGOROOT="C:\\tinygo"
PS E:\Development\Go\projects> tinygo run src/main/main.go
# runtime
C:\tinygo\src\runtime\gc_conservative.go:45:53: undeclared name: heapStart
C:\tinygo\src\runtime\scheduler.go:38:21: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:229:10: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:234:10: undeclared name: ticks
C:\tinygo\src\runtime\scheduler.go:239:53: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:243:26: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:259:16: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:263:39: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:266:4: undeclared name: sleepTicks
C:\tinygo\src\runtime\scheduler.go:267:7: undeclared name: asyncScheduler
C:\tinygo\src\runtime\scheduler.go:193:44: undeclared name: tickMicros
C:\tinygo\src\runtime\scheduler.go:198:35: undeclared name: tickMicros
C:\tinygo\src\runtime\scheduler.go:199:9: undeclared name: ticks
C:\tinygo\src\runtime\scheduler.go:133:2: undeclared name: sleepTicks
C:\tinygo\src\runtime\scheduler.go:133:13: undeclared name: timeUnit
C:\tinygo\src\runtime\scheduler.go:133:33: undeclared name: tickMicros
C:\tinygo\src\runtime\runtime.go:83:15: undeclared name: ticks
C:\tinygo\src\runtime\runtime.go:83:26: undeclared name: tickMicros
C:\tinygo\src\runtime\print.go:277:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:278:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:282:4: undeclared name: putchar
C:\tinygo\src\runtime\print.go:284:4: undeclared name: putchar
C:\tinygo\src\runtime\print.go:269:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:247:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:256:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:258:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:200:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:201:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:196:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:189:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:182:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:177:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:89:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:84:2: undeclared name: putchar
C:\tinygo\src\runtime\print.go:73:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:65:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:35:4: undeclared name: putchar
C:\tinygo\src\runtime\print.go:26:3: undeclared name: putchar
C:\tinygo\src\runtime\print.go:14:3: undeclared name: putchar
C:\tinygo\src\runtime\panic.go:20:2: undeclared name: abort
C:\tinygo\src\runtime\panic.go:13:2: undeclared name: abort
C:\tinygo\src\runtime\gc_conservative.go:378:35: undeclared name: heapEnd
C:\tinygo\src\runtime\gc_conservative.go:184:15: undeclared name: heapEnd
C:\tinygo\src\runtime\gc_conservative.go:184:25: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:190:15: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:191:13: undeclared name: heapEnd
C:\tinygo\src\runtime\gc_conservative.go:195:33: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:196:33: undeclared name: heapEnd
C:\tinygo\src\runtime\gc_conservative.go:209:25: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:172:42: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:158:42: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:149:42: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:141:42: undeclared name: heapStart
C:\tinygo\src\runtime\gc_conservative.go:96:47: undeclared name: heapEnd
PS E:\Development\Go\projects>

**Follow link:**
Unable to open '\tinygo\src\runtime\gc_conservative.go:378:35': resource is not available.

**Comment by aykevl** [comment]
What are you trying to do?

TinyGo does not yet support Windows as a compiler target. The compiler runs on Windows, but it cannot yet create Windows binaries. And this is what TinyGo defaults to with no other flags.

If you want to compile a binary for a microcontroller board or for webassembly, use the `-target` flag.

**Comment by evseevt** [comment]
I'm using Windows and WSL (Ubuntu), command "tinygo build -o main/main.hex -target arduino main/main.go", and get .hex file compile correctly =). 

But in Proteus simulator [http://bit.do/fwhNt](url), generated .hex file (tinygo) don't work.. Arduino-IDE compile .hex work's fine. It problem in Proteus or in tinygo?

I want upload tinygo .hex file into Arduino Proteus simulator...
**Video demonstration** : [https://youtu.be/omDvPYhQCMU](url)

**Comment by evseevt** [comment]
> What are you trying to do?
> 
> TinyGo does not yet support Windows as a compiler target. The compiler runs on Windows, but it cannot yet create Windows binaries. And this is what TinyGo defaults to with no other flags.
> 
> If you want to compile a binary for a microcontroller board or for webassembly, use the `-target` flag.
I'm using Windows and WSL (Ubuntu), command "tinygo build -o main/main.hex -target arduino main/main.go", and get .hex file compile correctly =).

But in Proteus simulator http://bit.do/fwhNt, generated .hex file (tinygo) don't work.. Arduino-IDE compile .hex work's fine. It problem in Proteus or in tinygo?

I want upload tinygo .hex file into Arduino Proteus simulator...
Video demonstration : https://youtu.be/omDvPYhQCMU

**Comment by evseevt** [comment]
> What are you trying to do?
> 
> TinyGo does not yet support Windows as a compiler target. The compiler runs on Windows, but it cannot yet create Windows binaries. And this is what TinyGo defaults to with no other flags.
> 
> If you want to compile a binary for a microcontroller board or for webassembly, use the `-target` flag.

I'm using Windows and WSL (Ubuntu), command "tinygo build -o main/main.hex -target arduino main/main.go", and get .hex file compile correctly =).

But in Proteus simulator http://bit.do/fwhNt, generated .hex file (tinygo) don't work.. Arduino-IDE compile .hex work's fine. It problem in Proteus or in tinygo?

I want upload tinygo .hex file into Arduino Proteus simulator...
Video demonstration : https://youtu.be/omDvPYhQCMU

**Comment by evseevt** [comment]
TinyGo code:

package main

// This is the most minimal blinky example and should run almost everywhere.

import (
	"machine"
	"time"
)

func main() {
	led := machine.LED
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})
	for {
		led.Low()
		time.Sleep(time.Millisecond * 500)

		led.High()
		time.Sleep(time.Millisecond * 500)
	}
}

**Comment by aykevl** [comment]
I think that Protheus is not able to correctly simulate the binaries produced by TinyGo. They work fine for me on real hardware.
I have attached a hex file that definitely works (renamed from test.hex to test.hex.txt for GitHub).

[test.hex.txt](https://github.com/tinygo-org/tinygo/files/4244722/test.hex.txt)

**Comment by evseevt** [comment]
> I think that Protheus is not able to correctly simulate the binaries produced by TinyGo. They work fine for me on real hardware.
> I have attached a hex file that definitely works (renamed from test.hex to test.hex.txt for GitHub).
> 
> [test.hex.txt](https://github.com/tinygo-org/tinygo/files/4244722/test.hex.txt)

This problem in Proteus, I uploaded in my real board .hex from Ubuntu and Windows compiler, TinyGo .hex file works corretly in board. This question is closed, thanks for the support.
