### ISSUE TITLE
Not work with Go 1.14

### ISSUE THREAD

**Issue by prospero78** [tinygo-org/tinygo#930]
Plis update yuors compiler to go 1.14. (only with 1.13.8 up)

**Comment by jaddr2line** [comment]
This is WIP - see #901

**Comment by woat** [comment]
For those looking for a workaround without disturbing your env, I found a quick and easy way to do it.

Download a compatible version of go as described in [official docs](https://golang.org/doc/install#extra_versions):
```
$ go get golang.org/dl/go1.13
$ go1.13 download
```

You can now use ```GOROOT=`go1.13 env GOROOT` tinygo```. Set that as an alias for convenience.

**Comment by deadprogram** [comment]
This has now been released, so closing. Thanks!
