### ISSUE TITLE
AVR does not support concurrency

### ISSUE THREAD

**Issue by yevsya-git** [tinygo-org/tinygo#931]
Traget board : Arduino UNO.
Goal : I want to use parallelism Go on atmega328p.
Result : 2 led -> blink only one.

Code :
```
package main

import (
	"machine"
	"time"
)

func main() {
	go led1()
	led2()
}

func led1() {
	led := machine.Pin(2)
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})
	for {
		led.Low()
		time.Sleep(time.Millisecond * 1000)

		led.High()
		time.Sleep(time.Millisecond * 1000)
	}
}

func led2() {
	led := machine.Pin(3)
	led.Configure(machine.PinConfig{Mode: machine.PinOutput})
	for {
		led.Low()
		time.Sleep(time.Millisecond * 420)

		led.High()
		time.Sleep(time.Millisecond * 420)
	}
}
```

**Comment by jaddr2line** [comment]
Currently goroutines are not supported on AVR due to bugs in the LLVM backend.

**Comment by aykevl** [comment]
Yeah, it's not yet supported. I started some work but never finished it.

**Comment by jaddr2line** [comment]
PR #961 added support for goroutines. They are turned off by default though, as most AVR boards do not have all that much memory to work with.
