### ISSUE TITLE
flash: unable to flash UF2 device using Fedora

### ISSUE THREAD

**Issue by perryrivera** [tinygo-org/tinygo#954]
**Distro**: Fedora 31
**tinygo version**: 0.11.0

$ **ls -al /dev/ttyACM0** 
crw-rw----. 1 root dialout 166, 0 Mar 14  2020 /dev/ttyACM0

$ **groups**
my_username wheel dialout docker

$ **tinygo flash -target=pybadge main.go**

error: failed to flash /tmp/tinygo_xxxxxx_/main.uf2: unable to locate UF2 device: PYBADGEBOOT

$ **id -a**
uid=_xxxx_(my_username) gid=_xxxx_(my_username) groups=_xxxx_(my_username),10(wheel),_xx_(dialout),971(docker) context=unconfined_(etc. etc.)

I've also tried:
$ **tinygo flash -port=/dev/ttyACM0 -target=pybadge main.go**

However...
I can easily copy UF2 files directly to the PYBADGEBOOT over USB with no issues.

How can I get tinygo flashing to work on Fedora 31?

**Comment by aykevl** [comment]
What is the location of the PYBADGEBOOT directory? You can get it with the `mount` command. On Debian it's usually `/home/<username>/PYBADGEBOOT`.

**Comment by aykevl** [comment]
As a temporary workaround, you can write it manually to the device. For example:

    tinygo build -o /home/$USER/PYBADGEBOOT/firmware.uf2 -target=pybadge main.go

**Comment by deadprogram** [comment]
The location of this drive on Fedora is not the same as Debians. We ran into this exact problem recently at our workshop at SCaLE.

I think someone was going to submit a PR that added the correct path.

**Comment by perryrivera** [comment]
> What is the location of the PYBADGEBOOT directory? You can get it with the `mount` command. On Debian it's usually `/home/<username>/PYBADGEBOOT`.

According to the Files app, the directory is:
/run/media/(my_username)/PYBADGEBOOT

**Comment by perryrivera** [comment]
Thanks @aykevl !

> As a temporary workaround, you can write it manually to the device. For example:
> 
> ```
> tinygo build -o /media/$USER/PYBADGEBOOT/firmware.uf2 -target=pybadge main.go
> ```

This workaround appears to work (note the path below):
tinygo build -o /run/media/$USER/PYBADGEBOOT/firmware.uf2 -target=pybadge main.go

**Comment by perryrivera** [comment]
> The location of this drive on Fedora is not the same as Debians. We ran into this exact problem recently at our workshop at SCaLE.
> 
> I think someone was going to submit a PR that added the correct path.

@deadprogram : Does the PR need to be submitted here or somewhere at Fedora? This looks like a tinygo building / flash issue. Does issue 954 serve as notice? :)

**Comment by perryrivera** [comment]
Not sure if this related, but I get this new error trying to flash the name badge code:
$ **tinygo build -o /run/media/$USER/PYBADGEBOOT/firmware.uf2 -target=pybadge main.go**
# main.go
main.go:25:22: SPI1_MISO_PIN not declared by package machine

Changing the code from MISO to MIS0 doesn't appear to help....

**Comment by deadprogram** [comment]
Regarding the path to the badge for flashing, that would be a PR here, please.

Regarding the SPI1 compile error, which program are you trying to build?

**Comment by aykevl** [comment]
The relevant code is here: https://github.com/tinygo-org/tinygo/blob/master/main.go#L483
It locates the correct path simply by globbing at a well-known location (that unfortunately varies between distros).

**Comment by Elara6331** [comment]
Experiencing the same issue on Arch. The path for drives on Arch is `/run/media/<user>/<drive name>`.

**Comment by Elara6331** [comment]
Another workaround is creating a symlink, like so: `sudo ln -s /run/media/$USER /media/$USER`. After this, `tinygo flash` should just work.

**Comment by aykevl** [comment]
Is there someone who would make a PR to fix this? The relevant code is here:

https://github.com/tinygo-org/tinygo/blob/a9ba6ebad9ad85cacd9674a1af9229489a811f68/main.go#L498-L499

It doesn't need any special knowledge, but is much easier done when you're actually running Fedora or Arch (which I don't).

**Comment by Elara6331** [comment]
I will try to make a PR. Should be ready soon if I don't encounter any issues.

**Comment by Elara6331** [comment]
I've just created a PR that seems to fix it. Only tested on Arch, not Fedora or Debian.

**Comment by Elara6331** [comment]
I accidentally made my previous PR against release. Sorry about that. Anyway, I've created a new PR and changed it to work with pre-1.16 versions. If someone could look at it, and test it on Debian and Fedora, that would be much appreciated. Thank you.

**Comment by deadprogram** [comment]
I think that this has been resolved with https://github.com/tinygo-org/tinygo/pull/3816 so tagging to close on next release.

**Comment by deadprogram** [comment]
Closing since this is part of release 0.29.0 thanks!
